### ISSUE TITLE
#7 问题依然存在。http://211.159.163.83/h5/content-hub/index/4

### ISSUE THREAD

**Issue by allycs** [mescroll/mescroll#10]
#7 

- 测试地址

http://211.159.163.83/h5/content-hub/index/4

http://211.159.163.83/h5/content-hub/4

- 测试环境

真机：6p\6sp\ipad min 2 \7p

- 现象

数据不足一页，当下拉出现了“释放更新”则不显示了，在此下拉到还未出现“释放更新”则会显示

**Comment by mescroll** [comment]
我晚上看一下哈 白天有点忙

**Comment by mescroll** [comment]
注销掉style.css的.list_item的overflow: hidden; 样式即可;
另外我看到您项目的overflow: hidden; 有点滥用了哦, body,很多div都在设置overflow: hidden;这个会出现一些意想不到的问题呢; 简化一下代码吧
