### ISSUE TITLE
配置dom节点为父级后,往下滑一段之后,无法滑动回去.

### ISSUE THREAD

**Issue by cxylys** [mescroll/mescroll#104]
目前在PC端的手机模拟上是可以向上拉动,但是拉完之后无法再向下拉动,鼠标滚轮可以滑动,手机端则是往上滑动之后无法往下滑回去了,就卡在那里。

**Comment by veah** [comment]
我的情况同楼上。但是我注意到这个问题发生是由于设置了 down 配置中的设置 use: false 而引发的。

**Comment by chenendian** [comment]
所以  你们最后怎么解决的  我的down下面并没有配置use:false

**Comment by chenendian** [comment]
历经两个小时终于找到原因了   给那个父级标签设置position：absolute

**Comment by chenendian** [comment]
知道原因了  没有将mescroll初始化的时候将页面所有的东西都放在这个mescroll里面
