### ISSUE TITLE
使用 mescroll  用vue 开发 在ios 手机滑动卡顿

### ISSUE THREAD

**Issue by 18510758841** [mescroll/mescroll#107]
情况是这样的，正常写一个不是懒加载的列表滑动很流畅，使用mescroll开始可以滑动，一旦不滑动，滚动条隐藏后，在滑动屏幕就不能滑动了，卡死在一个位置不动

**Comment by mescroll** [comment]
应该是mesrcoll这个div的 -webkit-overflow-scrolling: touch 样式被覆盖了..  检查一下哦

**Comment by 18510758841** [comment]
你好,解决了，在css文件中 .mescroll样式中加固定定位就滑动流畅了ios和安卓都解决了

**Comment by mescroll** [comment]
哈哈 那就是没有设置高度的原因  overflow:auto没有生效 
http://www.mescroll.com/qa.html#q2
