### ISSUE TITLE
禁止下拉刷新的时候，再下拉拉不动，正常情况下应该会出现滚动条，内容被拉离顶部一小段距离。

### ISSUE THREAD

**Issue by qingma1** [mescroll/mescroll#109]
var mescroll = new MeScroll("mescroll", {
				down: {
					use: false,
					auto: false,
					callback: function() {
						// do something
					},
				},
				up: {
					auto: false,
					callback: pullUpRefresh, 
					toTop: {
						src: "../../images/fan_top.png", //默认滚动到1000px显示,可配置offset修改
					},
					onScroll: function() {
						// do something
					}
				},
			});

**Comment by mescroll** [comment]
恩恩 内部我禁止掉了.. 我想想如果禁止下拉把bounce开启.. 感谢反馈~
