### ISSUE TITLE
关于在vue上的一个小问题及解决

### ISSUE THREAD

**Issue by qq568687535** [mescroll/mescroll#11]
引入的mescroll.js 中一处语法报错
![image](https://user-images.githubusercontent.com/22974194/29440541-7200b086-83f8-11e7-82ba-1fb6f10b871a.png)
建议在源码中修改下，
![image](https://user-images.githubusercontent.com/22974194/29440546-83faa8b4-83f8-11e7-8c4a-36f3c34c9bae.png)

**Comment by mescroll** [comment]
O(∩_∩)O谢谢

**Comment by mescroll** [comment]
新增vue的示例, http://www.mescroll.com/preview.html?name=list-products-vue
另外 mescroll更新至1.1.5
