### ISSUE TITLE
如何设置当数量不满一屏幕时 禁止上拉加载

### ISSUE THREAD

**Issue by MirrorFlower** [mescroll/mescroll#110]
如何设置当数量不满一屏幕时 禁止上拉加载

**Comment by mescroll** [comment]
不满屏 也有可能还有下一页呢 ..     禁止的话就再也翻不到下一页了吧..

如果非要禁止 可以设置mescroll.endSuccess(1, false); //第二个参数hasNext为false即可

**Comment by MirrorFlower** [comment]
大佬 再请教一下，那个吸顶悬浮效果，在IOS手机上，当缓慢向上滑动列表时，nav导航条出现抖动的情况  还有当突然猛的向上滑动时候，导航条会出现跟着列表先一块上去了，过了一会儿才回来悬浮在顶部

**Comment by MirrorFlower** [comment]
/*android和pc端悬停*/

        .nav-fixed {
            z-index: 9999;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
        }

.nav-sticky {
            z-index: 9999;
            /*需设置zIndex,避免在悬停时,可能会被列表数据遮住*/
            position: -webkit-sticky;
            position: sticky;
            top: 0;
            /*相对mescroll的div悬停的位置*/
        }



var navWarp = $api.byId('navWarp');
        navWarp.style.height = navWarp.offsetHeight + "px"; //固定高度占位,避免悬浮时列表抖动;
        mescroll.optUp.onScroll = function(mescroll, y, isUp) {
            if (y >= 150) {
                if (api.systemType == 'ios') {
                    $api.addCls($api.byId('navWarp'), 'nav-sticky');
                } else {
                    $api.addCls($api.byId('nav'), 'nav-fixed');
                }
            } else {
                if (api.systemType == 'ios') {
                    $api.removeCls($api.byId('navWarp'), 'nav-sticky');
                } else {
                    $api.removeCls($api.byId('nav'), 'nav-fixed');
                }
            }
        }

请大佬帮忙看一下什么问题

**Comment by MirrorFlower** [comment]
我发现IOS在第一次快速上滑过程中 只有当列表停下来的时候  才获取去上滑的距离 才去添加的样式
