### ISSUE TITLE
上拉刷新 auto 设置无效

### ISSUE THREAD

**Issue by hooray** [mescroll/mescroll#111]
我在up里设置auto为false，希望仅初始化控件，但不需要默认加载第一页数据，但实际效果还是会触发一次上拉回调

**Comment by hooray** [comment]
版本为1.3.1

**Comment by hooray** [comment]
更新到1.3.2问题依旧存在

**Comment by mescroll** [comment]
down的callback 你是不是也调了up的callback方法呢  检查一下哦
