### ISSUE TITLE
使用 mescroll 用vue 开发，android手机端，从后台恢复的前台后，当前页面卡主不动了

### ISSUE THREAD

**Issue by xiaojun515688** [mescroll/mescroll#113]
整个屏幕就卡在那里了，不能滑动了

**Comment by mescroll** [comment]
有重现的demo吗? 发一份到我邮箱 mescroll@qq.com

**Comment by chenpengjun** [comment]
每次组件的生命周期结束后，去卸载组件，this.state.mescroll.destroy()

**Comment by 565784135** [comment]
> 每次组件的生命周期结束后，去卸载组件，this.state.mescroll.destroy()

ios，首页进入列表页,再返回首页会出现页面不能滑动的情况，也是去要手动卸载
···
beforeDestroy(){
      this.mescroll.destroy();
    }
···

**Comment by yun0926** [comment]
> > 每次组件的生命周期结束后，去卸载组件，this.state.mescroll.destroy()
> 
> ```
> ios，首页进入列表页,再返回首页会出现页面不能滑动的情况，也是去要手动卸载
> beforeDestroy(){
>       this.mescroll.destroy();
>     }
> ```
必须要销毁之前的页面吗？

**Comment by yun0926** [comment]
> 有重现的demo吗? 发一份到我邮箱 [mescroll@qq.com](mailto:mescroll@qq.com)

只有在魅族手机上能重现
