### ISSUE TITLE
在微信公众号，ios11.3以下的版本会卡死，动不了。

### ISSUE THREAD

**Issue by py1568** [mescroll/mescroll#122]
在微信公众号，ios11.3以下的版本会卡死，进页面如果聊天框消息不满一屏可以拉动页面，满了一屏就卡死不动了，页面使用了flex布局，但是好像不是这个的原因，写固定的高度也不能滑动。安卓和最新版的ios都没问题。好苦恼啊。

**Comment by py1568** [comment]
已经解决了，重新看了一下文档，我把isBounce属性加到了down下面。所以卡死了。

**Comment by py1568** [comment]
认真看文档很重要~~~

**Comment by acme-h** [comment]
你用的vue吗？
