### ISSUE TITLE
在vue-cli中使用只要出现了返回顶部按钮就会一直显示

### ISSUE THREAD

**Issue by qdlyh** [mescroll/mescroll#123]
只要出现了返回顶部按钮就会一直显示，包括切换页面也还是显示存在，请问为什么？
代码就正常参考官方的vue中的demo

**Comment by mescroll** [comment]
回到顶部的按钮是动态添加到body中的哦  可以在切换界面的时候调用mescroll.hideTopBtn()先隐藏

**Comment by mescroll** [comment]
在iOS的惯性滚动中, fixed元素在overflow:auto的div里面确实会抖动;
所以回到顶部的按钮我添加到了mescroll这个div的外面 在body中
