### ISSUE TITLE
上拉加载数据至END后出现遮挡

### ISSUE THREAD

**Issue by luo201227** [mescroll/mescroll#124]
上拉加载，如果已经没有剩余数据出现END后，整个区域出现遮挡，无法点击列表中任何数据

**Comment by mescroll** [comment]
<div id="mescroll" class="mescroll"> //id可以改,而"mescroll"的class不能删
	   		<div>
		       		//内容数据需写在一个div或ul里面,确保mescroll初始化时,上拉加载的进度布局能够在这个div或ul的底部.
	    		</div>
	    	</div>

**Comment by mescroll** [comment]
`<div id="mescroll" class="mescroll"> //id可以改,而"mescroll"的class不能删
	   		<div>
		       		//内容数据需写在一个div或ul里面,确保mescroll初始化时,上拉加载的进度布局能够在这个div或ul的底部.
	    		</div>
	    	</div>`

**Comment by luo201227** [comment]
肯定不是你说的这些问题，而是说：加载到没有数据时，底部出现end，此时数据渲染区域则会被一个遮罩层元素覆盖，无法点击原数据列表中的任何数据
