### ISSUE TITLE
下拉刷新后，隐藏那个下拉区域的时机能不能改改，详情请看描述

### ISSUE THREAD

**Issue by xiaojun515688** [mescroll/mescroll#126]
下拉刷新时，只要后台一返回结果，立马就把下拉刷新区域隐藏了，但其实数据回来后还有一个渲染页面的过的过程，在同一时间内，这两个操作时同时进行的，渲染的页面元素少的时候没有感觉，元素稍微一多就会出现卡顿闪屏的效果，希望这个隐藏的时机可以在页面渲染完成后隐藏，或者给一个可控制的时间值去定时隐藏，不知道说这么多是否很 明确表达出了我的需求，如有表达不清的还请见谅啊，大神

**Comment by mescroll** [comment]
mescroll.endSuccess的意思就是隐藏下拉区域
所以你可以在渲染完成元素后 才调用mescroll.endSuccess即可
