### ISSUE TITLE
如何动态加载多页数据？订单列表修改后需要刷新列表，位置依然不变

### ISSUE THREAD

**Issue by charrysong** [mescroll/mescroll#127]
比如订单数据列表，修改后变了，返回依然是旧缓存，所以这里就需要动态加载多页数据，以及恢复保存的位置。

**Comment by mescroll** [comment]
不知道你描述的场景是否这样:
比如点击的订单确认收货按钮,希望改变一下列表数据的显示状态, 

如果希望位置不变,那么就只能单单改这一条数据了
方法一: 确认收货后,接口直接返回这一条订单的数据, 然后去当前列表这条数据
方法二: 确认收货后,再请求根据订单号查询订单数据的接口, 然后去替换当前列表这条数据
方法三:.确认收货后,直接把这一条数据改为已确认收货,显示的文案改一下

其实和mescroll没有关系了

**Comment by charrysong** [comment]
返回并不是刷新。
