### ISSUE TITLE
滚动到页面底部，返回到顶部后，返回顶部按钮不消失

### ISSUE THREAD

**Issue by pyyzcwg2833** [mescroll/mescroll#13]
我发现这么一个特点，在触底之前，返回顶部按钮一切表现正常。
但是一旦触底，无论是点击按钮，还是手动滚回到顶部，按钮均不消失

**Comment by mescroll** [comment]
亲 你的mescroll版本是1.1.5吗; 我记得我在1.1.2版本修复过的哦;
