### ISSUE TITLE
使用vue 2.0 开发移动端公众号。ios从列表(使用了mescroll)跳转到详情后，详情页会发生无法滑动的现象

### ISSUE THREAD

**Issue by linwenfeng122** [mescroll/mescroll#130]
我测试的两个ios系统。发现在系统11.3.1的手机下面正常。在系统11.1.2手机下面会出现这个这个问题

**Comment by mescroll** [comment]
可以参考这个链接的答案~
https://github.com/mescroll/mescroll/issues/80
