### ISSUE TITLE
scrollTo(200)

### ISSUE THREAD

**Issue by yangchongduo** [mescroll/mescroll#134]
这个 scrollTo(200) 这个数值是什么意思？
在ios 10.3.3下不好用？没有任何反应

**Comment by mescroll** [comment]
意思是向上滚动200px

前提是你的div内容超过了,mescroll这个div的高度,出现了滚动条,才能向上滚动.
检查一下你在调用这个方法的时候,内容是否满屏出现滚动条了呢
有可能有些图片没有出现,或者数据加载完,你调用的时候可能内容不满屏.
有Demo测试不
