### ISSUE TITLE
只有一页数据的时候  没有显示没有更多数据  

### ISSUE THREAD

**Issue by 18859231605** [mescroll/mescroll#135]
$(function(){
   //返回app
  $('.back_arrow').click(function(){
    window.location.href = "openmrb://close";
  })
  var id = getQueryString('floorId'); //楼层ID
   
  getBannerData(id);
  //拿banner数据
  console.log(path);
  function getBannerData(id) {
    var url = path + '/baseHomeFloor/1.1.0/queryById/' + id;
    $.get(url,function(res){
        if (res.code == 200) {
          var imgData = res.data.indexFloorImg;
          $('.banner img').attr('src',imgData)
          var flTitle =  res.data.title;
          document.title = flTitle;
          window.location.href = "openmrb://close?title=" + flTitle;
        }
    })
  }

  
  //实例化
  var mescroll = new MeScroll("mescroll", { 
        up: {
            callback: upCallback , //上拉加载的回调
            page:{
                num : 0 , 
                size : 10 , 
                time : null 
            },
            loadFull: {
                use: true, //列表数据过少,是否自动加载下一页,直到满屏或者无更多数据为止;默认false
                delay: 500 //延时执行的毫秒数; 延时是为了保证列表数据或占位的图片都已初始化完成,且下拉刷新上拉加载中区域动画已执行完毕;
            },
            isBounce: false, //此处禁止ios回弹,解析(务必认真阅读,特别是最后一点): http://www.mescroll.com/qa.html#q10
            clearEmptyId: "dataList", //1.下拉刷新时会自动先清空此列表,再加入数据; 2.无任何数据时会在此列表自动提示空
            empty:{ 
                warpId : null , 
                icon : null , 
                tip : "暂无相关数据~" , 
                btntext : "" , 
                btnClick : null ,
                supportTap : false 
            },
            htmlNodata: '<p class="upwarp-nodata">没有更多数据了~</p>', //无数据的布局
        }
    });

    /*上拉加载的回调 page = {num:1, size:10}; num:当前页 从1开始, size:每页数据条数 */
    function upCallback(page){
        //联网加载数据
        getListDataFromNet(page.num, page.size, function(curPageData,totalPage){
            //方法一(推荐): 后台接口有返回列表的总页数 totalPage
            mescroll.endBySize(curPageData.length, totalPage); //必传参数(当前页的数据个数, 总数据量)
            //设置列表数据
            setListData(curPageData);
        }, function(){
            //联网失败的回调,隐藏下拉刷新和上拉加载的状态;
            mescroll.endErr();
        });
    }
    
  //数据填充
  function setListData (curPageData) {
      var html = template('listTpl',{data:curPageData});
      $('#dataList').append(html);
  }
  //数据请求
  function getListDataFromNet(pageNum,pageSize,successCallback) {
      var url = path+'/baseHomeFloorList/1.1.0/findPageByFloorId?pageNo='+pageNum+'&pageSize='+pageSize+'&floorId='+id;
      $.ajax({
          type:'post',
          url:url,
          timeout:5000,
          headers: {
              'Content-type': 'application/json;charset=UTF-8'
          },
          dataType:'json',
          success:function(data){
              console.log(data)
              if(data.code==200){
                  var newArr = [];
                  var list = data.data.list;
                  var totalNum = data.data.total;   
                  newArr = list;
                  //联网成功的回调
                  successCallback&&successCallback(newArr,totalNum);
              }else{
                  mescroll.optUp.empty.tip = data.message;
              }
          },
          error:function(e){
              mescroll.endErr();
          },
          complete: function (XMLHttpRequest,status) {
              if(status == 'timeout') {
                  XMLHttpRequest.abort();    // 超时后中断请求
                  mescroll.optUp.empty.tip = '网络请求超时，请刷新~';
                  mescroll.showEmpty();
              }
          }
      })
  }

  //返回app详情页
  $(document).on('click','#dataList dl',function(){
        var id = $(this).data("id");
        var isSupportHome = $(this).data("issupporthome");
        var isSupportStore  = $(this).data("issupportstore");
        window.location.href = 'openmrb://appDetails?id='+ id + '&isSupportHome?=' + isSupportHome + '&isSupportStore=' + isSupportStore;
  })    
})

**Comment by mhxy13867806343** [comment]
解决了没？

**Comment by book-qian** [comment]
没有啊

**Comment by book-qian** [comment]
@作者 不是说48小时回复吗

**Comment by mescroll** [comment]
http://www.mescroll.com/api.html#tagNoMoreSize
