### ISSUE TITLE
往上拉到最后一页，不能继续往上拉拖拽然后回弹效果

### ISSUE THREAD

**Issue by freezyh** [mescroll/mescroll#136]
当一直往上拉，直到数据是最后一页的时候，不能往上继续拖拽，虽然最后一页尾部提示了--END--，但是不能往上拖拽然后回弹，感觉很生硬，会觉得卡死了一样，体验没那么好，能否优化下，最后一页还可以往上拖拽回弹动效

**Comment by mescroll** [comment]
你应该配置了 isBounce:false
不配置或者isBounce:true就好了

http://www.mescroll.com/qa.html?v=1219#q10
