### ISSUE TITLE
神奇的mescroll-upwarp

### ISSUE THREAD

**Issue by cn-xufei** [mescroll/mescroll#137]
你好，我只配置了up，然后mescroll 中， mescroll-upwarp这块div一直占用着mescroll的高度
![image](https://user-images.githubusercontent.com/14144811/43555643-0f67cede-962e-11e8-9fb6-eda57e1fef97.png)
导致列表顶部一直有60px的存在，百思不得姐啊，另外我给mescroll设置了高度

**Comment by xxvv** [comment]
我也遇到了，出现这个的情况，是pagesize大于返回的数据时候

**Comment by mescroll** [comment]
<div id="mescroll" class="mescroll"> //id可以改,而"mescroll"的class不能删, 且需保证这个div要有高度哦
	   		<div> //这个div不能删, 可以改成ul或者其他容器标签. 确保mescroll初始化时,上拉加载的进度布局能够在这个div或ul的底部
		       	 //内容
	    		</div>
	    	</div>

**Comment by cn-xufei** [comment]
@mescroll 多谢，当时就是忽略了这里

**Comment by lucky1213** [comment]
> <div id="mescroll" class="mescroll"> //id可以改,而"mescroll"的class不能删, 且需保证这个div要有高度哦 <div> //这个div不能删, 可以改成ul或者其他容器标签. 确保mescroll初始化时,上拉加载的进度布局能够在这个div或ul的底部 //内容 </div> </div>

能给这个div加class吗？

**Comment by mescroll** [comment]
可以加class呢
