### ISSUE TITLE
在轮播导航（ mescroll-swiper-nav ）中，可否在下拉刷新的同时添加屏蔽左右滑动功能？

### ISSUE THREAD

**Issue by hishosho** [mescroll/mescroll#138]
首先，感谢作者提供了这个精致的框架！
我在使用轮播导航（mescroll-swiper-nav）时，发现在触发下拉刷新时，依旧可以进行左右滑动。可否加一个配置，使用户在下拉刷新数据时，屏蔽左右滑动的功能？
感谢！

**Comment by mescroll** [comment]
感谢反馈, 我测试了一下,下拉的时候没法左右滑动. 你的操作应该是先左右滑动,同时下拉对吧...
这个..我想想如何屏蔽了^_^
