### ISSUE TITLE
down 和up里面的auto设置为true有坑啊，有些手机进来不会自动调用回调，比如现在测出来红米2，三星，和荣耀偶现过不回调的时候

### ISSUE THREAD

**Issue by Jason8Zhang** [mescroll/mescroll#139]
如题，之前都是写了auto为true，但发现老是会出现不回调的问题，我就把这个全写成false了，在生命周期里面自己调一下接口，防止进来以后没有数据，页面一直loading

 down: {
        auto: false,
        callback: this.downCallback
      },
      up: {
        auto: false,
        isBounce: false,
        noMoreSize: 0,
        callback: this.upCallback,
        htmlLoading: `<div id="databottom" class="data-bottom">
                    <div class="load">
                    </div>
                    <div class="text" id="bottomtext">更多产品正在赶来</div>
                  </div>`,
        htmlNodata: `<div class="no-data ${this.type != 12 ? 'no-other' : ''}" >
                        <div class="no-datas">
                          <div class="no-datas-text">已经到底啦</div>
                        </div>
                        <div class="other-pro" onclick="toProductlist('${this.codeData.type+";dkdq;w"+this.codeData.todkdq}')">${ this.type != 12 ? '没有合适产品?立即进入<span>贷款大全></span>' : ''}</div>
                    </div>`,
      }

**Comment by mescroll** [comment]
如果你的down和up处理的回调是一样的, 那么down就不用写了. 直接写up:{auto:true,callback:this.upCallBack}
