### ISSUE TITLE
end没显示在最低端

### ISSUE THREAD

**Issue by FlayWay** [mescroll/mescroll#14]
一行显示两排数据   上拉加载更多时   加载数据是奇数时end显示在右半部分了

**Comment by mescroll** [comment]
已经远程帮你解决了哈, 原因你的列表的 li 使用了float:left 没有及时clear 
解决方法一:
li {float:left,width: 30%;}
.mescroll-upwarp {clear:left} //清除float
解决方法二:
不使用float
li:{display: inline-block,width: 50%;}
