### ISSUE TITLE
下拉刷新后,显示end 然后不能上拉

### ISSUE THREAD

**Issue by master-G7** [mescroll/mescroll#140]
下拉刷新后,显示end 然后不能上拉,不懂是啥情况

**Comment by mescroll** [comment]
估计您的 mescroll.endSuccess传了0



//联网成功的回调,隐藏下拉刷新和上拉加载的状态;
					//mescroll会根据传的参数,自动判断列表如果无任何数据,则提示空,显示empty配置的内容;
					//列表如果无下一页数据,则提示无更多数据,(注意noMoreSize的配置)
					
					//方法一(推荐): 后台接口有返回列表的总页数 totalPage
					//必传参数(当前页的数据个数, 总页数)
					//mescroll.endByPage(curPageData.length, totalPage);
							
					//方法二(推荐): 后台接口有返回列表的总数据量 totalSize
					//必传参数(当前页的数据个数, 总数据量)
					//mescroll.endBySize(curPageData.length, totalSize);
							
					//方法三(推荐): 您有其他方式知道是否有下一页 hasNext
					//必传参数(当前页的数据个数, 是否有下一页true/false)
					//mescroll.endSuccess(curPageData.length, hasNext);
							
					//方法四 (不推荐),会存在一个小问题:比如列表共有20条数据,每页加载10条,共2页.
					//如果只根据当前页的数据个数判断,则需翻到第三页才会知道无更多数据
					//如果传了hasNext,则翻到第二页即可显示无更多数据.
					//mescroll.endSuccess(curPageData.length);

**Comment by master-G7** [comment]
setTimeout(() => {
            ajax('getorders', {
                pageidx: page
            }, 'POST', function (data) {
                mescroll.endByPage(data.orders.length, data.totalpage)
                orderList = data.orders
                var html = template('List', orderList)
                $('.list').append(html)
            })
        }, 1000);
您好,我之前就已经按文档配置了,可是还是这样
