### ISSUE TITLE
为什么要通过有多少页，或者有多少记录来判断是否到最后

### ISSUE THREAD

**Issue by zeroone2005** [mescroll/mescroll#141]
为什么要通过这个来判断。而不是通过是否有返回数据来判断呢。 如果没有数据，直接终止下拉或者上拉来加载。如果有数据直接累加分页计数就不就好了。不用每次都传入数量或者总页数，也不需要每次都去服务端查询记录总数，或者总页数。

**Comment by mescroll** [comment]
每个人设计的接口都不大一样,你的这个情况建议用方法三.
传多少条记录,其实还有另外的目的就是NoMoreSize的配置
http://www.mescroll.com/api.html#tagNoMoreSize

//方法一(推荐): 后台接口有返回列表的总页数 totalPage
					//必传参数(当前页的数据个数, 总页数)
					//mescroll.endByPage(curPageData.length, totalPage);
							
					//方法二(推荐): 后台接口有返回列表的总数据量 totalSize
					//必传参数(当前页的数据个数, 总数据量)
					//mescroll.endBySize(curPageData.length, totalSize);
							
					//方法三(推荐): 您有其他方式知道是否有下一页 hasNext
					//必传参数(当前页的数据个数, 是否有下一页true/false)
					//mescroll.endSuccess(curPageData.length, hasNext);
