### ISSUE TITLE
数据不满一页时无法触发上拉加载

### ISSUE THREAD

**Issue by TroyBug** [mescroll/mescroll#142]
我的数据接口是如下形式：
api?page=1&rows=3
rows表示取几条数据，现在我有4条数据，首次加载时只显示3条，未满一屏，正常情况下应该还有一条数据，但底部显示了end而且无法上拉加载了，
现在的代码是这样的
初始化：
```javascript
up: {
    callback: upCallback,
    isBounce: false,
    auto:true
}
```
数据加载：
```javascript
function upCallback(page) {
    page.size = 3;
    loadData('api',{rows:page.size,page:page.num},function(data) {
        //...填充列表...

        mescroll.endBySize(10, data.total);
    });
}
```
请问如何处理这种情况呢？非常感谢~~~

**Comment by mescroll** [comment]
你输出一下data.total确定返回的是4条吗 会不会没有取到值? 如果传0的话,就说明没有数据,会显示end的.. 

另外:
mescroll.endBySize(data.length, data.total); //第一个参数是当前页获取到的数据条数  注意是当前页的条数 应该是3   不是10 ..

**Comment by TroyBug** [comment]
@mescroll 非常感谢你的帮助，我之前不太理解endBySize，所以传了个10，现在改成3就好了
