### ISSUE TITLE
求教当查询条件改变的时候，怎么调用mescroll.resetUpScroll方法

### ISSUE THREAD

**Issue by pianaiqianduan** [mescroll/mescroll#143]

**Comment by pianaiqianduan** [comment]
@mescroll

**Comment by mescroll** [comment]
切换条件之后 直接调用mescroll.resetUpScroll
mescroll.resetUpScroll的意思就是把page.num=1 然后出发up的callback

http://www.mescroll.com/preview.html?name=list-mescroll-one
