### ISSUE TITLE
ios中当页面存在定位的动画时（不在mescroll的div里），滑动有闪烁和抖动情况

### ISSUE THREAD

**Issue by wawss** [mescroll/mescroll#144]
测试了iPhonex和iphone 6存在这种情况。去掉动画（css3弹幕动画）就好了。动画定位父级是body。

**Comment by mescroll** [comment]
方便发一下html结构和css3的样式给我看看吗? 有demo最好了 Thanks♪(･ω･)ﾉ   mescroll@qq.com

**Comment by wawss** [comment]
不好意思，项目急已经换实现方式了

**Comment by mescroll** [comment]
好的 那我close先啦~
