### ISSUE TITLE
上拉加载，超过设置的offset后回到顶部按钮淡入后又立刻淡出，并不显示，但该区域仍可点击

### ISSUE THREAD

**Issue by HappyLittleFish** [mescroll/mescroll#145]
通过vue组件方式使用，mescroll样式是参考文档写的，不知道问题在哪？

**Comment by HappyLittleFish** [comment]
> +1
> 我的现象为vue run是好的，build完就不显示了

我最后自己写了一个回到顶部的按钮

**Comment by mescroll** [comment]
@PengliangC  你的路径应该没有写对吧  试试src改成网络地址看看~
