### ISSUE TITLE
含有tab页的页面，实例化两个mescroll，分别设置toTop，只有一个生效

### ISSUE THREAD

**Issue by demonrain** [mescroll/mescroll#146]
![image](https://user-images.githubusercontent.com/2246995/44838079-de8d1200-ac6d-11e8-81c1-c98e7944fca7.png)
类似这样的tab页，两边都需要上拉操作，已经实例化两个mescroll，也分别设置了toTop属性，warpId也试过，都只能是一个tab页生效

**Comment by mescroll** [comment]
切换tab的时候 需把前一个的top隐藏  

//隐藏当前回到顶部按钮
mescrollArr[curNavIndex].hideTopBtn();

http://www.mescroll.com/preview.html?name=list-mescroll-more
