### ISSUE TITLE
使用mescroll组件方式引用，内容不显示

### ISSUE THREAD

**Issue by JaminFan** [mescroll/mescroll#149]
使用mescroll组件方式引用，在PC chrome浏览器下可以正常显示，在手机端均无法显示

`<mescroll-vue  ref="mescroll" :down="mescrollDown" :up="mescrollUp" @init="mescrollInit" >
   ...
</mescroll-vue>`

**Comment by JaminFan** [comment]
只有ios不生效，Android是可以正常使用的

**Comment by mescroll** [comment]
方便提供重新问题的demo吗
Thanks♪(･ω･)ﾉ
