### ISSUE TITLE
如何处理 下拉刷新数据加载

### ISSUE THREAD

**Issue by matianqing** [mescroll/mescroll#15]
问题描述：如何处理【下拉刷新的时候，如果数据没有更改，则不清空数据】
	//TODO 在清除第一页数据的时候判断 是否是原有数据更改。如果数据有变化则下拉刷新重置页码为第一页，否则只执行动画刷新效果【不执行AJAX请求数据】；

以下为源码：采用的JS是  mescroll-for-muiscroll.js
		if(pageNum == 1) this.clearDataList(); //如果是第一页,自动清空第一页列表数据
-------------------------------------------------------------------------------------------------------------
/*回调成功
 *结束下拉刷新 meScroll.endSuccess();无参;
 *结束上拉加载 meScroll.endSuccess(dataSize, systime); 必须传dataSize:联网获取到的数据条数;用于判断列表是否还有数据.如果不传则仅隐藏加载中的状态;  systime:第一页的系统时间 (可空)
 */
MeScroll.prototype.endSuccess = function(dataSize, systime) {
	//结束下拉刷新
	if(this.isDownScrolling) this.endDownScroll();

	//结束上拉加载
	if(this.optUp.use) {
		var pageNum = this.optUp.page.num; //当前页码
		var pageSize = this.optUp.page.size; //每页长度
			//TODO 在清除第一页数据的时候判断 是否是原有数据更改。如果数据有变化则下拉刷新重置页码
		if(pageNum == 1) this.clearDataList(); //如果是第一页,自动清空第一页列表数据
		
		var isShowNoMore; //是否已无更多数据
		if(dataSize != null) {
			if(dataSize < pageSize) {
				//返回的数据不满一页时,则说明已无更多数据
				this.optUp.isLock = true;
				if(dataSize == 0 && pageNum == 1) {
					//如果第一页无任何数据且配置了空布局
					isShowNoMore = false;
					this.showEmpty();
				} else {
					//总列表数少于配置的数量,则不显示无更多数据
					var allDataSize = (pageNum - 1) * pageSize + dataSize;
					if(allDataSize < this.optUp.noMoreSize) {
						isShowNoMore = false;
					} else {
						isShowNoMore = true;
					}
					this.removeEmpty(); //移除空布局
				}
			} else {
				//还有下一页
				isShowNoMore = false;
				this.optUp.isLock = false;
				this.removeEmpty(); //移除空布局
			}
		}

		//设置加载列表数据第一页的时间
		if(pageNum == 1 && systime) this.optUp.page.time = systime;

		//隐藏上拉
		this.endUpScroll(isShowNoMore);

		//检查是否满屏自动加载下一页
		this.loadFull();
	}
}

**Comment by mescroll** [comment]
感谢您的关注,如果你在看看clearDataList()的源码就知道如何处理了
`/*清空上拉加载的数据列表*/
	MeScroll.prototype.clearDataList = function() {
		var listId = this.optUp.clearId || this.optUp.clearEmptyId; //优先使用clearId
		if(listId) {
			var listDom = document.getElementById(listId);
			if(listDom) listDom.innerHTML = "";
		}
	}`
如果不配置clearId或者clearEmptyId或者配置的clearId找不到是不会清空列表的
那么你的可以动态配置clearId即可
mescroll.optUp.clearId=xxxxx

当然如果你用vue的话 就无需考虑这些问题了,vue内部会自动判断是非重绘界面

**Comment by matianqing** [comment]
太棒了
