### ISSUE TITLE
mescroll.endByPage 方法的问题

### ISSUE THREAD

**Issue by MickeyMouse623** [mescroll/mescroll#150]
使用 `endByPage` 方法判定是否是最后一页时
```javascript
  this.mescroll.endByPage(dataLength, totalPage)
```
当 dataLength 为 4， totalPage 为 1 时，最后一页并不触发
![image](https://user-images.githubusercontent.com/18524460/45931048-801c3080-bf9a-11e8-9dac-ce231b20ec70.png)

测试发现， dataLength 为 5 时 就会触发

**Comment by MickeyMouse623** [comment]
阅读案例发现 `noMoreSize` 这个值在起作用

**Comment by mescroll** [comment]
恩恩 对的哦
