### ISSUE TITLE
关于调用方法triggerDownScroll()导致出现多个mescroll-upwarp

### ISSUE THREAD

**Issue by zenglun** [mescroll/mescroll#151]
![qq 20180925203925](https://user-images.githubusercontent.com/35627778/46014806-23885500-c103-11e8-9abc-dd2723cefb77.png)

**Comment by mescroll** [comment]
1. 布局问题:
<div id="mescroll" class="mescroll"> //id可以改,而"mescroll"的class不能删
	   		<div> //这个div不能删, 可以改成ul或者其他容器标签.
		       	 //内容...
	    		</div>
	    	</div>


2.triggerDownScroll 很少调用的,我猜你此处应该调用的是想调用mescroll.resetUpScroll吧

3. 建议参考案例 http://www.mescroll.com/preview.html?name=list-mescroll-one
