### ISSUE TITLE
ios 微信端 打开 页面 空白 需手动下拉刷新才能加载数据

### ISSUE THREAD

**Issue by Lneedy** [mescroll/mescroll#154]
ios 微信端 打开 页面 空白 需手动下拉刷新才能加载数据  页面用了mescroll 的上拉 还有下拉 ,进入页面间歇性空白

**Comment by mescroll** [comment]
1.检查一下是否down或者up的auto设置为true
2.检查一下是否触发down或者up的callback没
3.检查一下是否请求获取到数据没
4.检查一下请求到数据是否正确渲染了列表
5.对照一下案例demo
6.提供重新问题的demo

Thanks♪(･ω･)ﾉ

**Comment by Lneedy** [comment]
ok
我试试

**Comment by Lneedy** [comment]
数据请求到了  但是ios上没有渲染数据
