### ISSUE TITLE
微信打开 ，列表上拉滚动到底部的 没有更多数据 显示后，无法回滚了（下拉）。

### ISSUE THREAD

**Issue by lxfwelldone** [mescroll/mescroll#155]
我是用微信打开的。 带有横向滚动类型菜单的列表的这样一个页面。 初始化后第一个mescroll，一直上拉滚动当所有数据加载完毕后，此时就会卡住，无法回滚了（下拉）。。。请问怎么解决？ 点击菜单其他类型后，返回这个mescroll，依然无法下拉。。。。。我只有第一个类型有数据。。。有点懒，数据比较少

**Comment by lxfwelldone** [comment]
//当前菜单下标
	var curNavIndex=0;
	
	var ts = [];
	[#list couponCats as tag]
		ts.push(${tag.id});
	[/#list]
	
	for(var i=0; i<ts.length; i++){
		var t = ts[i];
		if(catId == t){
			curNavIndex = i;
			break;
		}
	}
	var mescrollArr=new Array(ts.length);//每个菜单对应一个mescroll对象
	
					
	//初始化首页
	mescrollArr[curNavIndex]=initMescroll(curNavIndex);
			
	/*初始化轮播*/
	var swiper = new Swiper('#swiper', {
		onTransitionEnd: function(swiper){
			var i=swiper.activeIndex;//轮播切换完毕的事件
			if(curNavIndex == i){
				return false;
			}
		   	changePage(i);
		}
	});
	
	swiper.slideTo(curNavIndex);
		    
	/*菜单点击事件*/
	$("#nav li").click(function(){
		var i=Number($(this).attr("i"));
		swiper.slideTo(i);
	})
			
	/*切换列表*/
	function changePage(i) {
		if(curNavIndex!=i) {
					//更改列表条件
					var curNavDom;//当前菜单项
					$("#nav li").each(function(n,dom){
						if (dom.getAttribute("i")==i) {
							dom.classList.add("active");
							curNavDom=dom;
						} else{
							dom.classList.remove("active");
						}
					});
					//菜单项居中动画
					var scrollxContent=document.getElementById("scrollxContent");
					var star = scrollxContent.scrollLeft;//当前位置
					var end = curNavDom.offsetLeft + curNavDom.clientWidth/2 - document.body.clientWidth/2; //居中
					mescrollArr[curNavIndex].getStep(star, end, function(step,timer){
						scrollxContent.scrollLeft=step; //从当前位置逐渐移动到中间位置,默认时长300ms
					});
					//隐藏当前回到顶部按钮
					//mescrollArr[curNavIndex].hideTopBtn();
					//取出菜单所对应的mescroll对象,如果未初始化则初始化
					if(mescrollArr[i]==null){
						mescrollArr[i]=initMescroll(i);
					}else{
					}
					//更新标记
					curNavIndex=i;
					catId = ts[i];
				}
	}
			
	/*创建MeScroll对象*/
	function initMescroll(index){
		
		var mescroll = new MeScroll("mescroll"+index, {
			//上拉加载的配置项
			up: {
					callback: upCallbackOfAll, //上拉回调,此处可简写; 相当于 callback: function (page) { getListData(page); }
					page:{
						num:0,
						size:20,
					},
					noMoreSize: 5, 
					clearEmptyId: "dataList"+index,
					htmlNodata:'暂无更多数据',
					empty:{
						warpId:"mescroll"+index,
						icon:"",
						tip:"暂无相关数据~"
					}
				}
		});
		return mescroll;
	}
	
	//上拉加载的回调
    function upCallbackOfAll(page){
    	$.ajax({
        	url: "${setting.siteUrl}/wx/coupon/page.jhtm",
        	data:{pageSize:page.size, pageNum:page.num, catId:catId},
        	type:"POST",
        	dataType:"json",
        	beforeSend:function(){
        		$.showLoading("正在加载...");
        	},
            success: function(curPageData){

				mescrollArr[curNavIndex].endBySize(curPageData.content.length, curPageData.total); //必传参数(当前页的数据个数, 总数据量)
				if(page.num == 1){
					if(curPageData.total < 1){
						return false;
					}
				}
				setDatalist(curPageData.content);
        	},
            error: function(){
              	//联网失败的回调,隐藏下拉刷新和上拉加载的状态
	            mescrollArr[curNavIndex].endErr();
            },
            complete:function(){
           		$.hideLoading();
            }
    	});
    }

**Comment by lxfwelldone** [comment]
<div class="header">
	
	<div class="top-nav" id="topNav">
		<div class="nav-button-left">
			<img src="${setting.siteUrl}/resources/wx/images/back.png" />
		</div>
		<div class="nav-button-right">
			<img src="${setting.siteUrl}/resources/wx/images/coupon.png" />
		</div>
		<div class="nav-title">
			优惠券列表
		</div>
	</div>
	
	<div class="scrollx mescroll-touch-x">
		<div id="scrollxContent" class="scrollx-content">
			<ul id="nav" class="nav">
				[#list couponCats as couponCat]
				<li class="[#if couponCat_index == 0]active[/#if]" i="${couponCat_index}">${couponCat.name!}</li>
				[/#list]
			</ul>
		</div>
	</div>
	
</div>

<div id="swiper" class="swiper-container">
	<div id="swiperWrapper" class="swiper-wrapper" >
	
		[#list couponCats as tag]
			<div id="mescroll${tag_index}" class="swiper-slide mescroll">
			
				<div id="dataList${tag_index}"  class="">

    			</div>

			</div>
		[/#list]
	</div>
</div>

**Comment by lxfwelldone** [comment]
然后我用UC浏览器测试，有时候会卡在最底部，有时候不会。

**Comment by lxfwelldone** [comment]
个人觉得可能是事件冲突了吧，

**Comment by lxfwelldone** [comment]
.swiper-container {
    position: fixed;
    top: 100px;
    left: 0;
    right: 0;
    bottom: 0;
}  一个css文件中忘记加了。。。尴尬。哈哈

**Comment by mescroll** [comment]
O(∩_∩)O哈哈~ 记得看看常见问题哦
http://www.mescroll.com/qa.html?v=0929
