### ISSUE TITLE
vue2.0在mounted直接初始化new MeScroll时设置的warpId是无效的，直接获取的是body

### ISSUE THREAD

**Issue by paomian567** [mescroll/mescroll#156]
vue2.0在mounted直接初始化new MeScroll是设置的warpId是无效的，直接获取的是body。
因为mount的时候，DOM还没有加载，
if(c.optUp.warpId){
    b = c.getDomById(c.optUp.warpId)
}
这句就出错了，获取不到the element with id as "mescroll_content" can not be found: document.getElementById("mescroll_content")==null

希望能够更新解决

**Comment by paomian567** [comment]
this.$nextTick(function(){

/////方法

})来解决

**Comment by mescroll** [comment]
mounted按理说dom已经加载的了 建议贴一下代码 我觉得有可能是传值的问题

**Comment by mescroll** [comment]
mounted生命周期,dom是可以被找到的,,,  当然加上this.$nextTick是最保险的了
