### ISSUE TITLE
经常无法显示加载完成数据后的END, 如果给up做全局配置的话， 那么路由变化的话，page.num 会每次++

### ISSUE THREAD

**Issue by heimaliuchao** [mescroll/mescroll#158]

**Comment by acme-h** [comment]
这组件没人维护了吗？

**Comment by acme-h** [comment]
一堆问题

**Comment by mescroll** [comment]
亲 贴一下代码吧 你的描述表达的不是很清楚~

**Comment by heimaliuchao** [comment]
![_20181018111812](https://user-images.githubusercontent.com/34934352/47129373-94b4c580-d2c7-11e8-9bc4-c242ed4e7de4.png)

**Comment by mescroll** [comment]
问题在于
 `
 if (!datas.status ||datas.returnCode != 200 ||datas.data.length == 0 ) 
return;
`
你在这里return了 所以底下的mescroll.endSuccess没有执行;

改成:
`
 if (!datas.status ||datas.returnCode != 200 ||datas.data.length == 0 ) {
  mescroll.endSuccess(); //隐藏加载状态
  return;
}

            
`

**Comment by mescroll** [comment]
就是在callback中不管什么情况 都要调用mescroll.endSuccess才会隐藏加载中的状态的
