### ISSUE TITLE
up里面的auto设置为false失效，依旧在初始化的时候加载

### ISSUE THREAD

**Issue by Lvna5** [mescroll/mescroll#160]
页面第一页是视图渲染，第二页才是异步请求，可是现在在视图渲染和异步请求同是进行，要求是第二页的时候再实现异步加载

**Comment by mescroll** [comment]
你可以配置down的auto为true, 在down的callback中执行视图渲染;
然后配置up的auto为false, 在up的callback中执行异步请求;

**Comment by Lvna5** [comment]
我写的里面把down去掉了
   var mescroll = new MeScroll("mescroll", {
        up: {
            auto: false, //是否在初始化时以上拉加载的方式自动加载第一页数据; 默认false
            isBounce: false, //此处禁止ios回弹,解析(务必认真阅读,特别是最后一点): http://www.mescroll.com/qa.html#q10
            htmlLoading: '<p class="upwarp-progress mescroll-rotate"></p><p class="upwarp-tip">加载中..</p>',
            htmlNodata: '<p class="upwarp-nodata">-- 没有数据啦 --</p>',
            callback: upCallback({num:2,size:10}), //上拉回调,此处可简写; 相当于 callback: function (page) { upCallback(page); },
            toTop:{ //配置回到顶部按钮
                src : "../res/img/mescroll-totop.png", //默认滚动到1000px显示,可配置offset修改
                //offset : 1000
            }
        }
    });
1.3.5的版本。配置的回到顶部按钮也是失效

**Comment by mescroll** [comment]
callback: upCallback({num:2,size:10})  ?? 这个写法有问题; upCallback多了括号就相当于执行upCallback的方法了

建议参考文档写
callback: upCallback,  没有括号的;

**Comment by Lvna5** [comment]
那个toTop配置现在是无效的，在前台也没发现加载出来样式

**Comment by mescroll** [comment]
检查一下src的路径是否正确,支持网络图的.
回到顶部的按钮是滚动大于1000px的才显示的.

如果还不显示,请查看http://www.mescroll.com/qa.html#q1
