### ISSUE TITLE
关于在uc浏览器和百度浏览器中的问题

### ISSUE THREAD

**Issue by HuangHuanHuan** [mescroll/mescroll#161]
1.在UC浏览器和百度浏览器里，上拉加载的时候会卡顿一会才出现 加载中的状态，qq浏览器和Safari是正常的。
2.这个是每个浏览器都会这样：上拉加载完全部数据后，如果接着上拉列表会没反应，没有滚性滚动，除非先下滑一下列表再上拉才会有惯性滚动， 我看官网里的案例 只有 body为滚动区域的那个例子， 上拉加载完全部数据后， 接着上拉列表还是会有惯性滚动，其他的都不行。
麻烦作者看看这是神马原因

**Comment by mescroll** [comment]
1. 这个是浏览器渲染机制的问题了,下个版本加一个参数避免这个情况.预期月底更新一个版本给您
2.如果配置isBounce为false,是禁止惯性滚动了.不配置isBounce就好. http://www.mescroll.com/qa.html?v=66#q10
