### ISSUE TITLE
在ios 微信浏览器下，设置isBounce: false，还是有回弹效果

### ISSUE THREAD

**Issue by JaminFan** [mescroll/mescroll#162]
如题。
  mescrollDown: {
        callback: this.loadTop,
        isBounce: false, // 是否允许ios的bounce回弹
        auto: false
      },
      mescrollUp: {
        callback: this.loadBottom,
        use: false,
        auto: false,
        isBounce: false // 是否允许ios的bounce回弹
      }
   配置是这样的

版本是1.3.6

**Comment by mescroll** [comment]
/*通过fixed固定mescroll的高度*/
			  .mescroll {
			    position: fixed;
			    top: 44px;
			    bottom: 0;
			    height: auto;
			  }

**Comment by JaminFan** [comment]
.mescroll {
  position: fixed;
  top: 160px;
  bottom: 0;
  height: auto;
  background: #ededed;
}
我也是这样设置mescroll的高度的
