### ISSUE TITLE
作者有实现成react组件的计划么

### ISSUE THREAD

**Issue by acmilank22** [mescroll/mescroll#163]

**Comment by mescroll** [comment]
最近是在写小程序的组件,  最后才考虑angular, react的哦. 个人能力和精力有限哈. 可能需要您等会了.

**Comment by acmilank22** [comment]
> 最近是在写小程序的组件, 最后才考虑angular, react的哦. 个人能力和精力有限哈. 可能需要您等会了.

嗯嗯 没事的 

mescroll很好用 加油哦
