### ISSUE TITLE
使用mescroll组件在项目中无法生效

### ISSUE THREAD

**Issue by dearmingyue** [mescroll/mescroll#166]
import MescrollVue from 'mescroll.js/mescroll.vue'
  export default {
    name: "videoList",
    components: {
      MescrollVue // 注册mescroll组件
    },
    data(){
      return {
        headList:[{classifyName:'全部',id:'all'},{classifyName:'精品',id:'boutique'}],
        num:'all',
        videoAllList:"",   //全部商品
        list:"",
        mescroll:null,
        mescrollUp: { // 上拉加载的配置.
          callback: this.upCallback,
          page: {
            num: 0, //当前页 默认0,回调之前会加1; 即callback(page)会从1开始
            size:5 //每页数据条数,默认10
          }
        }
      }
    },
    created(){
    },
    methods: {

      upCallback: function(page) {  //上拉回调
        let that=this
        this.getAllshop(0,page.num,page.size)
        console.log(page,'我是上拉触发')
      },
      mescrollInit (mescroll) {
        this.mescroll = mescroll
      },

    },
  }

<html>
  <mescroll-vue ref="mescroll"  :up="mescrollUp" @init="mescrollInit">
          <ul class="videoList">
          <router-link :to="{path:'/detailVideo',query:{id:item.id}}" params v-for="item in videoAllList" :key="item.id">
          <li class="video" :id='item.id'>
          <div class="videoImg">
          <img :src="item.simpleSubject.logoPath" alt="">
          </div>
          <div class="title">{{item.simpleSubject.name}}</div>
          <div class="price">
          <div class="money">{{item.price}}</div>
          </div>
          </li>
          </router-link>
          </ul>
        </mescroll-vue>
</html>

**Comment by dearmingyue** [comment]
html
<mescroll-vue ref="mescroll"  :up="mescrollUp" @init="mescrollInit">
        <ul class="videoList">
          <router-link :to="{path:'/detailVideo',query:{id:item.id}}" params v-for="item in videoAllList" :key="item.id">
            <li class="video" :id='item.id'>
              <div class="videoImg">
                <img :src="item.simpleSubject.logoPath" alt="">
              </div>
              <div class="title">{{item.simpleSubject.name}}</div>
              <div class="price">
                <div class="money">{{item.price}}</div>
              </div>
            </li>
          </router-link>
        </ul>
      </mescroll-vue>

**Comment by mescroll** [comment]
亲 你这个代码发的不全, 我感觉是没有设置样式固定mescroll的高度

/*通过fixed固定mescroll的高度*/
			  .mescroll {
			    position: fixed;
			    top: 44px;
			    bottom: 0;
			    height: auto;
			  }

**Comment by dearmingyue** [comment]
这个有写，在vue里面不生效，在普通端可以使用，代码:
<mescroll-vue ref="mescroll"  :up="mescrollUp" @init="mescrollInit">循环内容</mescroll-vue>
从'mescroll.js / mescroll.vue' 
导出MescrollVue 导出默认{ 
name：“videoList”，
组件：{ 
MescrollVue //注册mescroll组件
}，
data（）{ 
return { 
mescroll：null，
mescrollUp：{//上拉加载的配置。
callback：this.upCallback，
page：{ 
num：0，//当前页默认0，回调之前会加1; 即回调（页面）会从1开始
大小：5 //每页数据条数，默认10 
} 
} 
} 
}，
created（）{ 
}，
方法：{
  upCallback: function(page) {  //上拉回调
    let that=this
    this.getAllshop(0,page.num,page.size)
    console.log(page,'我是上拉触发')
  },
  mescrollInit (mescroll) {
    this.mescroll = mescroll
  },
},
style:
 .mescroll {
    position: fixed;
    top: 44px;
    bottom: 0;
    height: auto;
  }

**Comment by moshanghan** [comment]
这个问题比较容易复现
将dmeo中的 极简示例`list-products`，以组件的形式被另一个页面引用
```html
<template>
	<list-products></list-products>
</template>
<script>
	import ListProducts from '../list-products.vue'
	export default {
		components: {
			ListProducts
		},
	}
</script>
```
然后打开这个页面，上拉加载更多就失效了
@mescroll
