### ISSUE TITLE
上拉加载更多的成功或者失败能否有回弹的效果，类似下拉刷新成功之后的回弹

### ISSUE THREAD

**Issue by tuzhiye123** [mescroll/mescroll#17]
场景：
假设现在第一次加载10条数据成功，再次上拉，第二次上拉加载失败，调用mescroll.endErr()，此时listview的底部会有空白（就是class为mescroll-upwarp的div被隐藏造成的），那么此时再次向下拉，是不会触发上拉加载的回调。反而下拉会触发上拉加载的回调（optUp中的offset使用的是默认的100）。会让人造成误解，明明是下拉，反而是触发加载更多回调。
所以能不能让上拉加载成功或者失败，都有回弹效果，或者让listview向上滚动class为mescroll-upwarp的div的高度。
很感谢你分享这个plugin，赞赞赞。

**Comment by mescroll** [comment]
谢谢您的反馈,我想了一下回弹到mescroll-upwarp的div也不行的哦,毕竟高度没有100px; 应该是回弹到offset的高度100px,, 我再想想还有没有其他方案..

**Comment by mescroll** [comment]
您反馈的问题已在1.2.1版本修复,您下载更新即可
