### ISSUE TITLE
vue使用mescroll之后，隐藏布局，滑动其他的控件，控制台报错Uncaught TypeError: j.preventDefault is not a function

### ISSUE THREAD

**Issue by JaminFan** [mescroll/mescroll#170]
实现输入一个搜索匹配功能，在点击了输入框之后会弹出使用mescroll实现的列表，操作完成后隐藏mescroll列表，拖动/滑动其他控件，控制台就报错，
Uncaught TypeError: j.preventDefault is not a function                                 
at a.bounceTouchmove (mescroll.min.js?31d4:12)
a.bounceTouchmove @ mescroll.min.js?31d4:12

**Comment by mescroll** [comment]
配置isBounce为true试试, 下个版本加入这个异常过滤 感谢反馈Thanks♪(･ω･)ﾉ

**Comment by YDJSZY** [comment]
@mescroll 麻烦处理下！现在老是报这个错误，虽然看似没啥影响。谢谢！！

**Comment by JaminFan** [comment]
配置isBounce为true就不报错了，感谢
