### ISSUE TITLE
ios 9.0版本中 setBounce(true)不生效，导致页面无法滚动

### ISSUE THREAD

**Issue by firesnow3676** [mescroll/mescroll#171]
ios 9.0版本中 setBounce(true)不生效，解绑事件无效，导致其他页面无法滚动；

查看原因发现setBounce(true)时，会执行window.removeEventListener("touchmove", this.bounceTouchmove); 

但是**在ios 9当中这个方法并不会生效**，导致滑动事件没有解绑，其他页面无法滚动；

**Comment by mescroll** [comment]
亲 我觉得不是因为removeEventListener的原因, 如果这个方法不生效 那么addEventListener肯定也是不生效的...  建议再对比一下文档和案例,排除一下其他原因哈..  

要不..你不配置bounce试试
或者改为body滚动区域: http://www.mescroll.com/preview.html?name=list-mescroll-body
