### ISSUE TITLE
safari上不显示滚动条

### ISSUE THREAD

**Issue by crescentstar** [mescroll/mescroll#172]
使用的是官网提供的案例，http://www.mescroll.com/preview.html?name=list-mescroll-more。

无论是在PC上的Chrome还是iphone上的Chrome打开，右侧都是有滚动条的；但在iphone上通过safari打开的，没有滚动条。这是为什么啊？

**Comment by mescroll** [comment]
亲 我的iPhone6的safari打开是有滚动条呢 我的ios版本是11.4.1 不知道你的版本是多少

**Comment by mescroll** [comment]
这个... 我觉得应该要打个电话问问蒂姆·库克了

喂.. 蒂姆·库克 先生.. 您好..
您这个ios12的safari咋不显示div的autoflow:auto滚动条呢??
