### ISSUE TITLE
Android UC内核fixed方式固定 mescroll top 使用 rem 单位会导致下拉抖动

### ISSUE THREAD

**Issue by ywz2010** [mescroll/mescroll#176]
Android UC内核使用 fixed 方式固定 mescroll ，如果 `top` 使用`rem` 单位会导致下拉抖动，设置方式如下
```
  .mescroll {
    position: fixed;
    top: 0.91 rem;
    bottom: 0;
    height: auto;
  }
```

**Comment by mescroll** [comment]
意思是 如果使用px就正常 对吗?

**Comment by ywz2010** [comment]
> 意思是 如果使用px就正常 对吗?

是的，px没有问题。使用其他的方式放置mescroll也没问题。

**Comment by ywz2010** [comment]
补充下哈，是在下拉的过程中，下拉刷新文案左边的图标抖动明显。

**Comment by mescroll** [comment]
请问一下 使用其他的方式放置mescroll 是指怎么样操作呢?

**Comment by ywz2010** [comment]
> 请问一下 使用其他的方式放置mescroll 是指怎么样操作呢?

给 mescroll 的父元素设置高度.
文档站中[给 mescroll 的父元素或 mescroll 设置高度的技巧 ](http://www.mescroll.com/qa.html#q2)

**Comment by mescroll** [comment]
亲,这个情况建议使用body为滚动区域了
http://www.mescroll.com/preview.html?name=list-mescroll-body
