### ISSUE TITLE
cdn 更新下，谢谢

### ISSUE THREAD

**Issue by wangzhilongh** [mescroll/mescroll#177]
https://www.jsdelivr.com/package/npm/mescroll
这里的版本太旧了，希望更新一下！
最好以后每次发布新版本，都在cdn同步更新下，非常感谢！

**Comment by mescroll** [comment]
https://www.jsdelivr.com/package/npm/mescroll.js
 亲, 我看了一下是最新的呢

**Comment by wangzhilongh** [comment]
哦哦，抱歉，链接是mescroll.js呀，我找错链接了，多谢多谢！

**Comment by wangzhilongh** [comment]
看了，min文件里面注释的内容是不是可以精简下，毕竟发布生产用的，体积越小越好呢！
其他许多开源项目的min文件，仅仅是标注下版本号等最基本信息，其他的都没有呢。
例如vue如下：
/*!
 * Vue.js v2.5.17
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */
对比咱们的：
/*! mescroll -- 精致的下拉刷新和上拉加载js框架  ( a great JS framework for pull-refresh and pull-up-loading )
 * version 1.3.8
 * 2018-09-29
 * author: wenju < mescroll@qq.com > 文举
 * *
 * 官网:  http://www.mescroll.com
 * 动态:  https://github.com/mescroll/mescroll/releases
 * 问答:  http://www.mescroll.com/qa.html
 * issues:  https://github.com/mescroll/mescroll/issues
 * QQ交流群: 633126761
 *
 * 温馨提示: mescroll唯一的全局样式: html,body{height:100%},用于固定body的高度满屏; 如果影响到您原本的项目样式,可自行删除
 *
 *
 * ----- mescroll的html结构解析 ----
 *
 <body>
   <div id="mescroll" class="mescroll">
    <div>

      //下拉刷新区域 ( mescroll初始化之后自动创建 )
      <div class="mescroll-downwarp">
        <div class="downwarp-content">
          <p class="downwarp-progress"></p> <p class="downwarp-tip">下拉刷新 </p>
        </div>
      </div>

      //界面的具体内容
      //<div>界面内容</div>
      //数据列表..
      //<ul id="dataList" class="data-list">
      //	<li>数据列表</li>

        //空布局 ( 列表无任何数据时, 且配置了warpId时, 会自动创建显示 )
        <div class="mescroll-empty">
          <img class="empty-icon" src="../img/mescroll-empty.png"/>
          <p class="empty-tip">暂无相关数据~</p>
           <p class="empty-btn">去逛逛 ></p>
        </div>

      //</ul>

      //上拉加载区域 ( mescroll初始化之后自动创建 )
      <div class="mescroll-upwarp">
        //加载中..
        <p class="upwarp-progress mescroll-rotate"></p><p class="upwarp-tip">加载中..</p>
        //无数据
        <p class="upwarp-nodata">-- END --</p>
      </div>

    </div>
	</div>

	//回到顶部按钮 ( 列表滚动到配置的距离时, 且配置了warpId时, 会自动创建显示, 注意是添加在body中的 )
	<img class="mescroll-totop" src="../img/mescroll-totop.png"/>
</body>
*/

/*! mescroll -- 精致的下拉刷新和上拉加载js框架  ( a great JS framework for pull-refresh and pull-up-loading )
 * version 1.3.8
 * 2018-09-29
 * author: wenju < mescroll@qq.com > 文举
 * *
 * 官网:  http://www.mescroll.com
 * 动态:  https://github.com/mescroll/mescroll/releases
 * 问答:  http://www.mescroll.com/qa.html
 * issues:  https://github.com/mescroll/mescroll/issues
 * QQ交流群: 633126761
 */
注释内容不仅多，还有大量的汉字。。。
可以简化下吗？
例如参考vue，注释个版本号，作者（官网）即可呢，其他在min文件中无关的注释尽量删简下，多谢多谢！

**Comment by mescroll** [comment]
好的 ~ 可以的~ 感谢支持~  我周末整理更新一个版本 顺便把这个注释删掉~

**Comment by wangzhilongh** [comment]
好的，非常感谢！

**Comment by mescroll** [comment]
亲 已经更新了哈
https://cdn.jsdelivr.net/npm/mescroll.js@1.4.0/mescroll.min.css
https://cdn.jsdelivr.net/npm/mescroll.js@1.4.0/mescroll.min.js

**Comment by wangzhilongh** [comment]
棒棒哒！谢谢！~
