### ISSUE TITLE
其他滚动的元素不能滚动

### ISSUE THREAD

**Issue by w493189140** [mescroll/mescroll#185]
导航可以滚动
![image](https://user-images.githubusercontent.com/22770789/49275664-f36c8200-f4b6-11e8-8c5c-3923b325e0c8.png)
怎么解决
导航滚动被mescroll阻止了

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/49275774-5827dc80-f4b7-11e8-9578-8f9bf4d39b56.png)

**Comment by mescroll** [comment]
http://www.mescroll.com/qa.html?v=66#q10
