### ISSUE TITLE
函数节流以及未滑动至底部不触发上拉加载事件

### ISSUE THREAD

**Issue by aNewLearnerHere** [mescroll/mescroll#186]
有属性可以配置不在未滚动到底部的时候触发上拉加载事件吗？
上拉加载一次可能触发多个请求，是否考虑增加函数节流？

**Comment by mescroll** [comment]
可配置up的offset

上拉加载不会触发多次请求的..除非你请求的时候马上又结束了上拉加载,比如马上调用mescroll.endSuccess;  如果请求回来的比较快,可以适当的延时或者列表数据加载完成之后再结束上拉加载,
