### ISSUE TITLE
vue中数据列表为空时mescroll-empty和empty-tip的样式无法覆盖重写

### ISSUE THREAD

**Issue by ltsxs** [mescroll/mescroll#189]
vue中数据列表为空时mescroll-empty和empty-tip的样式无法覆盖重写，我想调整一下列表为空时提示的字体样式

**Comment by mescroll** [comment]
你试试  
>>> .mescroll-empty .empty-tip {
	margin-top: 6px;
	font-size: 14px;
	color: red
}

**Comment by mescroll** [comment]
要加上 >>>
