### ISSUE TITLE
安卓手机下拉刷新时，整个页面都在抖动，但是Ios没有问题，麻烦大大帮忙看看

### ISSUE THREAD

**Issue by xiaocaihong** [mescroll/mescroll#196]
官网中的案例有这个例子：
安卓手机扫码观看：
![image](https://user-images.githubusercontent.com/18278450/50072551-90961d00-0210-11e9-9993-6b3d4aaf82fb.png)

复现场景：
手指慢慢向下拉，会看见
![image](https://user-images.githubusercontent.com/18278450/50072573-a3105680-0210-11e9-999a-fd6f602a46ba.png)这个地方有很明显的抖动

**Comment by mescroll** [comment]
亲 您测试的手机型号能方便告知一下不

**Comment by xiaocaihong** [comment]
oppo r9s

**Comment by mescroll** [comment]
亲 经测试 这里并无异常哦 您截图的那个只是一个普通的占位图哈 ~
