### ISSUE TITLE
官网有图片显示不出来

### ISSUE THREAD

**Issue by chenhuiYj** [mescroll/mescroll#197]
你好，这个可能不算 issues 。只是想提醒，官网的图片挂了一张

![qq 20181218102522](https://user-images.githubusercontent.com/27403818/50128277-592a7d80-02af-11e9-8ad7-1d4503c4f16a.jpg)

**Comment by mescroll** [comment]
O(∩_∩)O哈哈~  感谢反馈... 以前七牛服务器没充值 忘记换过来了
