### ISSUE TITLE
设置isBounce为false会导致视频进度条无法拖动

### ISSUE THREAD

**Issue by michaeljfei** [mescroll/mescroll#198]
![image](https://user-images.githubusercontent.com/18050049/50144574-89434200-02ea-11e9-8e44-9e3d651f8a70.png)

![image](https://user-images.githubusercontent.com/18050049/50144398-1b971600-02ea-11e9-87c3-396276962045.png)

如图所示，设置了isBounce会导致全局的touchmove事件异常，从而导致滚动区域之外的视频播放器的进度条无法拖动。
此问题仅仅出现在ios上。

**Comment by mescroll** [comment]
http://www.mescroll.com/qa.html?v=68#q10
