### ISSUE TITLE
节流阀建议

### ISSUE THREAD

**Issue by cddsgtc** [mescroll/mescroll#199]
不知道项目里是否用到节流阀，如果没有建议用上，因为在安卓上，如果页面的内容很多现在会感觉到卡顿，如果是只是文档里说的那个情况而非节流阀的问题，请忽略。

**Comment by mescroll** [comment]
其实mescroll的滚动过程中并没有执行特别耗时的代码呢.. 
如果是懒加载,有节流的配置,可配置lazyLoad的delay值... 

亲 卡顿的原因有很多的哦 ... 
1. 图片比较大, 建议配置对应大小的图片哦
2. dom结构比较复杂或嵌套比较多
3. android本身性能的问题了

不知道你页面的内容是不是有很多图片呢   如果是的话 能麻烦您把图片暂时注释一下,看看是不是能够缓解...   如果能缓解的话就可以确认是图片引起的,就要考虑一下图片的优化了
有线上的项目地址吗? 方便发一下我去体验看看~
