### ISSUE TITLE
上拉之后页面不能滚动

### ISSUE THREAD

**Issue by cnym** [mescroll/mescroll#2]
必现：移动端和PC端，上拉->松手->继续滑动页面时页面卡住不可滑动，不操作大约几百毫秒后页面才恢复。

**Comment by web-tiny** [comment]
你们在用的时候有没有遇到这种情况：在Android微信端的时候上拉加载更多没有任何反应，下拉刷新的时候没问题，在IOS的微信端上拉加载和下拉刷新都没问题的

**Comment by mescroll** [comment]
@web-tiny  您应该是QQ上联系我的 对吧 已经帮您解决 原因是您设置了一个全局的样式 *{touch-action: none} 导致的哈~  另外O(∩_∩)O谢谢你的大红包 哈哈

**Comment by mescroll** [comment]
@cnym 未发现您说的问题哦 我在android ios 手机微信 QQ PC浏览器都测试了一下 未发现您说的卡顿问题哈 ; 您如果有重现的案例可以发到我邮箱 mescroll@qq.com

**Comment by danlanxiaohei** [comment]
@mescroll 遇到同样问题，复现步骤：在iphone6的safari浏览器上

**Comment by ZhengMengSi** [comment]
我也遇到这个问题，你解决了吗？是什么原因导致的？

**Comment by ZhengMengSi** [comment]
@danlanxiaohei 我也遇到这个问题，你解决了吗？是什么原因导致的？
