### ISSUE TITLE
请问如何触发点击事件？

### ISSUE THREAD

**Issue by pinorr** [mescroll/mescroll#20]
mescroll上拉加载回来的数据，比如创建成了如下结构：
<li data-url='....'>
.....
</li>

然后用这样的方式绑定点击是无效的：$("li[data-url]").on("click",function(){...});
请问应该如何绑定点击事件呢？谢谢

**Comment by mescroll** [comment]
亲 这个不是mescroll的问题了.. 动态创建的demo不是这样监听事件的呢
你可以 $("#ul的id").on("click","li",function(){xxxx})

**Comment by pinorr** [comment]
多谢
