### ISSUE TITLE
passive:false 之后IOS下safari和chrome都不能滚动

### ISSUE THREAD

**Issue by dmfeng** [mescroll/mescroll#200]
1.3.5之后的版本加上了 {passive: false} 在我的页面里都不能正常滚动
c.scrollDom.addEventListener('mousemove', c.touchmoveEvent, {passive: false})

手动删除这个后就正常了

**Comment by mescroll** [comment]
(⊙o⊙)…  不是吧...  有线上的地址不  我想去看看一下代码结构 ?

**Comment by Benbzhou** [comment]
我也是 不能滚动 ios9 的版本11能正常

**Comment by Benbzhou** [comment]
我的 跳转页面后导致其他页面不能滚动了  在ios就出现的情况

**Comment by Benbzhou** [comment]
按照官网配置是ios9  ios11 12 都没问题

**Comment by Benbzhou** [comment]
我的 跳转页面后导致其他页面不能滚动了 在ios9就出现的情况
