### ISSUE TITLE
可否用css3的transform去实现下拉刷新呢，

### ISSUE THREAD

**Issue by LiuduZero** [mescroll/mescroll#201]
可开启 GPU 加速，体验更好

**Comment by LiuduZero** [comment]
可否将初始位置translateY设置成，downwrap的高度，这样他就会不显示，下拉的时候，就会出现，而不是Y(0)，这样可否可以呢
发自我的 iPhone

**Comment by mescroll** [comment]
uni-app版本的mescroll, 小程序性能要求比较高,已经使用了transform;  但是js版本的mescroll还是决定不采用此方案,一方面现在手机的性能在H5端已经经得起性能消耗,最主要的方面transform会使fixed元素失效,无法兼容以前版本,且写法上并得很麻烦,得把所有fixed元素都写在外面,很难用了
