### ISSUE TITLE
在浏览器一直上拉，再往下拉拉不动，必须先再往上拉一下手指不松开再下拉才可以

### ISSUE THREAD

**Issue by zoulinaini** [mescroll/mescroll#202]
如题

**Comment by WeiYuanlin** [comment]
我也遇到了这个问题，使用手机调试的。

**Comment by mescroll** [comment]
浏览器确实是没有监听鼠标滚轮事件, 下个版本加入鼠标滚轮,监听到底部时检查触发上拉加载..

手机端是不会存在此问题..

**Comment by xiaodaodizhen** [comment]
现在这个版本 支持鼠标滚轮事件了吗，

**Comment by mescroll** [comment]
> 现在这个版本 支持鼠标滚轮事件了吗，

需要再等会哦 打算这周六更新一下哈 到时通知您

**Comment by yeahsgz** [comment]
同遇到

**Comment by yeahsgz** [comment]
**version:1.4**

结合着源码看了下这个问题： 首先我的页面结构如下

<img width="286" alt="20190308111331" src="https://user-images.githubusercontent.com/18343561/54005329-f51fa300-4193-11e9-9879-84af2f3a7436.png">


body高度为设备高度677px，.content高度为实际高度，约为1200px;

当滑动到底部停止时，因为这段代码而禁止滑动

```
// 如果手指的位置超过配置的距离,则提前结束下拉,避免Webview嵌套导致touchend无法触发
if (me.maxTouchmoveY > 0 && curPoint.y >= me.maxTouchmoveY) {
  me.inTouchend = true; // 标记执行touchend
  me.touchendEvent(); // 提前触发touchend
  return;
}
```
然后改造：使.content与body高度相同，.content内部scroll。

but，这时候又遇见了新问题：

当页面滑动到底部的时候，再下拉时，触发了mescroll的回弹，导致不能滑动到顶部！

```
// 向下拉
  if (moveY > 0) {
    // 在顶部
    if (scrollTop <= 0) {
      me.preventDefault(e); // 阻止浏览器默认的滚动,避免触发bounce
```
因为这段代码，阻止了浏览器的默认事件。

好了，这时候我的做法就是打一个小补丁，增加一个参数配置解放浏览器的默认滚动，同时禁用下拉刷新功能

**Comment by mescroll** [comment]
感谢您的建议 想想哈 Thanks♪(･ω･)ﾉ
在此之前 您要不试试body为滚动区域的案例 
http://www.mescroll.com/preview.html?name=list-mescroll-body

**Comment by yeahsgz** [comment]
> 感谢您的建议 想想哈 Thanks♪(･ω･)ﾉ
> 在此之前 您要不试试body为滚动区域的案例
> http://www.mescroll.com/preview.html?name=list-mescroll-body

谢谢哒，不过我的页面有多个列表😂。这个尝试过，有其他问题。

**Comment by LIHAO520** [comment]
你好，这个mescroll  样式里给了绝对定位  这样上拉下拉都没有问题  但是改成相对定位后就下拉之后网上滑就滑不动  要再上拉一下才能滑，这个跟定位有关系吗？但是又不能绝对定位使用，因为中间的元素都是动态变换的，望解答

**Comment by calm420** [comment]
同遇

**Comment by weiya89** [comment]
同遇，有解决方案吗

**Comment by mescroll** [comment]
定位是为了固定mescroll的div的高度哦, 原理可以参考 http://www.mescroll.com/qa.html?v=0329#q1

如果中间的位置是动态变化的, 建议还是js动态计算 去固定mescroll这个div的高度哦

**Comment by mescroll** [comment]
@yeahsgz 之前没有注意到 你的div结构; 
如果是 .content内部scroll的话 你应该是给content这个div设置了overflow:auto
导致mescroll这个div的overflow:auto失效了,无法触发mescroll这个div的滚动事件,才会出现你反馈的这些问题.

其中最好的解决方案就是把content这个div 直接改成mescroll就好啦

**Comment by HUAMINO** [comment]
为什么我的往下滑动之后在网上上滑动就会触发下拉
