### ISSUE TITLE
使用 mescroll组件后出现警告 $attrs is readonly. $listeners is readonly

### ISSUE THREAD

**Issue by Curtain-A** [mescroll/mescroll#206]
引入mescroll组件 :   import MescrollVue from 'mescroll.js/mescroll.vue'
出现警告 $attrs is readonly. $listeners is readonly

**Comment by mescroll** [comment]
估计是你使用了组件的嵌套
建议您检查一下是不是A组件调B组件，B组件调C组件。然后A组件直接去修改C组件的数据。这个是不正确的...
