### ISSUE TITLE
ios 输入框问题，其他页面没引入vue组件不会出现此问题

### ISSUE THREAD

**Issue by jc91715** [mescroll/mescroll#208]
在容器外打开输入框，当隐藏起键盘后，输入框不能点击，滑动一下页面才可以点击，有个灰色的层罩住了，看着像是隐藏后的键盘，其他页面的输入框没有此问题。
![image](https://user-images.githubusercontent.com/24908449/51237223-f52ece00-19ae-11e9-93ab-25dcdb3cb552.png)

**Comment by mescroll** [comment]
亲 这个是iOS的input如果使用fixed定位会导致焦点错位的问题... 建议上网找找相关解决方法哦 
可以在input获取焦点时改为absolute定位试试~
