### ISSUE TITLE
下拉刷新背景在小米手机上显示不正常

### ISSUE THREAD

**Issue by q310550690** [mescroll/mescroll#21]
在小米上下拉刷新的时候背景不会更新，必须手离开屏幕后才会恢复正常

如图
![](http://ww1.sinaimg.cn/large/6dac2142gy1fj40xo4cigj20k00zkwff.jpg)

正常应该是这样的
![](http://ww1.sinaimg.cn/large/6dac2142gy1fj40y9n3zzj20k00zkjs7.jpg)

**Comment by q310550690** [comment]
找到问题所在

把.mescroll-hardware class去了就正常了

可是这样就无法启用硬件加速

有什么好的办法嘛？

**Comment by mescroll** [comment]
硬件加速在android不是万能药膏哦 有些机型还会适得其反 过几天会更新一个版本规避你说的问题 到时通知你 欢迎各位持续关注star

**Comment by q310550690** [comment]
@mescroll 好的

**Comment by q310550690** [comment]
@mescroll 
.mescroll{
    -webkit-transform-style: preserve-3d;
    -webkit-backface-visibility: hidden;
}
加入这个属性就解决问题了

**Comment by mescroll** [comment]
感谢提醒,还需再补上-webkit-perspective: 1000; 这个属性就完美了;
已经更新到1.2.1,修复此问题

**Comment by ifuweimin** [comment]
测试新版本在小米 360上背景仍存在， 对比了下代码， 新版本在.mescroll-hardware上加的 无效， 在.mescroll上加就可以了
