### ISSUE TITLE
不知道用mescroll能否做到淘宝首页的效果？

### ISSUE THREAD

**Issue by alicksnake22** [mescroll/mescroll#210]
在目前手淘app上面有个功能，就是滑动向上的时候，滑到一定距离，会有一个分类导航栏贴顶，然后下面的swiper可以左右滑动，左右滑动的每个scroll又可以单独上下滑动，然后滑动到顶部的时候分类导航栏自动离顶，如下图
![image](https://user-images.githubusercontent.com/14839142/51460193-bd9c9900-1d95-11e9-8c92-866014ee6992.png)
![image](https://user-images.githubusercontent.com/14839142/51460226-d442f000-1d95-11e9-8886-c9596d4434b3.png)

**Comment by mescroll** [comment]
其实就是这个案例哦 把列表改成swiper展示即可
http://www.mescroll.com/preview.html?name=sticky
