### ISSUE TITLE
请问如何实现下拉加载？

### ISSUE THREAD

**Issue by Yriuns** [mescroll/mescroll#211]
想实现类似微信聊天界面的下拉加载，但是没找到配置方案，似乎不支持？

**Comment by mescroll** [comment]
http://www.mescroll.com/preview.html?name=list-news
其实就是下拉刷新,把数据添加到顶部..

**Comment by Yriuns** [comment]
不太一样，微信的下拉加载后，数据添加到顶部，但显示的区域还是下拉前的部分。所以需要一个手动的`scrollTo(y, 0)`。y的数值由加载前后元素的scrollHeight的差值来计算
