### ISSUE TITLE
lazyLoad 有这里是错误的判断

### ISSUE THREAD

**Issue by ycg520520** [mescroll/mescroll#218]
`MeScroll.prototype.lazyLoad = function (delay) {
    var me = this;
    var t = delay != null ? delay : me.optUp.lazyLoad.delay; // delay需支持传0,不使用短路求值
`
delay != null  这里的判断逻辑有错误，调用lazyLoad()不传参数时，delay的值为undefined 所以t有可能是undefined

**Comment by mescroll** [comment]
var t = delay != null ? delay : me.optUp.lazyLoad.delay;

亲 我这里特意用的
是  !=  
不是 !==

所以如果delay不传的话 会取me.optUp.lazyLoad.delay的值呢

而且即使t为undefined, 并不影响setTimeout的运行哦
