### ISSUE TITLE
建议重构下代码

### ISSUE THREAD

**Issue by dailc** [mescroll/mescroll#22]
首先感谢作者的奉献，我另一个项目也是参考的这个的灵感的。

然后就是觉得这个项目目前的代码有点乱，代码风格没有统一，注释什么的也比较乱，另外代码结构上也不是很分离，建议可以模块化重构下，可以考虑使用以下方法

- 譬如JSDoc风格的代码注释（最长用的一种）

- 代码分成多个文件，使用gulp（或grunt）等工具自动构建

- ...(等等)

当然了，以上仅是个人建议，觉得这样一来能让作者的水准更上一个台阶，二来能让使用这个项目的人
看到更规范的代码，学到更多的东西。

最后，开源项目不容易，赞一个！

**Comment by mescroll** [comment]
感谢您的建议~ 如果能把第三点(等等) 写出来就好了 哈哈 再次感谢 我好好规划一下
