### ISSUE TITLE
下拉刷新时, page.num 不是重置为0, 而是减一?

### ISSUE THREAD

**Issue by LX314** [mescroll/mescroll#221]

**Comment by LX314** [comment]
还是说需要额外操作?

**Comment by mescroll** [comment]
文档里面有这么一句话哦: 
// down.callback默认调用mescroll.resetUpScroll(),而resetUpScroll会将page.num=1,再触发up.callback

**Comment by mescroll** [comment]
所以你想在down的callback里, 写上mescroll.resetUpScroll()即可将page.num=1
