### ISSUE TITLE
开发者你好，最近遇到一个多mescorll（仅初始化一次，依靠缓存）返回最初列表的初始化默认菜单的问题。

### ISSUE THREAD

**Issue by cowboy1997** [mescroll/mescroll#222]
真的很感谢提供的[多mescroll源码](https://github.com/mescroll/mescroll/blob/master/demo/base/list-mescroll-more.html)，基本拿过来就能用，哈哈哈；当点击菜单进入第二层页面的时候，需要返回上一层页面，这时候要初始化显示菜单，按照源码的方法一直默认初始化第一个菜单，之后稍微研究了一下，做了一下改动，但是我的代码看起来很笨拙，不知道开发者那边有没有更好的方法实现。
这边先从二级页面得到返回的curNavIndex，也就是当前菜单的索引值
`var curNavIndex = pdType>0?pdType:0;`
然后初始化索引值对应的菜单
`
$(function () {
	
	//初始化页面
	mescrollArr[curNavIndex] = initMescroll("mescroll" + curNavIndex, "dataList" + curNavIndex);
	if (curNavIndex > 0) {
		var i = Number($(".nav p").attr("i"));
		//更改列表条件
		$(".nav .active").removeClass("active");
		$("p[i=" + curNavIndex + "]").addClass("active");
		//隐藏当前列表
		$("#mescroll" + curNavIndex).hide();
		//显示对应的列表
		$("#mescroll" + curNavIndex).show();
	}

	/*初始化菜单点击事件*/
	$(".nav p").click(function () {
		var i = Number($(this).attr("i"));
		if (curNavIndex != i) {
			//更改列表条件
			$(".nav .active").removeClass("active");
			$(this).addClass("active");
			//隐藏当前列表
			$("#mescroll" + curNavIndex).hide();
			//显示对应的列表
			curNavIndex = i;
			$("#mescroll" + curNavIndex).show();
			//取出菜单所对应的mescroll对象,如果未初始化则初始化
			if (mescrollArr[i] == null) mescrollArr[i] = initMescroll("mescroll" + i, "dataList" + i);
			//更新标记
			curNavIndex = i;
		}
	})
});
`

**Comment by mescroll** [comment]
亲 您的思路是正确哦 缓存当前页的菜单下标 回来的时候从缓存中取 ;
缓存中没有下标就默认第一个了
您贴的代码挺好
