### ISSUE TITLE
微信网页上拉到底部后下拉卡顿

### ISSUE THREAD

**Issue by Xiaoshizaizi** [mescroll/mescroll#225]
你好，请教一下：
1.微信网页上拉到底部后下拉会卡顿，而且卡顿一下之后直接执行下拉刷新，回到最顶部。
2.在上拉加载过程中，有时也会卡住，需要松开界面稍等片刻，就又恢复正常。
找了一天没找到原因，麻烦帮看下，
谢谢。
*******************************************************************
在微信中打开下面这个网页
http://xiaoyuanfeixia.com/public/html/app/sence/article_old.html
可以复现该问题。
********************************************************************
这是此页面的代码：
https://github.com/Xiaoshizaizi/wx-privite/blob/master/html/app/sence/article_old.html

**Comment by gouwa626** [comment]
![image](https://user-images.githubusercontent.com/33645162/56363135-14dbc980-621e-11e9-9aff-2575286e6fa9.png)
试试这个

**Comment by Xiaoshizaizi** [comment]
> ![image](https://user-images.githubusercontent.com/33645162/56363135-14dbc980-621e-11e9-9aff-2575286e6fa9.png)
> 试试这个

试过，不行的

**Comment by gouwa626** [comment]
> > ![image](https://user-images.githubusercontent.com/33645162/56363135-14dbc980-621e-11e9-9aff-2575286e6fa9.png)
> > 试试这个
> 
> 试过，不行的

那就不晓得了  我之前也是拉到底部卡顿  用这个可以了

**Comment by mescroll** [comment]
原因是你mescroll这个样式写错位置了,请按照下图改好
![微信截图_20190420171531](https://user-images.githubusercontent.com/29813435/56455386-3066e180-6390-11e9-9a15-0e1c155a6b1d.png)

mescroll这个样式写的位置: 请参考https://github.com/mescroll/mescroll/blob/master/demo/swiper/mescroll-swiper-nav.html
