### ISSUE TITLE
在移动端使用的时候，如果锁定了下拉刷新，那么列表都没办法回到最上面去了

### ISSUE THREAD

**Issue by calm420** [mescroll/mescroll#227]

**Comment by calm420** [comment]
只有在先向下划，，并且不松手的情况下，才能继续向上华东，如果此时我已经到了底部，根本没办法在滑上去

**Comment by mescroll** [comment]
请提供一下重现的demo哦 ... 我觉得应该是mescroll的这个div没有固定高度.. 建议您看一下常见问题1和2
