### ISSUE TITLE
请问在mescroll组件中，可以手动重新触发init的回调吗

### ISSUE THREAD

**Issue by haylingzhang** [mescroll/mescroll#229]
目前只有destroy方法，文档中没用明确的可以重新触发init的办法

**Comment by mescroll** [comment]
确实没有重新触发init的方法..本身设计的init就是只执行一次的哈~
如果您需要重置页面为第一页,可以调用 mescroll.resetUpScroll()
http://www.mescroll.com/api.html?v=0329#methods

如果您需要重新创建mescroll,只能destroy,再new了
