### ISSUE TITLE
安卓QQ浏览器往上滑后下拉 卡住

### ISSUE THREAD

**Issue by njyangxiao** [mescroll/mescroll#230]
在安卓QQ浏览器中 刚进页面 上滑一点 然后下拉 就会卡住 然后用手轻轻滑动又就好了 这怎么解决
![TIM图片20190410095916](https://user-images.githubusercontent.com/48577245/55846252-8d37f000-5b77-11e9-81c1-62e88fe8f885.jpg)

**Comment by mescroll** [comment]
试试配置 up的isBounce为false

**Comment by mescroll** [comment]
http://www.mescroll.com/qa.html?v=66#q10
