### ISSUE TITLE
能否支持下uni-app开发？

### ISSUE THREAD

**Issue by YY007H** [mescroll/mescroll#231]
使用这个框架在uni开发中，网页上能正常使用，但是打包进app就用不了，作者能否自定义下主键支持一下呢，万分感激！

**Comment by mescroll** [comment]
uni-app不支持window,document等,所以mescroll在uni-app暂时还不支持;
当然目前我也在用uni-app开发, 对uni-app的支持还需要一阵子哦.. 最快也是五一之后了哈
五一我加加班改进一下~
感谢支持~

**Comment by mescroll** [comment]
昨晚加班了一下 最快这两天做出来一个版本哈 敬请期待~

**Comment by YY007H** [comment]
大佬厉害，牛~

**Comment by mescroll** [comment]
我计划25号发正式版本 您可以先体验 文档我刚整理好 http://www.mescroll.com/uni.html 有问题欢迎反馈

**Comment by mescroll** [comment]
HBuilderX的usingComponents编译和不使用usingComponents编译差别那么大 ...
感觉 快疯掉了 O(∩_∩)O哈哈~
五一前估计都弄不完了 要考虑的情况太多~
(。・＿・。)ﾉ I’m sorry~

**Comment by YY007H** [comment]
大佬，不着急，我先用官方自带的扛一段时间😂😂😂

**Comment by mescroll** [comment]
我感觉承诺出去的还是要按时兑现 哈哈
解决了各种奇形怪状的问题,终于可以正式发布 mescroll-uni 1.0.0   啦
撒花 撒花 ✿✿ヽ(°▽°)ノ✿

http://ext.dcloud.net.cn/plugin?id=343

文档: http://www.mescroll.com/uni.html

还好没有放弃 O(∩_∩)O哈哈~

**Comment by YY007H** [comment]
大佬真牛O(∩_∩)O

**Comment by plaleosworld** [comment]
非常感谢您  您不仅技术🐂  而且态度也很认真
