### ISSUE TITLE
请问有设置可以尽在页面顶部时触发下拉刷新的配置吗

### ISSUE THREAD

**Issue by LX314** [mescroll/mescroll#233]

**Comment by LX314** [comment]
需求是在 mescroll内部又嵌套了一个容器, 在页面中部下拉时很容易触发下拉刷新的操作, 是否可以配置为尽在页面顶部(底部)时才可以触发下拉刷新(上提加载)操作?

**Comment by mescroll** [comment]
1. 请确保mescroll这个div是有高度的, 推荐使用定位的方式 http://www.mescroll.com/qa.html?v=0329#q2
2. 建议您试试 mustToTop 这个参数设置为 true  : http://www.mescroll.com/api.html?v=0329#options
