### ISSUE TITLE
下拉刷新的问题.

### ISSUE THREAD

**Issue by HelloYeah** [mescroll/mescroll#234]
下拉刷新,用了 height: auto,属性后,
可以看到mescroll容器高度会有计算过程,由0->实际值的一个变化.
这个时候,会触发数据加载,导致页面闪动.且能看到页面上数据的变化

**Comment by mescroll** [comment]
亲,不是很明白您说描述的问题:
首先确定的是下拉过程中mescroll-downwarp这个div高度是实时变化的,这个并不是bug
如果mescroll的高度设置了height:auto,那么请必须给mescroll这个div固定高度, 推荐使用定位的方式固定
建议您参考常见问题1和2 
http://www.mescroll.com/qa.html?v=0329#q1

**Comment by mescroll** [comment]
为什么position: fixed的元素写到mescroll的div里面会抖动?
http://www.mescroll.com/qa.html?v=0329#q6

**Comment by HelloYeah** [comment]
是我自己配置的问题.  配置 auto:false, 就好了
