### ISSUE TITLE
上拉加载触发不了的问题 (按照问答给的方法仍解决不了的可能方法)

### ISSUE THREAD

**Issue by Skura23** [mescroll/mescroll#236]
讲一下用mescroll遇到的一个坑, 就是上拉加载死活触发不了, 折腾了一下午才找到原因,
开始我以为是css样式设置的问题, 于是按作者在[问答](http://www.mescroll.com/qa.html?v=0329#q1)提供的思路来回试了好多遍, 都不行.
而下拉刷新却可以正常运行, 但所有数据加载完后, 却不显示`无更多数据`提示
于是我想先把提示问题解决掉, 然后在这儿issue下找到答案, #135 
即由于**noMoreSize属性默认值为5**, 当总数据值少于5并加载完时, 是不会显示 `无更多数据`提示的,
把noMoreSize属性设置为0, 则无论加载完的总数据多少条, 都会显示这条信息.
把noMoreSize属性设置为0后, 然后我们再回头看上拉加载无法触发的问题, 
这时页面加载后会看到列表底部出现 `无更多数据` 提示, 
提示虽然出现了, 但奇怪的是, 我用的mock数据,
机制是每次请求传一条数据, 为什么第一次请求成功后就显示 `无更多数据`. 
于是回去翻看文档, [文档](http://www.mescroll.com/api.html?v=0329)页找到这段话:

> //结束上拉加载 curPageData.length必传的原因:
> 1.使配置的noMoreSize 和 empty生效
> 2.判断是否有下一页的首要依据: 当传的值小于page.size时,则一定会认为无更多数据.
>  比传入的totalPage, totalSize, hasNext具有更高的判断优先级
> 3.当传的值等于page.size时,才会取totalPage, totalSize, hasNext判断是否有下一页
> 传totalPage, totalSize, hasNext主要目的是避免方法四描述的小问题

这是插件判断是否有更多数据的机制, 尤其是首要依据'**当传的值小于page.size时,则一定会认为无更多数据**', 而因为我mock的数据每次请求一条, 就是说curPageData.length为1, **但插件的默认page.size为10**, 根据首要判断依据, 第一次请求后就被插件判断为无更多数据了, 于是将配置项里的page.size设置为ajax每次请求的列表项返回数, 就可解决了. 我这里把size改为1就行了.

以上是我用这个插件的爬坑之旅, 如果你在按照[问答](http://www.mescroll.com/qa.html?v=0329#q1)给的方法仍无法解决上拉无法加载的问题, 可以注意下**noMoreSize**与**page.size**选项的配置, 按照上面的方法试着解决一下.
@mescroll 建议把**noMoreSize**与**page.size**的默认值问题导致上拉加载无法触发更新到`Q. 为什么我写的上拉触发不了 或者 列表无法滑动 ?`问题的解答下, 或许能帮助一些人避免再踩坑.

**Comment by mescroll** [comment]
先对您say sorry 哈, 让您走了弯路~
确实我疏忽了这个情况
感谢反馈和建议哈

**Comment by Skura23** [comment]
> 先对您say sorry 哈, 让您走了弯路~
> 确实我疏忽了这个情况
> 感谢反馈和建议哈

用别人的轮子, 踩坑是难免的嘛, 得感谢你写出这个插件, 帮助了不少人, 给你点个赞

**Comment by mescroll** [comment]
感谢支持~ 我已经在问答加入此类情况的描述 http://www.mescroll.com/qa.html?v=190422#q1

Thanks♪(･ω･)ﾉ

**Comment by FengZeming** [comment]
今天在做 tab切换用到 mescroll   遇到这个问题，  我已经整了一下午了。uniapp 是在子组件里写多个的情况。
  发现哪里都没问题 最后居然发现。。。。
ref的名字不能改 我不知道是什么原因看文档也没找到啊 tab第一项用的 <scroll-view>
所以第二项mescrollItem0 之前写mescrollItem1 不好使 改成mescrollItem0好使了。。。 
<mescroll-item ref="mescrollItem0" api-name="user_comment" :isLock="true" :i="1" :index="tabs.index">

**Comment by FengZeming** [comment]
今天在做 tab切换用到 mescroll 遇到这个问题， 我已经整了一下午了。uniapp 是在子组件里写多个的情况。
发现哪里都没问题 最后居然发现。。。。
ref的名字不能改 我不知道是什么原因看文档也没找到啊 tab第一项用的
所以第二项mescrollItem0 之前写mescrollItem1 不好使 改成mescrollItem0好使了。。。
<mescroll-item ref="mescrollItem0" api-name="user_comment" :isLock="true" :i="1" :index="tabs.index">
			<template v-slot="{list}">
				<view class="g-comment" v-for="(item,index) in list " :key="index">
					<view class="left">
						<image :src="item.url" mode="aspectFill"></image>
					</view>
					<view class="right">
						<view class="top">
							<view class="name">{{ item.name }}</view>
							<view class="like">
								<view class="num">默认评价</view>
							</view>
						</view>
						<view class="content">{{ item.content }}</view>
						<view class="bottom">
							{{new Date(item.times).getTime() | date('mm月dd日 hh:MM') }}
						</view>
					</view>
				</view>
			</template>
		</mescroll-item>

**Comment by FengZeming** [comment]
今天在做 tab切换用到 mescroll 遇到这个问题， 我已经整了一下午了。uniapp 是在子组件里写多个的情况。
发现哪里都没问题 最后居然发现。。。。
ref的名字不能改 我不知道是什么原因看文档也没找到啊 tab第一项用的
所以第二项mescrollItem0 之前写mescrollItem1 不好使 改成mescrollItem0好使了。。。
```
<mescroll-item ref="mescrollItem0" api-name="user_comment" :isLock="true" :i="1" :index="tabs.index">
```
