### ISSUE TITLE
如何自定义 up.empty 里面的内容？

### ISSUE THREAD

**Issue by rni-l** [mescroll/mescroll#237]
我配置了 `up.empty` ，但是不能完全自定义里面的内容，`empty.wrapId` 我看了源码，好像也只是弄了一个 div，然后每次触发 `showEmpty` 和 `removeEmpty` 的时候，从里面添加、移除

我想要的效果：
比如下面的 up.empty 配置：
```
up.empty {
  warpId: '#empty',
  isCustom: true // 比如加这样的一个字段，判断是否用自定义的内容
}
```
然后在 HTML 中：
```
<div id="empty">
  <!-- 这里放自定义的内容 -->
</div>
```
我提了个 pr:  #238

**Comment by mescroll** [comment]
感谢您提的pr. 看了一下 简单的几行代码就实现了自定义 非常棒 .. Thanks♪(･ω･)ﾉ

**Comment by Destinygu** [comment]
自定义empty的方案实现了么

**Comment by mescroll** [comment]
https://www.mescroll.com/uni.html#note 第5条
