### ISSUE TITLE
vue-cli3 使用组件方式，微信电脑版浏览器不能滚动或者不显示

### ISSUE THREAD

**Issue by Kennersky** [mescroll/mescroll#242]
如题。使用在复杂的商城项目订单列表中，同样的一套代码应用在两个项目一个表现为能显示列表，但内容不能滚动，另一套则完全不显示列表，而当我独立出来成单独的demo页又能正常显示。。完全不清楚是哪边引起的问题。
*能显示但滚动不正常表现如下,滚动条能动，但列表没动，加载到最底部，显示没有更多数据叠在列表上：
![TIM截图20190518102313](https://user-images.githubusercontent.com/2129521/57963457-f7059f80-7956-11e9-9333-f14481b34d01.png)

*完全不显示列表，刷新也无用：
![TIM截图20190518102530](https://user-images.githubusercontent.com/2129521/57963476-477cfd00-7957-11e9-90ae-9f792c4bad26.png)

pc及手机微信浏览器都正常，就是在微信电脑版的浏览器底下有这个问题。
无法提供异常的demo，应用在一个比较大商城项目。有独立模拟demo,但独立的又是正常的。晕。
demo模拟正常：
![TIM截图20190518103725](https://user-images.githubusercontent.com/2129521/57963604-01289d80-7959-11e9-85a2-56aff7dc472e.png)

有没有小伙伴也有遇到这种情况的可以交流看看。群主大大也帮忙分析一下可能出现的问题是哪一环节。

有异常的订单页面源码：
[order.zip](https://github.com/mescroll/mescroll/files/3193575/order.zip)

demo源码：
[vue-mescroll-demo.zip](https://github.com/mescroll/mescroll/files/3193571/vue-mescroll-demo.zip)

**Comment by y-MaxJh** [comment]
我也碰到了这个问题，它的样式没有加载上来导致。

**Comment by Kennersky** [comment]
> 我也碰到了这个问题，它的样式没有加载上来导致。

兄弟你是怎么解决的呢？指点一下，谢谢

**Comment by Kennersky** [comment]
经观察是电脑版微信的浏览器bug。最近升级到2.6.8.51。一切正常了。
