### ISSUE TITLE
把VUE那个实例代码拷过来，一切都好就是从详情页返回列表页不能定位到之前的位置

### ISSUE THREAD

**Issue by may6288** [mescroll/mescroll#243]
把VUE组件那个实例代码拷过来，一切都好就是从详情页返回列表页不能恢复之前的数据以及定位到之前的位置。是不是需要搭配keep-alive才行。

**Comment by mescroll** [comment]
`beforeRouteEnter (to, from, next) { // 如果没有配置回到顶部按钮或isBounce,则beforeRouteEnter不用写
			    next(vm => {
			       // 找到当前mescroll的ref,调用子组件mescroll-vue的beforeRouteEnter方法
			      vm.$refs.mescroll && vm.$refs.mescroll.beforeRouteEnter() // 进入路由时,滚动到原来的列表位置,恢复回到顶部按钮和isBounce的配置
			    })
			  },
			  beforeRouteLeave (to, from, next) { // 如果没有配置回到顶部按钮或isBounce,则beforeRouteLeave不用写
			     // 找到当前mescroll的ref,调用子组件mescroll-vue的beforeRouteLeave方法
			    this.$refs.mescroll && this.$refs.mescroll.beforeRouteLeave() // 退出路由时,记录列表滚动的位置,隐藏回到顶部按钮和isBounce的配置
			    next()
			  },`

**Comment by AKclown** [comment]
请问一下作者大大，我这个项目过于庞大，所有有很多像列表详情这样子的页面，是不是只能在每个列表页面都监听路由，进行回滚， 这样子会不会太麻烦了呢？ 有没有办法满足这个需要，我现在每个页面都要监听一下。

**Comment by Xiaoshizaizi** [comment]
列表页加个keep-alive呢
