### ISSUE TITLE
为什么有时必须先下拉刷新之后，才能实现上拉加载呢

### ISSUE THREAD

**Issue by milyyy** [mescroll/mescroll#247]
您好，我这里碰到几个问题：
这里我是移动端vue项目
1.为什么有时候必须先下拉刷新之后 才能实现上拉加载呢？
2. 比如我现在有两个tab栏，使用了watch监听后，第一个tab列表的数据在我使用下拉或者上拉行为之后，第二个列表的数据在不足我设置的size情况下也显示了没有更多数据，这是为什么呢？
3.在给mescroll fixed定位后，点击列表项目刷新，列表有时候没变，顶部的tab栏却跟着手势移动了。
望解答，感谢

**Comment by mescroll** [comment]
第一个和第二个问题: 
结束上拉加载第一个参数是必须传的哦 mescroll.endByPage(), mescroll.endBySize(), mescroll.endSuccess() 第一个参数必传;

2.列表没有改变 检查一下数据赋值是否生效哦, 和 定位没有关系的呢

3.建议参考常见问题1排查 http://www.mescroll.com/qa.html#q1

**Comment by milyyy** [comment]
好的，感谢。我再查查


| |
mily
|
|
邮箱：milysong@163.com
|

Signature is customized by Netease Mail Master

在2019年05月30日 09:29，mescroll 写道：

第一个和第二个问题:
结束上拉加载第一个参数是必须传的哦 mescroll.endByPage(), mescroll.endBySize(), mescroll.endSuccess() 第一个参数必传;

2.列表没有改变 检查一下数据赋值是否生效哦, 和 定位没有关系的呢

3.建议参考常见问题1排查 http://www.mescroll.com/qa.html#q1
