### ISSUE TITLE
uni-app一个swiper多个mescroll的情况

### ISSUE THREAD

**Issue by wakaryry** [mescroll/mescroll#248]
mescroll嵌套swiper可以实现所有swiper-item共用的mescroll，但是问题就是他们共享所有的参数以及page，hasNext等。每次切换tab都resetUpScroll来清除，虽然是可用，但是体验不好。每次都是重新加载第一页，以前浏览加载的记录都没有了。

每一个swiper item应该都有自己的page和hasNext，以及当前的scroll-y。

不想共用一个mescroll，不想每次切换一个item都要resetUpScroll。而是想一个item对应一个mescroll，各自有自己的状态。

因为不支持swiper包裹mescroll，我们只能支持mescroll包裹swiper，这样变成了一个swiper事实上最外层只能是一个mescroll。

我们能不能这样：
1. 我们为每一个swiper-item分配一个mescroll，仅仅只是保存历史状态；
2. 在swiper最外层包裹的mescroll，每次切换item的时候，我们把当前切换到的item的mescroll的状态赋值给他，然后它重新更新状态；
3. 在当前item操作，最外层的mescroll和当前item的mescroll同步更新。

谁有没有什么好的实现。还是不能实现出来。

求大神帮忙。

**Comment by mescroll** [comment]
亲 您要不参考一下 
http://www.mescroll.com/preview.html?name=list-mescroll-more
对应的代码:
https://github.com/mescroll/mescroll/tree/master/mescroll-uni/uni-demo/pages/base/list-mescroll-more.vue

**Comment by wakaryry** [comment]
目前先取消了swiper。先这样将就用着。只是不能左右滑动切换内容，用起来觉得很别扭。

**Comment by mescroll** [comment]
1.1.0版本已经支持swiper了哦, 重新下载一下案例哈  里面也有mescroll-swiper的demo
http://ext.dcloud.net.cn/plugin?id=343
