### ISSUE TITLE
上拉加载page参数动态设置

### ISSUE THREAD

**Issue by 7NZ** [mescroll/mescroll#252]
## 问题所在
普通页面的项目，没有使用框架，里面有筛选功能。
在使用mescroll的过程中发现，在筛选之后使用下拉刷新之后，会出现无法上拉加载的情况。

## 可能原因
找了issue，看到了[#236](https://github.com/mescroll/mescroll/issues/236)，看了文档给的代码里面`mescroll.endBySize(curPageData.length, totalSize)`里面`curPageData.length`是判断有无更多数据的依据，`curPageData.length`需要和上拉加载up参数里面`page.size`作比较。

看到这里就想可不可以动态设置上拉加载up参数里面`page`的值，设置一个全局变量赋值给`page.size`，事实证明这样是不行的。

再次看了文档的所有参数，发现mescroll也没有动态设置`page`的方法，倒是找到了`mescroll.resetUpScroll()`这个方法，里面说明了，筛选时候用。
于是用了`mescroll.resetUpScroll()`，然而这个方法会请求上拉加载的回调（不管有没有更多数据），本来筛选时请求了一次接口数据，这样一来不就请求2次？

## （可能的？）需求
能不能给个动态设置上拉加载参数`page`的api?

**Comment by mescroll** [comment]
亲 在常用方法里面有的哦
http://www.mescroll.com/api.html?v=190426#methods


mescroll.setPageNum(num);
mescroll.setPageSize(size);
