### ISSUE TITLE
页面有多个列表 添加空页面 icon 的时候会自动添加一个../

### ISSUE THREAD

**Issue by 799536960** [mescroll/mescroll#253]
页面有多个列表 添加空页面 icon 的时候会自动添加一个../
比如
new MeScroll("mescroll1",
                                 empty: {
						warpId:	"xxid1", 
						icon: "../img/mescroll-empty.png", 
						tip: "暂无相关数据~" 
					}
new MeScroll("mescroll2",
                                 empty: {
						warpId:	"xxid2", 
						icon: "../img/mescroll-empty.png", 
						tip: "暂无相关数据~" //提示
					}
图标路径初始化时设置的一样 但是在跑起来后 在dom中实际生成的img路径中 第一个icon的路径多了一个../ 
如果初始化的时候两个icon 文件不使用同一个则不会出现此问题

**Comment by mescroll** [comment]
亲 您可以看到mescroll.js源码的 我这边并没有对empty.icon做改动哦..
建议您提供一下重现的demo哈
