### ISSUE TITLE
mescroll-uni 无法触发 afterLoading等方法

### ISSUE THREAD

**Issue by StriveNuby** [mescroll/mescroll#254]
测试了进行下拉刷新的配置

```js
downOption: {
      use: true,
        auto: true,
        endDownScroll: function(mescroll) {
          console.log('showLoading')
        },
        afterLoading: function(mescroll) {
          console.log('afterLoading')
          return 300
        }
      }
```

endDownScroll、afterLoading等方法都无法触发

输出源码 props 只输出 
```js
{
      use: true,
        auto: true 
}
```
貌似是uni-app不支持props 方法的问题，这块要怎样处理下？

@mescroll

**Comment by mescroll** [comment]
亲 uni-app的编译不支持props 传function的
只能在mescroll-vue的文件中emit您想要的回调哦

目前mescroll-uni.vue只回调了emptyclick和topclick,您可以参考一下
`<mescroll-uni :down="downOption" @down="downCallback" :up="upOption" @up="upCallback" @init="mescrollInit" 
top="0" bottom="0" **@emptyclick="emptyClick" @topclick="topClick"** ></mescroll-uni>`

如果要加endDownScroll和afterLoading 建议修改mescroll-uni.vue文件哦
endDownScroll在mescroll-uni.vue文件中有,可用直接拓展
afterLoading在mescroll-uni.vue直接写在endDownScroll方法上面也是可以触发的
