### ISSUE TITLE
mescroll-uni在小程序在上拉加载的回调中使用endErr()后无法再次直接上拉触发加载，得向上滚动一小段距离再上拉才能触发上拉加载

### ISSUE THREAD

**Issue by fightfa** [mescroll/mescroll#255]
mescroll-uni在小程序在上拉加载的回调upCallback中使用endErr()后，
用户此时的mescroll已触底，无法再次直接上拉触发加载，
得手势下拉，即列表向上滚动一小段距离使之不触底，再上拉至触底，才能触发上拉加载。
请问大佬呀如何解决这个问题，即如何使已触底状态时再上拉可再次触发上拉加载？
我本想用mescroll.setScrollTop等模拟将mescroll控件的y坐标上移一点，但在uni微信小程序中没效果噢，mescroll.setScrollTop(0)也没法回到列表开头。
mescroll-uni1.0.2版本的。

**Comment by mescroll** [comment]
回到顶部,调用其实是uni.pageScrollTo, 也就是说您可以直接调用uni.pageScrollTo即可
触发上拉加载的回调是基于uni的onReachBottom的... 他这个确实只能触发一次...

我下个版本修复一下 如果endErr()就向上滚动一点,感谢反馈

**Comment by mescroll** [comment]
github已经更新, npm这两天会更新哈
endErr()默认以上滚动110

**Comment by mescroll** [comment]
npm已经更新 1.0.3

**Comment by fightfa** [comment]
哇(◦˙▽˙◦)作者大大真是神速，(●'◡'●)ﾉ❤
