### ISSUE TITLE
列表页面，下拉页面最底部，再次上滑，无法滑动页面（IOS偶现）

### ISSUE THREAD

**Issue by zhangttwork** [mescroll/mescroll#264]
这个应该不是ios回弹效果导致的吧，尝试着设置isBounce=false,但是没有作用，希望坐着关注下问题看看哪里需要更改

**Comment by mescroll** [comment]
请问是在ios的微信端吗? 是mescroll.js还是mescroll-uni呢

**Comment by zhangttwork** [comment]
是app内嵌h5,mescroll.js

**Comment by mescroll** [comment]
需要给mescroll设置高度哦 不然滚动会失效.. 请参考官网常见问题1

**Comment by AKclown** [comment]
我也遇到这个问题。不过他是影响到外层的滚动条了

**Comment by 13230357894** [comment]
@mescroll 我这边遇到了一个在端内webview打开h5页面，右滑角度45度左右，webview没有响应，h5也没有响应不下拉也不右滑
