### ISSUE TITLE
mescroll-uni属性值:fixed设置为false，上拉加载无法触发，为true的时候正常

### ISSUE THREAD

**Issue by Sweets001** [mescroll/mescroll#265]

**Comment by zhangweiwei0326** [comment]
我也碰到这个问题 不知怎么解决

**Comment by Sweets001** [comment]
> 我也碰到这个问题 不知怎么解决

已经解决了，在引用mescroll-uni组件的页面，将页面最外层容器（不是page）设置 height:100%

**Comment by mescroll** [comment]
http://www.mescroll.com/qa.html?v=190701#q20
