### ISSUE TITLE
你有遇到过吗Vue warn

### ISSUE THREAD

**Issue by dreamxyp** [mescroll/mescroll#266]
VM33675:1 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "list"

found in

---> components/other/pd-list
       components/mescroll-uni/mescroll-uni
         pages/_test/base/mescroll-options

**Comment by mescroll** [comment]
http://ask.dcloud.net.cn/question/72693
官方已修复,更新HBuilderX即可
