### ISSUE TITLE
使用uni开发微信公众号中MescrollUni如何禁止ios 微信的弹性回弹

### ISSUE THREAD

**Issue by Buggersldx** [mescroll/mescroll#267]
使用uni开发微信公众号中MescrollUni如何禁止ios 微信的弹性回弹

MescrollUni官网的文档上面给的方案一个是
{
	   "path" : "pages/xxx/xxx", // 只配置使用mescroll-uni的页面
	   "style" : {
			"navigationBarTitleText" : "xxx",
			"enablePullDownRefresh" : false, // 不开启下拉刷新, 默认就是false
			"app-plus" : {
				"bounce" : "none" // 取消iOS回弹,避免和下拉刷新冲突 (小程序无法取消)
			}
		}
	}
测试了不能用

第二个方案

![image](https://user-images.githubusercontent.com/21056737/61424457-182e4080-a946-11e9-8f72-ce9cb1f24765.png)
不是uni使用的

**Comment by mescroll** [comment]
预期下周提供~

**Comment by mescroll** [comment]
http://www.mescroll.com/qa.html?v=190725#q25
更新最新版本即可 , 内部已默认禁止isBounce
