### ISSUE TITLE
mescroll.resetUpScroll(true) 有时候会触发两次上啦加载

### ISSUE THREAD

**Issue by q310550690** [mescroll/mescroll#27]
通过mescroll.resetUpScroll(true)在页面第一次加载的时候默认显示下拉刷新的样式

可是有时候会同时显示了上啦加载的样式，经过排查发现是有时候会执行两次上啦加载的回调

希望作者能够排查下。

正常应该是这样  http://ww1.sinaimg.cn/large/6dac2142gy1fja5wiz1dcj20k00zk74y.jpg
![](http://ww1.sinaimg.cn/large/6dac2142gy1fja5wiz1dcj20k00zk74y.jpg)

触发了两次上啦加载  http://ww1.sinaimg.cn/large/6dac2142gy1fja5wvz6dcj20k00zkgma.jpg
![](http://ww1.sinaimg.cn/large/6dac2142gy1fja5wvz6dcj20k00zkgma.jpg)

**Comment by q310550690** [comment]
![](http://ww1.sinaimg.cn/large/6dac2142gy1fja5r0m3s0j20gm0hc0tf.jpg)

**Comment by mescroll** [comment]
亲 虽然没有看到你发的源码;
我觉得问题应该是配置错了参数,或者重复调用了上拉回调.建议您参考一下基础案例或提供代码demo, 这样我才能帮你排查问题~
mescroll.resetUpScroll()会触发一次上拉加载的
