### ISSUE TITLE
关于多mescroll初始化加载的问题

### ISSUE THREAD

**Issue by EDacdy** [mescroll/mescroll#270]
根据官网下载的例子进行了修改，去除了一些本人认为不是很需要的配置，出现以下问题：页面首次加载，当前swiper tab页面可以正常加载，切换到其他tab页时无法正常加载，比如进入页面是热门tab可以正常加载，进入最新tab无法加载（报错如下图），需要从最新tab切换回热门tab一次，再次切换回最新tab才能加载。
![image](https://user-images.githubusercontent.com/33247211/62470000-fc42ef80-b7cb-11e9-9e1b-f8b596e089dc.png)
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'triggerDownScroll' of null"
为什么会需要切换一遍标签才能触发triggerDownScroll()，问题最可能出在哪里，开发者能否答疑解惑，十分感谢！

**Comment by mescroll** [comment]
多mescroll的实例是需要页面加载完成就要全部初始化的
有可能其他tab用了v-if , 导致页面初始化的时候 其他tab的mescroll元素并没有渲染
