### ISSUE TITLE
怎么禁用mescroll，当滚动到一定的高度在开启

### ISSUE THREAD

**Issue by AKclown** [mescroll/mescroll#272]
场景是这样的，有一个tab栏需要需要做成吸附的效果。但是tab栏距离顶部还是有段距离，这个mescroll实在tab里面引用的。我想刚开始是滚动外层的浏览器，等tab栏吸附在滚动这个插件，实现下拉加载的效果。现在问题是：  当我下滑的时候，没问题，但是最外层上滑就卡住了

**Comment by AKclown** [comment]
有点效果类似，antd的移动的下拉刷新那个组件

**Comment by mescroll** [comment]
http://www.mescroll.com/preview.html?name=sticky

**Comment by AKclown** [comment]
谢谢，没注意到，我去看看
