### ISSUE TITLE
小于刷新范围时，松手回弹，onMoving监听不到

### ISSUE THREAD

**Issue by konglili502** [mescroll/mescroll#275]
如何监听mescroll-downwarp元素的高度变化？？
是否可以添加一个函数，监听mescroll-downwarp元素的高度变化。
现在的onMoving方法，不能监听到小于刷新范围时，松手的回弹之后，不能监听到

**Comment by konglili502** [comment]
最好把me的touchend事件抛出，更灵活

**Comment by mescroll** [comment]
回弹之后的高度直接设置为0的; 期间的动画是通过css过渡transition实现的 
这个时候的高度变化无法监听
你可以在endDownScroll中做transition的处理
