### ISSUE TITLE
scrollTo()方法没有效果

### ISSUE THREAD

**Issue by Jacky-MYD** [mescroll/mescroll#280]
你好，我的版本是1.4.1，滚动区域为1400，但是我想默认组件滚动位置为底部，设置无效果this.mescroll.scrollTo(1000, 0)，写死了高度值都无效果。

**Comment by mescroll** [comment]
建议延时调用scrollTo  确保列表数据和图片已加载

**Comment by Jacky-MYD** [comment]
是父级没有设定高度的问题
