### ISSUE TITLE
上滑获取几次数据之后，在回到顶部下拉刷新，页码没有变成1哦

### ISSUE THREAD

**Issue by Bai-xiaoxiao** [mescroll/mescroll#281]
假设列表有50条数据，每次我请求10条，上滑到第3页之后，回到顶部，再用下拉刷新，主要js中的判断请求是否结束的函数（endBySize，endByPage，endSuccess）中，this.optUp.page.num还是3，下拉刷新之后页码应该变为1哦

**Comment by mescroll** [comment]
下拉刷新的down的Callback应该使用 mescroll.resetUpScroll才对
