### ISSUE TITLE
当鼠标点击就是触发下拉加载

### ISSUE THREAD

**Issue by AKclown** [mescroll/mescroll#283]
页面没有到底，每次鼠标往下拉方向点击  就会触发下拉刷新，请问作者大大这是什么原因呢？

**Comment by AKclown** [comment]
一开始根据父元素高度，现在用fixed就没问题了.不知道问题在哪里

**Comment by mescroll** [comment]
可能父元素的父元素也没有高度哦.. 还是用fixed简单快捷
