### ISSUE TITLE
滑动的过程中会触发item的longpress事件？

### ISSUE THREAD

**Issue by tydqcjj** [mescroll/mescroll#284]
手指滑动的过程中，由于是长按。会触发我给item项设置的@longpress事件。
请问怎么解决？

**Comment by mescroll** [comment]
并没有重新此问题哦.. 
请问是mescroll.js还是mescroll-uni ; 
苹果还是Android呢.. 

如果手指按下去 300ms没有滑动的话会触发longpress,这个没有问题
如果手指按下去300ms内滑动了,就不会触发, 滑动过程长按也不会触发
