### ISSUE TITLE
uniapp  IOS,在断网情况下 ，上拉加载会一直被触发

### ISSUE THREAD

**Issue by lrthorhammer007** [mescroll/mescroll#285]
如题ios,发现在上滑过程中scroll 事件会一直被触发,从而导致triggerUpScroll 一直被触发

**Comment by mescroll** [comment]
异常的情况, 需调用mescroll.endErr()隐藏加载状态

**Comment by lrthorhammer007** [comment]
已经调用endErr   一直加载的原因是scroll 事件会一直被触发
