### ISSUE TITLE
下拉到最后一页后，页面点击事件失效

### ISSUE THREAD

**Issue by langzhigang** [mescroll/mescroll#286]
感觉是这个div覆盖了整个页面，导致无法点击到下一层。
还有就是end这个字也没看到了。不知道是否有人遇类似问题。
`<div class="mescroll-upwarp mescroll-hardware" style="visibility: visible; display: block;"><p class="upwarp-nodata">-- END --</p></div>`

**Comment by langzhigang** [comment]
“<div class="mescroll-upwarp mescroll-hardware" style="visibility: visible; display: block;"><p class="upwarp-nodata">-- END --</p></div>”

**Comment by mescroll** [comment]
检查您的列表是否用了float, 如果有的话 需要清一下float;
mescroll里面的内容是否用了定位,导致内容并没有把mescroll的高度撑开 ?
