### ISSUE TITLE
uni-app下mescroll返回顶部功能经常会被内容遮住

### ISSUE THREAD

**Issue by messchow** [mescroll/mescroll#287]
![微信图片_20190904173845](https://user-images.githubusercontent.com/32609442/64244221-3b836e00-cf3b-11e9-9e4b-c267cdcd7fb4.png)
![image](https://user-images.githubusercontent.com/32609442/64244224-3de5c800-cf3b-11e9-8572-c97ecdde048f.png)
我是在吧mescroll封装在组件中使用，就会出现返回顶部功能忽然在list上层忽然在list下层的情况。
是否是#shadow-root下fixed不正常？层级有问题 希望能帮我解决下问题

**Comment by mescroll** [comment]
小程序编辑器会把组件slot部分拿出来显示, 很难看出层级结构, 可以编译到浏览器看就很清楚了..
然后建议对比一下 http://www.mescroll.com/preview.html?name=swiper-tap 这个案例哦
没有出现您反馈的问题哈~
