### ISSUE TITLE
demo疑问

### ISSUE THREAD

**Issue by cddsgtc** [mescroll/mescroll#29]
![_20170915155454](https://user-images.githubusercontent.com/16315661/30472277-4f8e2dde-9a2e-11e7-8577-cd9293a2457f.png)
如果所示，如果我每次请求接口返回的是某个页面的数据，不是直接加到一个数组中就行了嘛？
这里pageNum不是请求页的数字吗还是到此为止所有的页的数，不太明白。

**Comment by cddsgtc** [comment]
关了吧，我明白怎么回事了，这种方式做假数据太容易混淆了。

**Comment by mescroll** [comment]
恩 我想想其他做假数据的方式; 以前是ajax分页读取json文件的数据的; 有的用户下载下来就直接打开文件夹 浏览器直接ajax读不到json 报跨域的错误的; 要拖到编辑器看就没有问题; 为了避免这个错误就直接引入json文件做假数据了.. 既然反馈的话 我考虑一下 然后换回原来的ajax分页读json文件数据好了

**Comment by cddsgtc** [comment]
@mescroll 
预祝该项目做得更好。
个人提出两个建议：
1. 希望在在文档写出用的什么技术，什么原理，这样在学习该项目的时候我或者其他人会思考每个属性或者方法大概用来做什么。
2. 希望该项目的使用向更傻瓜式方向发展。

对于需不需要改回用ajax方式，希望你慎重考虑下，可能不是每个学习者都是我这样思考的。
当时我觉得page.num和page.size应该是返回的页数已经那个页面的数据数量，所以应该把他们添加到渲染的数组里，但是看到那处的代码还对这两个进行操作，所以有些疑惑还要对这个两个属性加工才能传到数组里？后来捋了一两遍代码，又意识到这个是专门给做假新闻数据的，所以才觉得只不过是想得到一个递增的新闻标题数字而已。。

**Comment by mescroll** [comment]
感谢您的建议.. 我简化一下demo~
