### ISSUE TITLE
setClientHeigh()中计算scroll-view的高度不正确

### ISSUE THREAD

**Issue by hy20160705** [mescroll/mescroll#290]
获取mescroll-uni.vue中的scroll-view的高度不对（clientHeight） 一直获取的是100 实际高度远远大于这个,导致在上拉加载的时候一直有问题

**Comment by mescroll** [comment]
mescroll-uni的滚动需要有高度, 默认:fixed="true" 通过fixed固定高度的; 
如果设置为false,高度则跟随父元素,需要给父元素设置高度,比如100%
