### ISSUE TITLE
大神 ,我这边按照example写的,上拉加载的时候callBack多次调用请求,这是什么原因?

### ISSUE THREAD

**Issue by iJay** [mescroll/mescroll#291]
上拉加载的时候callBack多次调用请求,这是什么原因?down明明设置了use是false,还是有下拉刷新

**Comment by iJay** [comment]
`<template>
  <div class="ranking">
    <header>
      <i class="arrow-left-icon">《 </i>
      <h2>榜单</h2>
      <span>09-22<i class="arrow-down-icon"></i></span>
    </header>
    <mescroll-vue ref="mescroll" :up="mescrollUp" @init="mescrollInit">
      <div class="info">
        <div class="org-name">丁丁团队</div>
        <div class="user-name">李木子</div>
        <div class="rank">今日排名: 暂无</div>
        <div class="three-user">
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
      <div>
        <ul>
          <li v-for="item in list" class="list-item" :key="item.index">{{item}}</li>
        </ul>
      </div>
    </mescroll-vue>
  </div>
</template>
<script>
import MescrollVue from 'mescroll.js/mescroll.vue'
import axios from 'axios'

export default {
  name: 'Ranking',
  components: {
    MescrollVue
  },
  data() {
    return {
      list: [],
      mescroll: null,
      mescrollDown: {},
      mescrollUp: {
        callback: this.upCallback,
        isBounce: false,
        page: {
          num: 0,
          size: 10
        },
        noMoreSize: 5,
        lazyLoad: {
          use: true // 是否开启懒加载,默认false
        }
      }
    }
  },
  mounted() {
    
  },
  methods: {
    mescrollInit (mescroll) {
      this.mescroll = mescroll
    },
    upCallback (page, mescroll) {
      var self = this
      axios.get('./static/mock/info.json',
      {
        params: {
          num: page.num, // 页码
			    size: page.size // 每页长度
        }
      }).then( (res) => {
        self.list = self.list.concat(res.data.data);
        self.$nextTick(() => {
          mescroll.endSuccess(res.data.data.length)
        })
      }).catch( (err) => {
        mescroll.endErr();
      })
    }
  },
}
</script>
<style scoped>
mescroll-vue{
  position: fixed;
  top: 80px;
  bottom: 50px;
  height: auto; /*如设置bottom:50px,则需height:auto才能生效*/
}
</style>
`

**Comment by mescroll** [comment]
没有给mescroll配置高度哦, 可以写死高度试试
参考常见问题1 http://www.mescroll.com/qa.html?v=190725
