### ISSUE TITLE
我不想使用下拉刷新，但是需要ios在顶部可以继续往下拖拽回弹

### ISSUE THREAD

**Issue by kswOok** [mescroll/mescroll#292]
我不实用下拉刷新的时候，如何可以让iOS回弹的下拽手感跟系统完全一样。现在我通过 使用下拉刷新，设置参数怎么样都无法达到跟系统下拽阻尼的手感一直。总觉得卡顿 或者速度很奇怪。

**Comment by mescroll** [comment]
1. 配置down的use为false可禁用下拉刷新
2.使用body为滚动区域会有iOS的回弹 http://www.mescroll.com/preview.html?name=list-mescroll-body
