### ISSUE TITLE
上拉加载多次数据后，再下拉刷新并保留当前刷新的数据之后，下拉加载不起作用的问题

### ISSUE THREAD

**Issue by y-MaxJh** [mescroll/mescroll#294]
如题所述，并拿官方demo修改测试也出现同样的问题。

![image](https://user-images.githubusercontent.com/20962921/65023739-0e38b600-d966-11e9-816f-41c8c6a3aba8.png)

### 只修改了list-products.vue文件，并将pdlist.js文件新增了100+条数据

![image](https://user-images.githubusercontent.com/20962921/65023917-6a9bd580-d966-11e9-8035-0ca58a366227.png)

页面显示大致图下
![image](https://user-images.githubusercontent.com/20962921/65024135-cd8d6c80-d966-11e9-9875-750ea1b8b328.png)

进入页面后，先执行了5次上拉加载数据后，在回到顶部执行下拉加载，之后，就无法在上拉加载数据了。

如果第一页的数据能占满全屏的话，是没问题的。

如果在业务开发中，个人认为是可以改变page.size来做适配。但不是最好的解决方案（分页的数据不是自己决定的时候），不知道有什么更好的解决方案？

**Comment by y-MaxJh** [comment]
![image](https://user-images.githubusercontent.com/20962921/65024828-2a3d5700-d968-11e9-8e9c-8e9c64345af0.png)

**Comment by y-MaxJh** [comment]
查看源码发现是 MeScroll.prototype.triggerUpScroll 方法中的
![image](https://user-images.githubusercontent.com/20962921/65028195-43e19d00-d96e-11e9-9168-193555ffa4a0.png)

![image](https://user-images.githubusercontent.com/20962921/65028241-58259a00-d96e-11e9-89fe-b15e5776e92c.png)

scrollHeight在下载刷新后没有重置，一直保持原来的滚动区域大小导致

**Comment by mescroll** [comment]
感谢反馈~ 确实没有考虑到这个问题~ 您真仔细, 解决方法也很巧妙~ Thanks♪(･ω･)ﾉ
我计划在1.1.8版本中更新~
