### ISSUE TITLE
ios滑动问题

### ISSUE THREAD

**Issue by AKclown** [mescroll/mescroll#295]
使用技术：
vue
问题：
大部分页面基于mescroll没什么问题可以滑动，但是一些没有使用到mescroll，而是原生滚动在ios上路由第一次进入不能滑动，只能刷新才可以滑动。 经过查找方法isBounce设置为false有这种情况，如果是true就没有这种情况了。（Android一切都好）

希望作者大大，能够修复一下这个问题，因为在浏览器感觉没必要回弹

**Comment by mescroll** [comment]
建议看看: http://www.mescroll.com/qa.html?v=190725#q10

**Comment by AKclown** [comment]
好的，谢谢作者大大
