### ISSUE TITLE
局部滚动报错

### ISSUE THREAD

**Issue by RicoLiu** [mescroll/mescroll#298]
使用 vue 引入 mescroll ，想实现局部下拉刷新。错误信息如下
```
the element with id as "mescroll" can not be found: 

document.getElementById("mescroll")==null
```
~~经排查，是外部容器为 `flex` 布局导致。~~

~~mescroll 是不支持 `flex` 布局么？~~

不是页面导致布局。

请问是什么问题导致？

**Comment by mescroll** [comment]
意思是初始化mescroll的时候 传入的"mescroll"这个id不存在或者此时的div还未被渲染

建议延时初始化mescroll
