### ISSUE TITLE
這能用在vue上嗎

### ISSUE THREAD

**Issue by c941010623** [mescroll/mescroll#3]

**Comment by web-tiny** [comment]
你们在用的时候有没有遇到这种情况：在Android微信端的时候上拉加载更多没有任何反应，下拉刷新的时候没问题，在IOS的微信端上拉加载和下拉刷新都没问题的

**Comment by mescroll** [comment]
亲 可以在vue上使用的

**Comment by mescroll** [comment]
@web-tiny  您应该是QQ上联系我的 对吧 已经帮您解决 原因是您设置了一个全局的样式 *{touch-action: none} 导致的哈~  另外O(∩_∩)O谢谢你的大红包 哈哈

**Comment by silvacheng** [comment]
advice you use BScroll

**Comment by mescroll** [comment]
已新增vue的示例, http://www.mescroll.com/preview.html?name=list-products-vue
另外 mescroll更新至1.1.5

**Comment by yilanye** [comment]
我也是这种情况？ 该怎么解决呢
