### ISSUE TITLE
当设置body为滚动区域，其他页面不能下拉的问题

### ISSUE THREAD

**Issue by kevin611003** [mescroll/mescroll#301]
版本1.4.1

在vue项目中当设置body为滚动区域，在页面A上拉加载一些数据后，切换到页面B，页面B的div设置`overflow-y: scroll`，页面B的这个div在浏览器可以上拉，但是再往下拉拉不动，必须先再往上拉一下手指不松开再下拉才可以。初步检查是body的touchmove事件的原因，将mescroll.js绑定touchmove事件时passive设置为true才行。请问有其他的解决方法吗？

**Comment by cmdreay** [comment]
按照你的方法，修复了，太感谢了

**Comment by mescroll** [comment]
如果是body为滚动区域 则里面的div不应该设置为overflow:scroll的 因为此时的滚动区域就变成了这个div 而不是body了
