### ISSUE TITLE
请问作者大大 有没有  uni懒加载图片的案例啊!

### ISSUE THREAD

**Issue by q767095693** [mescroll/mescroll#307]
uni的懒加载配置 mescroll-uni.vue里面配置还是在mescroll-uni-option.js里面配置呢 麻烦麻烦

**Comment by mescroll** [comment]
mescroll-uni暂时还没懒加载的配置,预计下个月加上..
mescroll.js就有..

**Comment by q767095693** [comment]
好的 祝mescroll越做越好!!
