### ISSUE TITLE
大部分安卓手机出现上拉无限加载。测试了官方的demo也有这个问题。

### ISSUE THREAD

**Issue by yx94** [mescroll/mescroll#310]
安卓手机连续上拉加载操作，就会出现一个很鬼畜的现象，页面不发生滑动，页面数据一直在变，一直在替换新的数据，然后下面的加载loading动画一直在转。试过了给的demo，就第一个新闻的列表，在安卓手机上运行也会出现这个问题。现在没什么解决的方向。

**Comment by NPZ000** [comment]
我也发现这个问题了

**Comment by zcs151** [comment]
对啊  找了半天也没办法，谁解决了说一下啊

**Comment by ivanlee93** [comment]
小程序使用uni版本一样的问题，等大佬回复一下

**Comment by DaDaDaBocai** [comment]
同样问题，求解决

**Comment by wakaryry** [comment]
上一个版本也是这样吗？

**Comment by zcs151** [comment]
> 上一个版本也是这样吗？
不知道  应该是好的  就这几天发现的问题 我怀疑是不是微信的问题

**Comment by yuxin112483** [comment]
这一块我也有在微信小程序的社区发现有人提过这个问题，但是找不到什么解决方案，不知道能不能从重设滚动高度这一块入手，这两天弄这个问题头发感觉又稀少了好多。希望各位大大伸出援手，救救孩子吧！

**Comment by zcs151** [comment]
我也是这两天搞这个问题搞得头大啊  刚群主解决了半天也没弄了  不知道现在怎么样了

**Comment by zcs151** [comment]
老哥 留个联系方式  交流下

**Comment by yx94** [comment]
可以的老哥   @zcs151  18166036572  加微信吧

**Comment by tangniyuqi** [comment]
我刚才也发现这个问题了uni版本 微信小程序（安卓版微信），MAC版微信开发工具无这个问题

**Comment by tangniyuqi** [comment]
> me.preScrollY && me.scrollTo(me.preScrollY, 0)

无效

**Comment by tangniyuqi** [comment]
> 试试 在mescroll-uni.js的544行加上me.preScrollY && me.scrollTo(me.preScrollY, 0)

添加了测试无效

**Comment by mescroll** [comment]
额 应该是540行 也就是 me.endUpScroll(isShowNoMore); 这一行后面添加 me.preScrollY && me.scrollTo(me.preScrollY, 0)

**Comment by mescroll** [comment]
更新到 1.1.8版本哈 已修复
