### ISSUE TITLE
vue使用demo中的吸顶效果不执行onScroll

### ISSUE THREAD

**Issue by feikai2012** [mescroll/mescroll#312]
mescroll.optUp.onScroll=function(mescroll, y, isUp){
console.log("up --> onScroll 列表当前滚动的距离 y = " + y + ", 是否向上滑动 isUp = " + isUp);
if(y>=navWarp.offsetTop){
      navContent.classList.add("nav-fixed");
	}else{
	navContent.classList.remove("nav-fixed");
}
}
这块vue中应该写在什么位置。我初始化中使用new MeScroll("mescroll")也是不执行的！

**Comment by mescroll** [comment]
建议使用 mescroll-vue的组件;  如果手动new MeScroll,则需要在dom挂载之后调用
