### ISSUE TITLE
在手机webview中使用问题

### ISSUE THREAD

**Issue by LiuJCode** [mescroll/mescroll#314]
在webview中使用，滑动不灵敏，没有触发滑动事件，主要问题是：当列表滑动到底部后展示出没有更多数据后，列表无法继续滑动。

**Comment by LiuJCode** [comment]
主要就是上拉的时候，滑动事件没法触发。

**Comment by mescroll** [comment]
这个很显然是没有给mescroll固定高度..  http://www.mescroll.com/qa.html?v=191101
