### ISSUE TITLE
能否提供showNoMore的对应方法hideNoMore

### ISSUE THREAD

**Issue by lingdOoOb** [mescroll/mescroll#317]
在数据少的时候，下拉刷新清空列表后就会看见htmlNodata的内容
<img width="486" alt="image" src="https://user-images.githubusercontent.com/25924241/69298945-469c8f00-0c4a-11ea-9457-763f343f4221.png">

**Comment by mescroll** [comment]
无需调用showNoMore和hideNoMore的 建议按照文档的upCallback方法处理哦
