### ISSUE TITLE
加载完数据以后，页面无法向下滚动是什么问题

### ISSUE THREAD

**Issue by ZR1984** [mescroll/mescroll#319]

**Comment by mescroll** [comment]
建议查看: http://www.mescroll.com/qa.html?v=191101#q20
和 http://www.mescroll.com/qa.html?v=191101#q10

**Comment by mescroll** [comment]
建议查看: http://www.mescroll.com/qa.html?v=191101#q20
和 http://www.mescroll.com/qa.html?v=191101#q10
