### ISSUE TITLE
<mescroll-vue ref="mescroll" :down="mescrollDown" :up="mescrollUp" @init="mescrollInit" > ... </mescroll-vue>

### ISSUE THREAD

**Issue by LiuJCode** [mescroll/mescroll#320]
IOS手机中不显示内容，安卓和pc 都可以显示

**Comment by LiuJCode** [comment]
<div id="ptb-div-unused" class="tab-content">
                            <mescroll-vue ref="mescroll" :down="mescrollDown" :up="mescrollUpUnused" @init="mescrollInit">
                                <div v-for="item in itemsunused" class="item-div item-div-unused">
                                    sadasdasd   
                                    asdasdasdas
                                    asdas
                                </div>
                            </mescroll-vue>
                        </div>

**Comment by LiuJCode** [comment]
<div id="ptb-div-unused" class="tab-content">
                            <mescroll-vue ref="mescroll" :down="mescrollDown" :up="mescrollUpUnused" @init="mescrollInit">
                                <div v-for="item in itemsunused" class="item-div item-div-unused">
                                    sadasdasd   
                                    asdasdasdas
                                    asdas
                                </div>
                            </mescroll-vue>
                        </div>

**Comment by LiuJCode** [comment]
**<div id="ptb-div-unused" class="tab-content">
                            <mescroll-vue ref="mescroll" :down="mescrollDown" :up="mescrollUpUnused" @init="mescrollInit">
                                <div v-for="item in itemsunused" class="item-div item-div-unused">
                                    sadasdasd   
                                    asdasdasdas
                                    asdas
                                </div>
                            </mescroll-vue>
                        </div>**

**Comment by LiuJCode** [comment]
`<div id="ptb-div-unused" class="tab-content">
                            <mescroll-vue ref="mescroll" :down="mescrollDown" :up="mescrollUpUnused" @init="mescrollInit">
                                <div v-for="item in itemsunused" class="item-div item-div-unused">
                                    sadasdasd   
                                    asdasdasdas
                                    asdas
                                </div>
                            </mescroll-vue>
                        </div>`

**Comment by LiuJCode** [comment]
知道的兄弟进来指点一二 感谢了

**Comment by mescroll** [comment]
需要给mescroll指定固定的高度, 可以参考文档通过fixed定位固定高度
