### ISSUE TITLE
配置了lazyload但是auto设为false之后第一屏没有把图片加载出来

### ISSUE THREAD

**Issue by suiyi8760** [mescroll/mescroll#323]
```
mescrollUp: {
        auto: false, // 去掉后正常
        lazyLoad: {
          use: true,
          attr: 'imgurl'
        },
}
```
如图配置刚进入页面要滚动一下才会把图片加载出来

**Comment by mescroll** [comment]
mescroll在列表滚动时会自动加载可视区域内的图片.
另外,有时候您可能会动态添加或修改图片,希望手动触发一下懒加载,
那么只需调用 mescroll.lazyLoad() 或 mescroll.endByPage() 或 mescroll.endBySize() 或 mescroll.endSuccess() 即可.

--

也就是说你在上拉回调中并没有调用 mescroll.endByPage() 或 mescroll.endBySize() 或 mescroll.endSuccess() 补上即可
