### ISSUE TITLE
sticky 吸顶悬浮建议

### ISSUE THREAD

**Issue by JimboXie** [mescroll/mescroll#324]
sticky 吸顶悬浮可以用 uni.createIntersectionObserver 监听节点交叉状态来达到吸顶悬浮效果，滚动监听效果会差点，如果速度过快会出现闪动

**Comment by mescroll** [comment]
感谢建议哈~(*＾-゜)v

**Comment by night-Magicl** [comment]
请问一下，没有vue都吸顶实例代码吗，下载都demo里没看到吸顶效果都例子，急，在线等

**Comment by mescroll** [comment]
已推荐使用sticky属性实现了
