### ISSUE TITLE
字节跳动小程序，上拉刷新  设置 scrollTop=0， 

### ISSUE THREAD

**Issue by xybingbing** [mescroll/mescroll#326]
![image](https://user-images.githubusercontent.com/10228562/72064459-e1464f80-3316-11ea-84f3-3b1f6ce3f8cf.png)
最新版本还是这样。
我测试的情况会根据   up.toTop.offset 设置的值   自动重置  scrollTop=0

字节跳动小程序 官网的
![image](https://user-images.githubusercontent.com/10228562/72072438-e7ddc280-3328-11ea-8955-6b66fe4f1938.png)

**Comment by mescroll** [comment]
在1.2.1版本已推荐使用mescroll-body 可解决此问题

**Comment by zd198666** [comment]
swiper中无法触发mescroll-mixins.js的onPageScroll和onReachBottom方法,只能用mescroll-uni,不能用mescroll-body
