### ISSUE TITLE
报无法上拉加载BUG，在Android的H5上，前一个页面有键盘弹起时，跳转第二个scroll页面后，无法上拉加载

### ISSUE THREAD

**Issue by mrlinjw** [mescroll/mescroll#327]
在Android的H5上，前一个页面有键盘弹起时，跳转第二个scroll页面后，无法上拉加载

**Comment by mrlinjw** [comment]
Android上，由于键盘弹起，会改变浏览器可视化区域的高度，导致view.boundingClientRect 回调的data.height的高度为：浏览器高度-键盘高度

**Comment by mescroll** [comment]
从1.2.1版本开始推荐使用 mescroll-body 请更新哈
