### ISSUE TITLE
1.2.3版本mescroll-body 自动下拉刷新的问题

### ISSUE THREAD

**Issue by xxvolvo** [mescroll/mescroll#332]
auto和native同时为true时，进入页面无法自动下拉刷新。navtive为false时正常。配置了原生的下拉刷新事件也无法触发。

**Comment by xxvolvo** [comment]
mescroll-uni模式下 采用this.mescroll.endSuccess 这种写法 加载完成后loading提示无法正确隐藏。
采用参数形式mescroll.endSuccess正常

**Comment by mescroll** [comment]
你可能没有引入mescroll-mixins.js;

**Comment by xxvolvo** [comment]
> 你可能没有引入mescroll-mixins.js;

引入了

**Comment by xxvolvo** [comment]
![WeChat4ce1d504cc6d59f0c2a86e1c480cddc9](https://user-images.githubusercontent.com/16984534/75625511-cba82480-5bf9-11ea-868c-80239548fe35.png)
![WeChatf3913ab7aa3dd0dc512ec99b0dcfbab3](https://user-images.githubusercontent.com/16984534/75625514-ce0a7e80-5bf9-11ea-82f5-bb23b4fce4a8.png)

**Comment by xxvolvo** [comment]
> 你可能没有引入mescroll-mixins.js;

不知道关issue的原因是啥 这两个问题都是非常好复现的
问题1 auto:true，native:false时自动下拉是正常。
问题2 这个只是UI显示问题 数据加载是正常的。

这个回复有点敷衍吧 没有引入这个js很多功能是不能正常实现的。目前只是这两个工况有点小问题。

插件来源=》npm
