### ISSUE TITLE
使用 npm 安装 之后, 在小程序中使用 报错 “'getElementsByTagName' of undefined;at setTimeout callback function‘’

### ISSUE THREAD

**Issue by ZhiGang-Fang** [mescroll/mescroll#335]
// 引入
import MescrollBody from 'mescroll-uni/mescroll-body.vue'
import MescrollMixin from 'mescroll-uni/mescroll-mixins.js'

mixins: [MescrollMixin],
  components: {
    MescrollBody
  }

<mescroll-body
    ref="mescrollRef"
    :down="downOption"
    :up="upOption"
    :fixed="true"
    @init="mescrollInit"
    @down="downCallback"
    @up="upCallback"
    @emptyclick="emptyClick"
    @topclick="topClick"
    @scroll="scroll"
  >
    <slot></slot>
</mescroll-body>

![image](https://user-images.githubusercontent.com/24228407/75842337-f7e6bf80-5e0a-11ea-9404-35a7c4934c5a.png)

**Comment by mescroll** [comment]
你安装错了吧 mescroll-uni的npm是 npm install --save mescroll-uni 

http://www.mescroll.com/uni.html?v=20200311#note
