### ISSUE TITLE
toTop的src

### ISSUE THREAD

**Issue by huoyou** [mescroll/mescroll#336]
请问开发环境下的src应该怎么设置，我运行了你的demo也无法正确显示图片，只有打包后图片路径才正确吗？

**Comment by mescroll** [comment]
支持网络图和本地路径的;  没有显示可能你的路径没有设置正确 建议检查一下

**Comment by huoyou** [comment]
多谢回答，我单独拿了img标签试过路径没问题的，而且我把你的demo里的src和static拿出来运行，也是无法正常显示的，现在我换成网络图片了--
