### ISSUE TITLE
请问作者，是不是不支持nvue呢

### ISSUE THREAD

**Issue by cooliean** [mescroll/mescroll#338]
：请问作者，是不是不支持nvue呢
我试了一下，好像不行
还是我用法不对嗯，谢谢了，我试的是最基础的新闻例子

**Comment by xb12369** [comment]
这个是16年的时候拉取到的代码，最新没有更新，能不能支持nvue目前还没有研究

**Comment by mescroll** [comment]
是的 不支持nvue
