### ISSUE TITLE
mscroll方法up和down的样式不一致

### ISSUE THREAD

**Issue by wqbill** [mescroll/mescroll#341]
```
<div id="mescroll" class="mescroll" style="margin-top: 61px;">
    <ul class="list" id='orderList'>
    </ul>
</div>
```
头部有个fixed搜索框
```
         up: {
             callback: findAllList
         }
```
和
```
         down: {
             callback: findAllList
         }
```
样式不一致

只配置up样式正常

只配置down最下面有61px超出屏幕，无法继续滑动。再配置一个空的up，样式才能正常

这是哪里计算样式有问题把？

**Comment by mescroll** [comment]
把 style="margin-top: 61px;"去掉,然后

.mescroll{
			position: fixed;
			top: 61px; /*这里改成你要偏移的距离*/
			bottom: 0;
			height: auto; /*如设置bottom:50px,则需height:auto才能生效*/
		}
