### ISSUE TITLE
mescroll-uni在IOS上滑会有卡顿

### ISSUE THREAD

**Issue by YY007H** [mescroll/mescroll#346]
在ios手机上偶尔会滑动不了，有时要2-3秒才能滑动，安卓不会。ios版本是13.4.1

**Comment by mescroll** [comment]
当设置:fixed="false"时  建议设置height固定mescroll的高度;  比如<mescroll :fixed="false" height="100%" top="40">

**Comment by gaoshanshanshan** [comment]
官方示例中的mescroll-swper在ios app端也会有这个问题，我测试的是在iphone7机型，是必先的。 @mescroll
