### ISSUE TITLE
strict 模式下不允许一个属性有多个定义

### ISSUE THREAD

**Issue by muziling** [mescroll/mescroll#347]
ie11下报 strict 模式下不允许一个属性有多个定义

看了下例子里这样写的：
<mescroll-body ref="mescrollRef" @init="mescrollInit" :down="downOption" @down="downCallback" :up="upOption" @up="upCallback"
		 @emptyclick="emptyClick">

有两个down，两个up，这种名字相同导致IE11下没办法使用

**Comment by mzongx** [comment]
请问你解决了吗

**Comment by mescroll** [comment]
已在1.2.6版本修复 请更新
