### ISSUE TITLE
华为P30、红米note70Pro，自带浏览器上拉到最后一页数据后，卡住不动

### ISSUE THREAD

**Issue by Supermanqiang** [mescroll/mescroll#348]
Safari、Android其他自带浏览器都可以正常使用，华为P30、红米note70Pro，自带浏览器上拉到最后一页数据后，卡住不动，所有操作都进行不了

**Comment by mescroll** [comment]
使用mescroll-uni + flex布局 http://www.mescroll.com/qa.html?v=20200522#q26
