### ISSUE TITLE
上拉加载触发不了，一直显示加载中

### ISSUE THREAD

**Issue by Yao916952836** [mescroll/mescroll#350]
h5和小程序， 用的 swiper嵌套的mescroll-uni ，上拉触发不了，一直显示加载中， 但是主动触发了一下下拉刷新后， 就可以正常触发上拉了，很奇怪， 有木有遇到这种问题的大佬

**Comment by mescroll** [comment]
对比一下demo; 可能是下标没有传正确;  默认第一个下标配置的auto为true
