### ISSUE TITLE
在小程序运行会提示 'isPreventDefault' of undefined;

### ISSUE THREAD

**Issue by lany9527** [mescroll/mescroll#351]
## 安装包：
 npm install --save mescroll-uni
## 参考配置：
http://www.mescroll.com/uni.html?v=20200522#mescrollbody
## 运行报错如下 ：
![image](https://user-images.githubusercontent.com/19483798/83477635-4cf7a780-a4c6-11ea-948f-99d63967b507.png)

## 定位报错源码 在小程序里面 #ifdef H5 这个条件注释里面的逻辑被执行了， 十分诡异
![image](https://user-images.githubusercontent.com/19483798/83477681-6e589380-a4c6-11ea-9fb8-b60f322f8fbd.png)

不知道作者有什么解决办法

**Comment by mescroll** [comment]
HBuilderX可能对npm安装的不做条件编译... 建议拷贝到components目录下 不用npm安装
