### ISSUE TITLE
mescroll-uni在钉钉小程序中下拉刷新用不了？

### ISSUE THREAD

**Issue by ydydydq** [mescroll/mescroll#353]
我在微信小程序一切都正常，在HBuilderX中添加了钉钉小程序，运行过去，下拉刷新就无法用了，事件也不触发。。。。。

**Comment by ydydydq** [comment]
通过测试在scroll-view上的touch事件基本没触发，暂时在外面包了一层view将事件放在了上面，就解决了。记得页面要设置"allowsBounceVertical": "NO"，要不页面下拉会冲突，很奇怪

**Comment by mescroll** [comment]
感谢反馈~
