### ISSUE TITLE
布局涉及到绝对定位问题（安卓小程序端）

### ISSUE THREAD

**Issue by Aliveqiao** [mescroll/mescroll#354]
布局绝对定位问题，在安卓端有问题，例如，一张图片绝对定位，在慢慢触发下拉，图片是脱落整个文档流

**Comment by mescroll** [comment]
方便发重现DEMO到我邮箱不 mescroll@qq.com

**Comment by Aliveqiao** [comment]
已发你邮箱。

**Comment by mescroll** [comment]
亲 没有看到您的demo 只收到一个图片..

**Comment by mescroll** [comment]
不可以设置 image{will-change: transform}
