### ISSUE TITLE
关于mescroll 上拉加载的时候，后台返回没有更多的数据，调用 mescroll.showNoMore(); 显示上拉无更多数据的布局之后，当重置列表的数据的时候，如何重新触发上拉加载的回调

### ISSUE THREAD

**Issue by liangjuncheng1995** [mescroll/mescroll#357]
使用场景，比如做一个搜索的组件，搜索一个关键词，“张杰”，展示对应“张杰”的数据列表,当第一个列表上拉的时候使用没有了数据
，需要提示用户，已经没有数据了，可以使用mescroll.showNoMore(); 方法
可是在此基础上 再搜索一个 关键词 “邓紫棋” 再生成另外的一个列表，上拉是触发不了上拉加载的回调的
请问有什么方案解决吗？

**Comment by mescroll** [comment]
你用复杂了.. 其实很简单的使用 mescroll.resetUpScroll的方法即可; 建议您看看这个案例,真的很简单 http://www.mescroll.com/preview.html?name=search
