### ISSUE TITLE
this.mescroll.getScrollTop() 获取高度一直为0

### ISSUE THREAD

**Issue by z605666069** [mescroll/mescroll#359]
因为底部导航的原因，所以一些页面使用了组件的方式去引入，这就导致了，如果我使用mescroll-body ，在主页面使用onPageScroll调用子组件的方法，但是获取的scroll的高度一直为0，使用mescroll-uni 不会触发@scroll 方法，请问这个问题有什么办法可以解决吗

**Comment by z605666069** [comment]
因此引发出 真机上无法上滑的bug  希望解决 谢谢

**Comment by mescroll** [comment]
mescroll-body写在子组件,需要引入 mescroll-comp.js 参考mescroll-comp的示例;
使用mescroll-uni就简单很多,不需要引入mescroll-comp, 没有触发@scroll的原因是不是没有配置up的onScroll:true ? 如果有配置, 那么再给mescroll-uni加上height属性试试,比如 <mescroll-uni height="100%" top="88"
