### ISSUE TITLE
下拉刷新与移动端chrome的下拉刷新冲突

### ISSUE THREAD

**Issue by michaeljfei** [mescroll/mescroll#36]
移动端的chrome下拉手势会与插件的下拉刷新冲突，会导致整个页面重新刷新

**Comment by mescroll** [comment]
亲 我在iphone和android手机都下载了chrome  
测试没有发现你说的那个这问题哦;  
如果您测试是有问题的话 返回提供一下手机的型号吗?
当然web端的话 下拉刷新其实用处不大,可以配置不使用下拉刷新 哈哈
