### ISSUE TITLE
mescroll 与 uview ui BUG

### ISSUE THREAD

**Issue by 1514100951** [mescroll/mescroll#365]
使用 mescroll 与 uview ui 在app端不兼容
> h5端正常显示
![2HPRH UMP~905TE@RZC0YAX](https://user-images.githubusercontent.com/45170904/89250409-4e208e80-d647-11ea-8e17-2762164843a4.png)
> app 真机端异常
![N0OS}Z7L7H7@VYVT32UD{5D](https://user-images.githubusercontent.com/45170904/89250415-51b41580-d647-11ea-882d-0e781710bb82.jpg)

**Comment by mescroll** [comment]
重现的bug发我邮箱 mescroll@qq.com
