### ISSUE TITLE
【BUG】mescroll-body设置 :fixed="true" top="100" 时 没有铺满全屏幕，无法上拉加载更多，也没有显示 上拉加载的文字提示

### ISSUE THREAD

**Issue by zhangyq233** [mescroll/mescroll#366]
![微信图片_20200805105504](https://user-images.githubusercontent.com/28673757/89366808-2ba37980-d70a-11ea-892e-abcc020a0d92.png)

**Comment by zhangyq233** [comment]
![微信图片_20200805105504](https://user-images.githubusercontent.com/28673757/89366866-470e8480-d70a-11ea-80b8-4326c287376f.png)

**Comment by mescroll** [comment]
mescroll-body本身就没有fixed的属性; 只有mescroll-uni才有; mescroll-body是page的滚动,本身就是基于整个页面的; 建议您下载DEMO对比一下看看哈
