### ISSUE TITLE
mescroll.js在H5上，如果mescroll容器里面包含其他滚动条，则会冲突

### ISSUE THREAD

**Issue by mzongx** [mescroll/mescroll#367]
mescroll.js在H5上，如果mescroll容器里面包含其他滚动条，则会冲突，比如我再mescroll容器里面放一个div，设置overflow-y:auto,这样可以下拉滚动没有问题，但是div下拉的时候会触发mescroll的下拉刷新

**Comment by mescroll** [comment]
如果mescroll内部存在overflow:auto的div, 对这div阻止touchmove的事件冒泡即可

document.getElementById("xxx").addEventListener('touchmove',function(e){
				e.stopPropagation()
			})
