### ISSUE TITLE
1.3.2版本 uniapp app打包后报错导致下拉异常

### ISSUE THREAD

**Issue by StriveNuby** [mescroll/mescroll#369]
- uniapp版本

2.8.6.20200814

- mescroll版本

1.3.2

- 系统环境

window8 64位

- 报错

TypeError: Cannot read property 'bottomOffset' of undefined at view.umd.min.js:1

- 问题描述

升级到1.3.2后，打包app时报以上错误导致下拉后无法回位，重新降级到1.2.5版本后，该问题没有出现

**Comment by mescroll** [comment]
我这边未出现此问题.. 使用最新的编辑器
