### ISSUE TITLE
完美的插件

### ISSUE THREAD

**Issue by qiexinrui** [mescroll/mescroll#371]
1.文档很完整，也很详细
2.插件功能比较全，很人性化，可以随心所欲
3.兼容问题暂时还没有，在ios和安卓手机上均无异常表现
4.配置也不麻烦，文档写的很清楚
简单就说这么多，我这边就是希望有一个流畅的上拉加载，这个插件完美符合我的预期，甚至还提供了没有数据展示时显示的图片，很赞，作者很用心

**Comment by ErrorJe** [comment]
确实不错，之前在写 uni-app 的时候，各端兼容性都还不错
