### ISSUE TITLE
安卓和微信运行正常，ios 上滑会误触发上拉加载

### ISSUE THREAD

**Issue by Qfish007** [mescroll/mescroll#375]
问题1：iOS，页面有内容时，有时上拉会滑不到，但是触发了上拉加载（偶尔）
问题2: iOS，按住屏幕下拉一点不松手，在上滑，滑不动 （必现）

**Comment by mescroll** [comment]
不知道您说的是不是这个问题: 
https://ask.dcloud.net.cn/question/98881
https://www.mescroll.com/uni.html?v=20200807#note 第三点

如果都不是 建议再仔细对比最新demo哈
