### ISSUE TITLE
下拉刷新的优化建议

### ISSUE THREAD

**Issue by night-Magicl** [mescroll/mescroll#378]
当无更多数据的dom存在时，在下拉刷新的时候，有时候会同时展示加载中和暂无更多数据的情况，建议在执行下拉刷新的方法中先隐藏无更多数据的dom，或者提供一个隐藏方法，方便用户手动隐藏，最后谢谢小姐姐写的组件，很好，很强大！！！

**Comment by mescroll** [comment]
mescroll-uni无此问题哈, 如果是mescroll.js 我检查一下

**Comment by wyhPro** [comment]
mescroll.endSuccess(num,true); 后再下拉刷新 nomoredata一直在那，不能再下拉

**Comment by mescroll** [comment]
下拉刷新 downCallback 需要调用一下 this.mescroll.resetUpScroll()
