### ISSUE TITLE
merscroll 嵌套video 下拉刷新时，video固定住，不会随着下拉内容滚动

### ISSUE THREAD

**Issue by wlingf** [mescroll/mescroll#379]
merscroll 嵌套video, 当第一项数据有video组件时，此时下拉刷新数据时，video会固定住，不会随着内容一起向下滚动

**Comment by mescroll** [comment]
APP端下拉时video脱离文档流的问题, 已在1.3.3版本的 mescroll-options.vue 提供解决方案, 请下载查看
