### ISSUE TITLE
mescroll-uni快速下拉到最底部，再下拉，直接触发下拉刷新。

### ISSUE THREAD

**Issue by XiaoLeaf** [mescroll/mescroll#382]
场景：有一个左右两侧的分类页面。右侧是mescroll-uni。点击左侧的分类栏目，使用mescroll.scrollTo(viewId)方法滑动至最底部。再下拉就触发了下拉刷新。

**Comment by mescroll** [comment]
亲 https://ext.dcloud.net.cn/plugin?id=343 已经提供现成的示例哈
