### ISSUE TITLE
不是bug

### ISSUE THREAD

**Issue by Leo2018Wu** [mescroll/mescroll#388]
请问支持一次滚动一屏的功能吗

**Comment by mescroll** [comment]
不是很懂,,, 这个需求应该直接用swiper实现比较好吧

**Comment by Leo2018Wu** [comment]
嗯那，我最后也是选择swiper实现的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mescroll"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 下午3:54
收件人: "mescroll/mescroll"<mescroll@noreply.github.com&gt;; 
抄送: "淘宝网"<2273952345@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mescroll/mescroll] 不是bug (#388)





 
不是很懂,,, 这个需求应该直接用swiper实现比较好吧
