### ISSUE TITLE
Android微信端上拉加载更多的bug

### ISSUE THREAD

**Issue by web-tiny** [mescroll/mescroll#4]
我用多个android的微信端测试，出现如下bug：下拉刷新没问题，上拉加载更多的时候没有任何反应，而且我一次请求的数据超出一屏的时候隐藏了；
IOS的微信端测试没有任何问题；求解决！

**Comment by mescroll** [comment]
@web-tiny  您应该是QQ上联系我的 对吧 已经帮您解决 原因是您设置了一个全局的样式 *{touch-action: none} 导致的哈~  另外O(∩_∩)O谢谢你的大红包 哈哈
