### ISSUE TITLE
官网mescroll-uni页面，有个单词打错了

### ISSUE THREAD

**Issue by npmrun** [mescroll/mescroll#401]
![image](https://user-images.githubusercontent.com/62639956/104402393-26880780-5591-11eb-86ab-73106926a354.png)

**Comment by mescroll** [comment]
发的图片看不到 不知道哪个单词打错了..

**Comment by npmrun** [comment]
锁定下拉刷新(isLock=ture

**Comment by mescroll** [comment]
Thanks♪(･ω･)ﾉ
