### ISSUE TITLE
支付宝小程序 使用swiper 会导致下拉刷新失效

### ISSUE THREAD

**Issue by MioGu** [mescroll/mescroll#404]
即使运行 案例中 mescroll-swiper.vue 在支付宝小程序下 还是会导致 下拉加载失效。

**Comment by mescroll** [comment]
奇怪了,有的HBuilderX版本可以, 建议此种情况使用支付宝小程序自带的了, 配置down的native: true,  需在pages配置"enablePullDownRefresh":true 和 "mp-alipay":{"allowsBounceVertical":"YES"}
