### ISSUE TITLE
mescroll-uni.vue中upLoadType值更新后页面未刷新导致加载中状态一直存在

### ISSUE THREAD

**Issue by gui-gu-zi** [mescroll/mescroll#410]
使用版本："mescroll-uni": "^1.3.7",
问题描述：
使用npm在uni-app项目中安装的mescroll，安装之后我按照文档提示进行配置，配置完之后我发现无论是触发上拉加载还是下拉刷新，在请求结束之后加载中的状态都不消失，于是我打印了源码中对参数信息
打印部分对映代码（mescroll-uni.js）：
MeScroll.prototype.endSuccess = function(dataSize, hasNext, systime) {
	let me = this;
	// 结束下拉刷新
	if (me.isDownScrolling) {
		me.isDownEndSuccess = true
		me.endDownScroll();
	}

	// 结束上拉加载
	if (me.optUp.use) {
		let isShowNoMore; // 是否已无更多数据
		if (dataSize != null) {
			let pageNum = me.optUp.page.num; // 当前页码
			let pageSize = me.optUp.page.size; // 每页长度
			// 如果是第一页
			if (pageNum === 1) {
				if (systime) me.optUp.page.time = systime; // 设置加载列表数据第一页的时间
			}
			if (dataSize < pageSize || hasNext === false) {
				// 返回的数据不满一页时,则说明已无更多数据
				me.optUp.hasNext = false;
				if (dataSize === 0 && pageNum === 1) {
					// 如果第一页无任何数据且配置了空布局
					isShowNoMore = false;
					me.showEmpty();
				} else {
					// 总列表数少于配置的数量,则不显示无更多数据
					let allDataSize = (pageNum - 1) * pageSize + dataSize;
					if (allDataSize < me.optUp.noMoreSize) {
						isShowNoMore = false;
					} else {
						isShowNoMore = true;
					}

					me.removeEmpty(); // 移除空布局
				}
			} else {
				// 还有下一页
				isShowNoMore = false;
				me.optUp.hasNext = true;
				me.removeEmpty(); // 移除空布局
			}
		}
		console.log(isShowNoMore, "isShowNoMore======")
		// 隐藏上拉
		me.endUpScroll(isShowNoMore);
	}
}

/* 结束上拉加载 */
MeScroll.prototype.endUpScroll = function(isShowNoMore) {
	console.log(isShowNoMore, "isShowNoMore我进来了")
	if (isShowNoMore != null) { // isShowNoMore=null,不处理下拉状态,下拉刷新的时候调用
		if (isShowNoMore) {
			console.log("isShowNoMore=true,显示无更多数据")
			this.showNoMore(); // isShowNoMore=true,显示无更多数据
		} else {
			console.log("isShowNoMore=false,隐藏上拉加载")
			this.hideUpScroll(); // isShowNoMore=false,隐藏上拉加载
		}
	}
	this.isUpScrolling = false; // 标记结束上拉加载
}
打印部分对映代码（mescroll-uni.vue）：
// 隐藏上拉加载的回调
hideUpScroll(mescroll) {
    vm.upLoadType = mescroll.optUp.hasNext ? 0 : 3;
    console.log(mescroll.optUp.hasNext,"mescroll.optUp.hasNext",vm.upLoadType, "vm.upLoadType","隐藏上拉加载的回调")
},
打印对结果及页面展示：
![image](https://user-images.githubusercontent.com/23214175/115643741-ebdff900-a34f-11eb-8d96-005b2be2ec37.png)

问题结果：
当upLoadType值更新为3的时候，页面上得到的upLoadType值却是1，这就导致加载中的状态一直不消失

**Comment by free-leaves** [comment]
这部分是我方便在页面上展示upLoadType的值，做的修改

					
					<view v-if="mescroll.optUp.use && !isDownLoading && upLoadType!==3" class="mescroll-upwarp" :style="{'background':mescroll.optUp.bgColor,'color':mescroll.optUp.textColor}">
						
						<view v-show="upLoadType===1">
							<view class="upwarp-progress mescroll-rotate" :style="{'border-color':mescroll.optUp.textColor}"></view>
							<view class="upwarp-tip">{{ mescroll.optUp.textLoading+"upLoadType的值"+ upLoadType }}</view>
						</view>
						
						<view v-if="upLoadType===2" class="upwarp-nodata">{{ mescroll.optUp.textNoMore }}</view>
					</view>

**Comment by free-leaves** [comment]
我项目是使用cli建立的使用npm引入的就有这个问题，我把组件改成在本地components目录上就没有这个问题了，搞不明白怎么回事

**Comment by mescroll** [comment]
没试过npm引入,,这个还是直接下载改到本地好了
