### ISSUE TITLE
文件地址引用bug

### ISSUE THREAD

**Issue by wzhsh90** [mescroll/mescroll#411]
mescroll-body.vue
mescroll-uni.vue

<script src="wxs/wxs.wxs" module="wxsBiz" lang="wxs"></script>

src 路径没有加载相对位置，编译报错

修改为：

<script src="./wxs/wxs.wxs" module="wxsBiz" lang="wxs"></script>

**Comment by mescroll** [comment]
一直都是相对地址, 您这边可能被改过吧
