### ISSUE TITLE
在h5下，使用mescroll-body滚动问题

### ISSUE THREAD

**Issue by jiadaoyun** [mescroll/mescroll#414]
在h5下，使用mescroll-body滚动的时候，会导致uni-app的onPageScroll方法失效，里面的数值不会发生改变

**Comment by mescroll** [comment]
mescroll-body就是监听onPageScroll的,  如果onPageScroll都失效了,那么mescroll-body也有问题, 原因很可能是项目中公共样式导致的 , 你可以新建一个空页面 就监听onPageScroll是否执行.. 如果不能执行就检查一下 body,html是不是设置了overflow
