### ISSUE TITLE
请问当数据不满一页时，执行endBySize等方法不显示 END状态，是故意这么设计的吗？

### ISSUE THREAD

**Issue by dongjianghao** [mescroll/mescroll#418]
数据条数只有2、3条的时候，执行了 endBySize(datasize=2, total=2); 后

不显示底部的 -- END --

但是增加数据为10+条后，能正常显示咧

**Comment by mescroll** [comment]
是的 通过up的noMoreSize配置, 默认是5, 您可以改为1或者0
