### ISSUE TITLE
数据初始化成功,上拉事件未触发

### ISSUE THREAD

**Issue by 7777777zll** [mescroll/mescroll#42]
mounted : function(){
     this.getList();
  },
  methods: {
      getList(){
      // 上拉加载
      this.mescroll = new MeScroll("mescroll", { //第一个参数"mescroll"对应上面布局结构div的id
        up: {
              callback: this.upCallback, //上拉回调
              empty:{ 
                warpId:"dataList",
                icon : "../res/img/mescroll-empty.png" , 
                  tip : "亲,暂无相关数据哦~" , 
              }
            }
      })
      document.getElementById("dataList").style.display="block";
    },
    //上拉加载的回调 page = {num:1, size:10}; num:当前页 从1开始, size:每页数据条数
    upCallback(page) {
      console.log('kaishi')
      var pageIndex = page.num-1;
        //联网加载数据
        var self = this;
        this.getListDataFromNet(pageIndex, page.size, function(curPageData) {     
          //如果是第一页需手动制空列表
          if(page.num == 1) self.pdlist = [];   
          //更新列表数据
          self.pdlist = self.pdlist.concat(curPageData);         
        }, function() {
          self.mescroll.endErr();
        });
    },
    getListDataFromNet(pageNum,pageSize,successCallback,errorCallback) {
      console.log(pageNum*pageSize)
      this.prames.page=pageNum
      SerachOrder.condition({params: this.prames})
        .then((response) => {
          var data=response.content;
          var total=response.total;
          var listData=[];
          console.log(total)
          for (var i = (pageNum)*pageSize; i < (pageNum+1)*pageSize; i++) {
            if(i==total) break;
              listData.push(data[i]);
            }
            successCallback&&successCallback(listData);//成功回调  
            }, (response) => {
            console.log('fail')
          })   
      }
    }

**Comment by mescroll** [comment]
callback: this.upCallback, //上拉回调
这个this指向会不会有问题, 检查一下;

然后再检查一下官网的第一个常见问题,样式的问题
