### ISSUE TITLE
有关mescroll-uni的问题，mescroll-upwarp什么的样式失效

### ISSUE THREAD

**Issue by npmrun** [mescroll/mescroll#423]
第一次滑动的时候是正常的，截图如下：
![image](https://user-images.githubusercontent.com/62639956/131205652-7138eec4-05e8-413f-a66f-ff5643548682.png)
然后下拉刷新，在拉到最下面，样式就变了：
![image](https://user-images.githubusercontent.com/62639956/131205669-636a2906-f624-41cd-8307-a2056aabac00.png)
可以看到上面的hash值变了，然后样式就失效了。
如果我在列表内容外多加一层view就变正常了，hash没有变：
![image](https://user-images.githubusercontent.com/62639956/131205682-f454058d-df40-40cd-bf9a-e2f6e01e809d.png)
或者在外边包一层view也可以：
![image](https://user-images.githubusercontent.com/62639956/131205790-0197b270-79da-484d-873a-58a6dffdb560.png)

不知道是uniapp的bug还是啥。

**Comment by mescroll** [comment]
HBuilderX版本的问题, 更新一下就好
