### ISSUE TITLE
下拉刷新无效    hbuilderX的版本是3.2.9

### ISSUE THREAD

**Issue by cookie-cong** [mescroll/mescroll#425]
uni-app里的项目，使用mescroll-body之后，安卓机在企业微信里无法下拉刷新，只有在企业微信里有问题，并且只有安卓机有问题，下拉刷新没有反应，只有第一次加载的时候会走刷新那个回调。之后就没有任何反应了，请问能帮忙排查一下到底是编辑器版本的问题导致编译出现问题还是自身插件的问题。比较急，谢谢啦，辛苦了

**Comment by cookie-cong** [comment]
我是企业微信，安卓下拉刷新没有效果  编辑器是3.2.9 我用的是mescroll-uni 下面的mescroll-more和mescroll-more-item这个示例，而且把你们的案例运行到企业微信上也是不能刷新

**Comment by mescroll** [comment]
可能是因为企业微信不支持wxs导致的, 解决方案:
```
在package.json中,加入
{
	"uni-app": {
		"scripts": {
			"mp-qywx": {
				"title": "企业微信",
				"env": {
					"UNI_PLATFORM": "mp-weixin"
				},
				"define": {
					"MP-QYWX": true
				}
			}
		}
	}
}

然后,发行的时候选择"自定义发行--企业微信", 这时mescroll就不走wxs的逻辑,走普通监听touch事件的逻辑
```
