### ISSUE TITLE
插件是被封了吗,访问官网提示有大量用户举报

### ISSUE THREAD

**Issue by ArthurMiao** [mescroll/mescroll#426]

**Comment by mescroll** [comment]
没有被封,可能是个别恶意举报的,,, 冤枉哇

**Comment by ArthurMiao** [comment]
谢谢咯


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mescroll/mescroll"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mescroll/mescroll] 插件是被封了吗,访问官网提示有大量用户举报 (Issue #426)





 
没有被封,可能是个别恶意举报的,,, 冤枉哇
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
