### ISSUE TITLE
endBySize之后如何重新启用上拉加载而不是reset

### ISSUE THREAD

**Issue by 1vanLuo** [mescroll/mescroll#428]
我的业务逻辑是有几个tab切换，如果某一个tab下的数据全部加载完了调用了endBySize，然后切换到另一个tab，这个tab已经加载过一次数据，但没有全部加载完，我想实现在这个tab下能继续上拉加载，而不调用resetUpScroll方法，因为resetUpScroll会把页码设为1从头加载数据。

**Comment by mescroll** [comment]
参考 mescroll-more的示例
