### ISSUE TITLE
minAngle设置异常

### ISSUE THREAD

**Issue by Hsinky** [mescroll/mescroll#43]
V1.2.3中设置minAngle：90并非垂直时才刷新，目前是约80-90这个区间就执行刷新了
但当设置大于90时，是可以的，但是下拉时 文字消失不见
代码详见 #44

**Comment by mescroll** [comment]
触发下拉最少要偏移的角度(滑动的轨迹与水平线的锐角值),取值区间 [0,90];默认45度,即向下滑动的角度大于45度(方位角为45°~145°及225°~315°)则触发下拉;而小于45度,将不触发下拉,避免与左右滑动的轮播等组件冲突;
注意:没有必要配置超出[0,90]区间的值,否则角度限制无效; 因为假设配置60, 生效的方位角就已经是60°到120° 和 240°到300°的范围了;

**Comment by Hsinky** [comment]
我已经设置成90，但80多的样子就可以刷新了

**Comment by mescroll** [comment]
如果是设置90 那么就必须下拉的偏移角度就是90 
如果是设置80 那么生效的角度是80到100
如果是设置70 那么生效的角度是70到110
如果是设置60 那么生效的角度是60到120
默认是45 生效的角度是范围是45到145

能找到规律没

不建议设置成90

**Comment by Hsinky** [comment]
明白你的规则，但现在需求就是90，因为页面上有多个tab，如果80多度就可以刷新，界面会很奇怪，一边在刷新，一边在显示另外的数据

**Comment by mescroll** [comment]
哦哦好的 您的意思是设置90无效; 可以暂时设置成89或者89.9 我看一下如何调整~ 迟点答复你 现在在杭州出差 1号回去 调试一下答复您
