### ISSUE TITLE
局部区域滚动

### ISSUE THREAD

**Issue by buquan** [mescroll/mescroll#439]

**Comment by buquan** [comment]
`
<template>
	<view>
		<view :style="{height: '1000px', backgroundColor: 'red'}"></view>
		<view :style="{height: '300px'}">
			<mescroll-uni :fixed="false" ref="mescrollRef" @init="mescrollInit" :down="downOption" @down="downCallback"
				@up="upCallback">
				<view class="notice">本Demo的下拉刷新: 添加新数据到列表顶部</view>
				<view class="news-li" v-for="news in dataList" :key="news.id">
					<view>{{news.title}}</view>
					<view class="new-content">{{news.content}}</view>
				</view>
			</mescroll-uni>
		</view>
	</view>


</template>
`

demo中list-news改成上面这种写法，也就是如果mescroll-nui组件不在首屏可视区内，则无法触发下拉刷新，
另外如果我使用mescroll-body组件怎么做到局部滚动，
请指教^_^

**Comment by mescroll** [comment]
mescroll-uni不再首屏内确实无法触发下拉刷新, 如果能执行下拉刷新,就无法再滑动到顶部了..  mescroll-body也是一样的,下拉刷新只能在滚动条到顶部的时候触发
