### ISSUE TITLE
下拉闪烁且伴有卡顿

### ISSUE THREAD

**Issue by Hsinky** [mescroll/mescroll#44]
V.1.2.3中下拉时有闪烁，代码如下，求指导

![image](https://user-images.githubusercontent.com/10111222/32084637-ec922a2e-bafc-11e7-9c59-78c9fe2c5693.png)

**Comment by mescroll** [comment]
你给item1mobile的div设置硬件加速的样式试试;

-webkit-transform:translateZ(0);
-webkit-transform-style:preserve-3d;
-webkit-backface-visibility:hidden;
-webkit-perspective:1000

**Comment by pdwjun** [comment]
htmlNodata 是放在 up里面的， 不是down
