### ISSUE TITLE
TypeError: Cannot read property 'nv_optDown' of undefined

### ISSUE THREAD

**Issue by indiboy** [mescroll/mescroll#449]
TypeError: Cannot read property 'nv_optDown' of undefined

**Comment by zhuyihongwei** [comment]
![image](https://user-images.githubusercontent.com/48353625/195973469-3c83b806-c624-4fcd-a8ca-29abf5ab14c6.png)
![image](https://user-images.githubusercontent.com/48353625/195973509-55261686-e7e5-494d-a2a4-f689edc8a3c3.png)

**Comment by zhuyihongwei** [comment]
> TypeError: Cannot read property 'nv_optDown' of undefined

**Comment by mescroll** [comment]
感谢反馈,已在1.3.8版本修复

**Comment by gitboyzcf** [comment]
npm 包麻烦跟进下 谢谢
