### ISSUE TITLE
【优化】Empty配置项fixed:true, top值为百分比，刷新空白图会闪动

### ISSUE THREAD

**Issue by Connerli** [mescroll/mescroll#458]
https://user-images.githubusercontent.com/16755393/228109209-f4089dfb-9200-47b7-9aa7-08ba45c8d5cc.mp4
![image](https://user-images.githubusercontent.com/16755393/228109927-f35d7427-0e13-43ba-83ce-cf6ee12e2ee1.png)

暂时使用具体数值来解决。

**Comment by mescroll** [comment]
确实如此.. 下拉刷新使用了transform..这个属性会使fixed元素降级为absolute...
