### ISSUE TITLE
uniapp微信小程序全局引入 偶尔会报错 不明白为什么！

### ISSUE THREAD

**Issue by JoyWang1024** [mescroll/mescroll#459]
![image](https://user-images.githubusercontent.com/25610993/228292077-e5654ec9-2882-4638-8717-54f9c403f7f6.png)

**Comment by JoyWang1024** [comment]
概率大概是1/3左右 好多项目都使用你这个插件并且遇到了这个问题 不知道为什么！

**Comment by mescroll** [comment]
mescroll是遵循easycom的 不用全局引入注册组件的 直接用就行 建议下载demo看看
