### ISSUE TITLE
uni-app 小程序中  typeError: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by yjt1216** [mescroll/mescroll#465]
![13332753-CFDD-4091-9C1F-102DB255861C](https://user-images.githubusercontent.com/12771656/234484644-0464c280-07f8-413a-8fe4-069636b73396.png)

**Comment by yjt1216** [comment]
`
<template>
	<view>
		<nav-bar title="登录" backgroundColor="linear-gradient(to right, #39C9BC,#6DE8CC)"></nav-bar>
		<view class="top-wrap">
			<me-tabs v-model="tabIndex" :tabs="tabs" @change="tabChange"></me-tabs>
		</view>
		<mescroll-body @init="mescrollInit" top="120" @down="downCallback"
		 :up="upOption" @up="upCallback">
			<good-list :list="goods"></good-list>
		 </mescroll-body>
	</view>
</template>

<script>
	import MescrollMixin from "@/uni_modules/mescroll-uni/components/mescroll-uni/mescroll-mixins.js";
	import { apiGoods } from '@/api/mock.js'
	
	export default {
		mixins: [MescrollMixin],
		data() {
			return {
				upOption: {
					noMoreSize:4,
					empty: {
						tip: '暂无数据'
					}
				},
				goods: [],
				// tabs:[
				// 	{name:'待评估'},
				// 	{name:'待执行'},
				// 	{name:'执行中'},
				// 	{name:'已完成'}
				// ],
				tabs: [{name:'全部',type:'xx'}, {name:'奶粉',type:'xx'}, {name:'面膜',type:'xx'}, {name:'图书',type:'xx'}],
				tabIndex: 0
			}
		},
		methods: {
			upCallback(page) {
				let curTab = this.tabs[this.tabIndex]
				let keyword = curTab.name
				apiGoods(page.num, page.size, keyword).then(res=>{
					this.mescroll.endSuccess(res.list.lenght)
					if(page.num == 1) this.goods = []
					this.goods = this.goods.concat(res.list)
				}).catch(()=>{
					this.mescroll.endErr()
				})
			},
			tabChange() {
				this.goods = []
				this.mescroll.resetUpScroll()
			}
		}
		
	}
</script>

<style lang="scss">
	.top-wrap{
		z-index: 9990;
		position: fixed;
		top: --window-top;
		/* left: 0; */
		width: 100%;
		height: 120rpx;
		background-color: white;
	}
</style>

`

**Comment by yjt1216** [comment]
> <template>
	<view>
		<nav-bar title="登录" backgroundColor="linear-gradient(to right, #39C9BC,#6DE8CC)"></nav-bar>
		<view class="top-wrap">
			<me-tabs v-model="tabIndex" :tabs="tabs" @change="tabChange"></me-tabs>
		</view>
		<mescroll-body @init="mescrollInit" top="120" @down="downCallback"
		 :up="upOption" @up="upCallback">
			<good-list :list="goods"></good-list>
		 </mescroll-body>
	</view>
</template>

<script>
	import MescrollMixin from "@/uni_modules/mescroll-uni/components/mescroll-uni/mescroll-mixins.js";
	import { apiGoods } from '@/api/mock.js'
	
	export default {
		mixins: [MescrollMixin],
		data() {
			return {
				upOption: {
					noMoreSize:4,
					empty: {
						tip: '暂无数据'
					}
				},
				goods: [],
				// tabs:[
				// 	{name:'待评估'},
				// 	{name:'待执行'},
				// 	{name:'执行中'},
				// 	{name:'已完成'}
				// ],
				tabs: [{name:'全部',type:'xx'}, {name:'奶粉',type:'xx'}, {name:'面膜',type:'xx'}, {name:'图书',type:'xx'}],
				tabIndex: 0
			}
		},
		methods: {
			upCallback(page) {
				let curTab = this.tabs[this.tabIndex]
				let keyword = curTab.name
				apiGoods(page.num, page.size, keyword).then(res=>{
					this.mescroll.endSuccess(res.list.lenght)
					if(page.num == 1) this.goods = []
					this.goods = this.goods.concat(res.list)
				}).catch(()=>{
					this.mescroll.endErr()
				})
			},
			tabChange() {
				this.goods = []
				this.mescroll.resetUpScroll()
			}
		}
		
	}
</script>

<style lang="scss">
	.top-wrap{
		z-index: 9990;
		position: fixed;
		top: --window-top;
		/* left: 0; */
		width: 100%;
		height: 120rpx;
		background-color: white;
	}
</style>

**Comment by zxplethe** [comment]
我也遇到这个问题了,你是不是也使用了`uni-simple-router`这个路由插件,我把他注释掉就好了
或者修改`mescroll-top.vue`组件
```
<!-- 回到顶部的按钮 -->
<template>
	<image v-if="mOption.src" class="mescroll-totop"
		:class="[isShow ? 'mescroll-totop-in' : 'mescroll-totop-out', {'mescroll-totop-safearea': mOption.safearea}]"
		:style="{'z-index':mOption.zIndex, 'left': left, 'right': right, 'bottom':addUnit(mOption.bottom), 'width':addUnit(mOption.width), 'border-radius':addUnit(mOption.radius)}"
		:src="mOption.src" mode="widthFix" @click="toTopClick" />
</template>

<script>
	export default {
		props: {
			// up.toTop的配置项
			option: {
				type: Object,
				default () {
					return {}
				}
			},
			// 是否显示
			value: false, // vue2
			modelValue: false // vue3
		},
		computed: {
			// 优先显示左边
			mOption() {
				return this.option || {}
			},
			left() {
				return this.mOption.left ? this.addUnit(this.mOption.left) : 'auto';
			},
			// 右边距离 (优先显示左边)
			right() {
				return this.mOption.left ? 'auto' : this.addUnit(this.mOption.right);
			},
			// 是否显示
			isShow() {
				// #ifdef VUE3
				return this.modelValue
				// #endif
				// #ifdef VUE2
				return this.value
				// #endif
			}
		},
		methods: {
			addUnit(num) {
				if (!num) return 0;
				if (typeof num === 'number') return num + 'rpx';
				return num
			},
			toTopClick() {
				// #ifdef VUE3
				this.$emit("update:modelValue", false); // 使v-model生效 vue3
				// #endif
				// #ifdef VUE2
				this.$emit('input', false); // 使v-model生效 vue2
				// #endif
				this.$emit('click'); // 派发点击事件
			}
		}
	};
</script>

<style>
	/* 回到顶部的按钮 */
	.mescroll-totop {
		z-index: 9990;
		position: fixed !important;
		/* 加上important避免编译到H5,在多mescroll中定位失效 */
		right: 20rpx;
		bottom: 120rpx;
		width: 72rpx;
		height: auto;
		border-radius: 50%;
		opacity: 0;
		transition: opacity 0.5s;
		/* 过渡 */
		margin-bottom: var(--window-bottom);
		/* css变量 */
	}

	/* 适配 iPhoneX */
	@supports (bottom: constant(safe-area-inset-bottom)) or (bottom: env(safe-area-inset-bottom)) {
		.mescroll-totop-safearea {
			margin-bottom: calc(var(--window-bottom) + constant(safe-area-inset-bottom));
			/* window-bottom + 适配 iPhoneX */
			margin-bottom: calc(var(--window-bottom) + env(safe-area-inset-bottom));
		}
	}

	/* 显示 -- 淡入 */
	.mescroll-totop-in {
		opacity: 1;
	}

	/* 隐藏 -- 淡出且不接收事件*/
	.mescroll-totop-out {
		opacity: 0;
		pointer-events: none;
	}
</style>
```

**Comment by yjt1216** [comment]
> uni-simple-router
是的，用了uni-simple-router这个路由插件
mescroll-top 中 option 改为 mOption 等配置后 的确不显示之前的错误了
谢谢

**Comment by gatspy** [comment]
真是意向不到的问题。。。
