### ISSUE TITLE
从列表页到详情页，怎么从详情页返回列表时定位到点击的那条数据

### ISSUE THREAD

**Issue by jinleli** [mescroll/mescroll#47]
现在手机端和PC端都需要这个功能，发现从详情页返回的时候列表刷新了无法定位到点击的那条数据，有什么比较好的方法吗？谢谢

**Comment by yohanceli** [comment]
+1

**Comment by jinleli** [comment]
我现在是在列表页点击按钮跳转的时候记录下page和scroll，然后返回列表页的时候根据这两个cookie去取数，但是现在有个问题是mescroll又从page为0取了一次数据，所以页面上总的数据量就多了一页

**Comment by jinleli** [comment]
@yohanceli 这个插件确实挺不错，不需要自己动手加载之前加载过的数据，在离开该页面的时候记录下scrollTop值，然后到详情页，在列表页的setListData里面mescroll.scrollTo(scrollTop,0)它自动就像后台取数填充这一段滚动距离，不需要在去上拉加载触发upCallBack加载数据。之前还以为必须要页面有那么高的高度才能滚动到那个距离，不知道这个插件是怎么做到的
暂时这样实现了，但是如果后台数据发生变化比如删除新增，因为我的数据是倒序排列的最新添加的再最前面返回，定位可能就不准了
