### ISSUE TITLE
上拉刷新默认开启了下拉刷新，怎么关闭？我将down的use设置为false没效果

### ISSUE THREAD

**Issue by panjiefeng** [mescroll/mescroll#48]
我将down的use设置为false没效果，而且设置后上拉刷新在初始化后不加载数据了，上拉也没有效果。求解，在那儿进行设置

**Comment by panjiefeng** [comment]
上拉完全没反应，数据“加载中...”的提示也不会出现了

**Comment by mescroll** [comment]
如果不想使用上拉加载,只用下拉刷新则配置 down:{callback:downCallback},up:{use:false} 或者up不配置
如果只想用上拉加载,不想用下拉刷新则配置 down:{use:false},up:{auto:true,callback:upcallback}

**Comment by mescroll** [comment]
建议结合基础案例 参考文档 配置一下down:{auto:true,callback:downcallback},up:{auto:true,callback:upcallback} 这几个参数 看看效果就能理解了

**Comment by panjiefeng** [comment]
我试了只要给down的callback加上回调函数就会出错
例如：
`down{callback: successCallback}`
最后我采取的解决方案如下：
`var mescroll = new MeScroll(mescrollId, {
			down:{
				callback: null,
				offset: 300000,
				htmlContent: ""
			},
			up: {
				use:true,
				callback: getListData,
				noMoreSize: 5,
				empty:{
					tip: "暂无相关数据~"
				},
				clearEmptyId: null,
				toTop:{
					src: "",
					offset: 100
				}
			}
		});`

**Comment by mescroll** [comment]
要从错误出发解决问题  看看报什么错 是不是down的callback你写了page这个参数
 http://www.mescroll.com/api.html
