### ISSUE TITLE
下拉动画都有点卡

### ISSUE THREAD

**Issue by wcldyx** [mescroll/mescroll#5]
能把下拉动画改成 transform 的动画吗，这样就流畅些

**Comment by mescroll** [comment]
亲 我建议你尝试一下哦 transform 要加时间吧 每滑动1px都延时 更加卡顿 哈哈; 
下拉进度的动画和恢复高度的动画是有加css过渡的.

**Comment by Hopingocean** [comment]
页面第一次加载时页面滑动的卡顿感太明显了，有什么办法解决吗

**Comment by mescroll** [comment]
原因是你没有按照规范来使用mescroll哦 没有加上mescroll的样式
<div id="mescroll" class="game--ranking mescroll">  //id可以改;当时mescroll的class要加上呢

根本原因是 mescroll样式中的 -webkit-overflow-scrolling: touch; 启动决定性的作用

**Comment by Hopingocean** [comment]
e,谢谢，哎，原来就差这个东西呀，文档还是没有读清楚。（建议：可以在文档中明确标明mescroll类的这一作用^-^）

**Comment by wcldyx** [comment]
我是的意思是： 下拉时，不应该直接改变div的高度，用div把列表撑下去， 这样会导致浏览器重排，这样在手机端就会有点卡顿，如果换成用 translate3d 就流畅些

**Comment by yangqihua** [comment]
同样有个bug，就是下拉刷新的时候，连续下拉刷新（每次下拉只拉到提示”下拉刷新”就松开屏幕，也就是拉到半路，且连续的动作比较快），然后再往上滑滑动列表数据，此时浏览器会卡顿两三秒钟列表才会正常的滑动。如连续快速下拉两次到提示”下拉刷新”，然后再往上滑动屏幕，此时会卡顿两三秒钟

**Comment by nelhu** [comment]
我这边的问题是： 当用户触碰屏幕开始，到下拉生效，中间这段时间有延迟， 不知改怎样解决？

**Comment by mescroll** [comment]
各位亲 反馈的问题 已在1.2.5版本修复
http://www.mescroll.com/qa.html#q10
