### ISSUE TITLE
上拉刷新完成后，加载中不能隐藏

### ISSUE THREAD

**Issue by jusheng** [mescroll/mescroll#52]
vue里用，下拉刷新完成后，加载中不能隐藏，在成功回调里已经写了self.mescroll.endSuccess();数据也已经成功返回显示，不知什么原因，顶部一直显示加载中

**Comment by jusheng** [comment]
可否查看一下，很紧急的任务，加载完成后如何关闭顶部加载中

**Comment by mescroll** [comment]
贴一下完整的代码吧.. 或者发demo哦~ mescroll.endSuccess();就是会关闭顶部加载中的..
