### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by YYQ8023** [mescroll/mescroll#53]
1，高度，祖父容器是弹性布局，父容器的`flex-grow`是1，也就是自动撑满剩余的空间，此时不会触发上拉刷新，设一个值之后就可以，比如100%；
2，上拉刷新对于vue不够友好（至少我这么认为），目前我的需求是上拉时触发一个方法，具体的业务逻辑应该自行处理，只需要有一个开关去控制是不是显示加载中样式就可以了，不需要传参去获取数据啥的。

**不过还是要感谢作者的付出，谢谢~~**

**Comment by mescroll** [comment]
1.对的 如果父布局没有高度,则不会触发scroll事件; 如果不想设置高度,则可使用body为scroll区域的http://www.mescroll.com/preview.html?name=list-mescroll-body

2.已经有现成的方法满足您的需求 http://www.mescroll.com/api.html#others

**Comment by JoJiangz** [comment]
设置父容器的css为 `display: flex; flex-direction: column;`加上class=“mescroll”的div因为`.mescroll{height:100%;}`，弹性布局计算后，容器就会有高度，就可以解决无法触发上拉刷新的问题。
