### ISSUE TITLE
用了down option就必须手动设置

### ISSUE THREAD

**Issue by weituotian** [mescroll/mescroll#58]
```
 var mescroll = new MeScroll("mescroll", { //第一个参数"mescroll"对应上面布局结构div的id
            down: {
                callback: function () {

//                    console.log(page);

                    //下拉刷新的回调,别写成downCallback(),多了括号就自动执行方法了
                    NetModule.refresh(mescroll);

                }
            },
//            clearEmptyId: "select_list",
            up: {
                callback: function (page) {
                    console.log(page);
                    //上拉加载回调,简写callback:function(page){upCallback(page);}
                    NetModule.loadMore(mescroll);

                }
            }
        });
```

拉到底，显示end，列表全部显示完毕

然后刷新列表，数据全部清空后

然后继续往下，不能加载更多了

从
 `mescroll.endSuccess(）`
```
改为
                        mescroll.optUp.page.num = 1;
                        mescroll.endSuccess(data.pageResult.length, data.totalRowsCount);
```

必须手动设置num为1才可以加载更多

**Comment by mescroll** [comment]
down.callback默认调用mescroll.resetUpScroll(),而resetUpScroll会将page.num=1,再触发up.callback

所以你可以在down的callback调用mescroll.resetUpScroll(),

**Comment by weituotian** [comment]
首页readme的例子，只用了`mescroll.endSuccess(）`

**Comment by mescroll** [comment]
//方法二(推荐): 后台接口有返回列表的总数据量 totalSize
//必传参数(当前页的数据个数, 总数据量)
mescroll.endBySize(curPageData.length, totalSize);

**Comment by weituotian** [comment]
首页readme的文档中:

4. 处理回调:
```
        //下拉刷新的回调
        function downCallback(){
            $.ajax({
                url: 'xxxxxx',
                success: function(data){
                	//联网成功的回调,隐藏下拉刷新的状态;
        		mescroll.endSuccess();//无参
        		//设置数据
        		//setXxxx(data);//自行实现 TODO
               },
               error: function(data){
               		//联网失败的回调,隐藏下拉刷新的状态
        	        mescroll.endErr();
                }
            });
        }
```


其中的`mescroll.endSuccess();//无参`

就是这个地方

应该改为
```
mescroll.resetUpScroll(),
mescroll.endSuccess(...,);
```
才有效

**Comment by mescroll** [comment]
mescroll.resetUpScroll(), 写在downCallback里面

**Comment by weituotian** [comment]
mescroll.resetUpScroll() 确实有用

但是首页readme的例子中的downcallback 没有用到`mescroll.resetUpScroll()`

**Comment by mescroll** [comment]
嗯嗯 是的
如果您的下拉刷新是重置列表数据,那么down完全可以不用配置,具体用法参考第一个基础案例
解析: down内部默认调用的是mescroll.resetUpScroll(),而resetUpScroll会将page.num=1,再触发up.callback,从而实现刷新列表数据

例子想说明的意思是:
如果您的下拉刷新是重置列表数据,不配置down,内部也会默认调用了mescroll.resetUpScroll();
如果你配置了down,相当于你要自定义down的callback了,你可能会在down的callback刷新其他数据,比如轮播数据,用户信息,商品金额等等,如果你此时还想顺带刷新列表,则要手动调mescroll.resetUpScroll();因为你配置了down的callback覆盖了内部的mescroll.resetUpScroll();

**Comment by weituotian** [comment]
好吧，这样好理解了，thanks！
