### ISSUE TITLE
ios 滚动条高度重置后会闪烁

### ISSUE THREAD

**Issue by buhairong** [mescroll/mescroll#59]
因为页面上只想保留5页数据，所以当滑动到第六页时，开始把第一页删除掉，所以需要把滚动条高度重置。
代码如下：
if(u33_pages > 5){
                    var offset = $(divId + ' li:eq(' + page_size + ')').offset().top - $(divId + ' li:eq(0)').offset().top;
                    setTimeout(function(){
                        $(divId + ' li:lt(' + page_size + ')').remove();                      
                        mescroll.scrollDom.scrollTop = mescroll.scrollDom.scrollTop - offset;                        
                    },50);
                };

ios下会闪烁，安卓下不会，请问下这是什么原因？该如何解决呢？麻烦您了，谢谢！

**Comment by mescroll** [comment]
因为你是把前面的都删除了嘛 你可以试试先移动到顶部mescroll.scrollDom.scrollTop=0再删

**Comment by buhairong** [comment]
好的，谢谢，我明天试试看
