### ISSUE TITLE
无法触发上拉加载？

### ISSUE THREAD

**Issue by Hopingocean** [mescroll/mescroll#6]
按照 ‘mescroll所有配置项‘ demo进行初始化，可以触发下拉刷新，但是无法触发上拉加载，页面滚动时不能进入scroll事件，使用Vue框架，求提供一个思路

**Comment by mescroll** [comment]
亲 看看这个常见问题一哦 http://www.mescroll.com/qa.html#q1

**Comment by Hopingocean** [comment]
1.父容器不是body时只能使用position:fixed定位才能触发scroll事件吗，顶部菜单栏如果不适用fixed定位，在下拉时就会出现顶部菜单栏会被拉下来。
2.页面第一次加载时页面滑动的卡顿感太明显了，有什么办法解决吗？

**Comment by mescroll** [comment]
1.mescroll的高度默认是100%, 所以父容器要有高度哦,用fixed只是一种固定高度的方法.
2.页面第一次加载滑动卡顿?请问运行mescroll的案例会卡顿吗?
你是先隐藏mescroll的加载进度,再执行列表初始化的 对吧, 会不会列表还没初始化完毕呢;

**Comment by Hopingocean** [comment]
1.设置父容器固定高度无法触发scroll事件，通过fixed定位则可以，无奈脸？
2.运行mescroll的案例不会卡顿，但是我的页面第一次加载滑动卡顿，如果页面加载后下拉刷新一次滑动就流畅了，这是为什么？初始化mescroll的时候已经默认下拉加载一次了，但是还是需要再下拉刷新一次才行。

**Comment by mescroll** [comment]
不是很清楚你是如何写的哦 能发一下重现的案例给我吗? 发部分代码也行 mescroll@qq.com
