### ISSUE TITLE
请教下滚动条高度的问题

### ISSUE THREAD

**Issue by buhairong** [mescroll/mescroll#61]
目前业务需要页面上只保留5页数据，在拉到5页以后，再往回拉的时候，需要把前一页再加载出来，这时候滚动条是默认到顶部的。是否这是mescroll.scrollDom.scrollTop设置为0了呢？现在要求前一页加载出来时，滚动条停留在第二页开头的位置。
代码如下：
var offset = $(divId + ' li:eq(' + page_size + ')').offset().top - $(divId + ' li:eq(0)').offset().top;
                        setTimeout(function(){
                            mescroll.scrollDom.scrollTop = offset - 40;
                            $(divId + ' li:gt(' + (page_size * (save_page-1)-1) + ')').remove();
                        },50);
这时候页面会跳动一下。现在是希望页面不要跳动，请问mescroll可以设置吗？

**Comment by mescroll** [comment]
"在拉到5页以后，再往回拉的时候，需要把前一页再加载出来"

有几个地方不是很理解  "再往回拉"是指向下滑还是继续向上滑动列表 
前一页是指第4页 还是第6页
"把前一页再加载出来" 你是怎么加载的 调哪个方法

要不你提供一下完整可运用的demo 我帮您看看
