### ISSUE TITLE
在SPA下用这个,会导致切换路由时重复生成mescroll

### ISSUE THREAD

**Issue by cxylys** [mescroll/mescroll#63]
现在在做SPA用这个时,根据Body来做刷新加载,但是切换路由时对于没有引用的路由页还是默认加载了初始化时的mescroll对象,而且再切回上个页面时会重复生成mescroll对象,现在貌似只能在切换路由时删除这个mescroll对象,然后每个页面创建不同的mescroll对象不然会引用第一个mescroll对象配置里的东西。

**Comment by mescroll** [comment]
亲 .. 记得保持mescroll对象的单例哦
