### ISSUE TITLE
这是我再github上见过最用心的人

### ISSUE THREAD

**Issue by zwhGithub** [mescroll/mescroll#64]
这是我再github上见过最用心的人   厉害了 妹子

**Comment by mescroll** [comment]
感谢支持 还请大神多指教哈O(∩_∩)O~

**Comment by shimiso** [comment]
我苦苦寻找pull-to-refresh框架，希望找到一个最接近原生的，支持scrollTo  getPosition 还有对Refresh和load结束事件的捕获，结果搜到了mescroll，正是我想要的，简直量身定制，感谢

**Comment by w493189140** [comment]
作者真的很负责 ，有问题立马解决了

**Comment by acme-h** [comment]
再字写错了

**Comment by sushuier** [comment]
> 再字写错了

秀儿，秀儿，是你吗
