### ISSUE TITLE
react中使用时下拉刷新动画效果不出现

### ISSUE THREAD

**Issue by gluckMu** [mescroll/mescroll#67]
在react中使用时出现了下拉刷新动画效果不出现，但是触发下拉操作函数，调试的时候发现一开始加载时有mescroll-downwarp这个div，但是在第一次加载数据后就没有了，
react组件如下
render(props) {
    return (
      <div id='mescroll' class='mescroll'>
        { this.props.children }
      </div>
    )
  }

我理解可能是react在rerender的时候把手动插入的dom给覆盖掉了，所以想问作者大大有没有给react封装的组件

**Comment by mescroll** [comment]
我觉得跟平台没有关系哦
new Mescroll的时候 会自动创建mescroll-downwarp这个div的
你的理解是正确的 你看看插入的dom可以没有写对位置哦
