### ISSUE TITLE
移动端浏览器中无法全屏显示，无法隐藏浏览器顶部网址和底部菜单栏，请问有解决方法吗？

### ISSUE THREAD

**Issue by Hopingocean** [mescroll/mescroll#68]

**Comment by mescroll** [comment]
我看了一下你发的taptap 你说的全屏是指当列表向上滚动的时候 safari搜索栏会隐藏对吧 这个只能用body的方式 因为这个属于浏览器本身的功能 他是监听body的滚动事件的 ;  如果是div方式的mescroll,滚动事件在div了,所以浏览器的那个功能就木有了
