### ISSUE TITLE
up//上拉回调 变成了下拉刷新 ,上拉加载不能触发，为什么呢

### ISSUE THREAD

**Issue by shimiao105** [mescroll/mescroll#69]
用的vue  install后  在vue组件里import MeScroll from 'mescroll.js' ，up//上拉回调 变成了下拉刷新 ,上拉加载不能触发额。不知道为什么呀

**Comment by mescroll** [comment]
这个要检查一下mescroll.min.css和js是否都正常引入哦
可以参考 https://github.com/mescroll/mescroll/issues/56

**Comment by chenyu977564830** [comment]
我也是变成这样了，蛋疼
