### ISSUE TITLE
除了使用position：fixed定位可以触发上拉加载，还有其他方法触发上拉加载吗？父容器不是body

### ISSUE THREAD

**Issue by Hopingocean** [mescroll/mescroll#70]

**Comment by mescroll** [comment]
body为滚动区域的案例就不用设置高度;
如果mescroll的div方式的话 就要给div设置高度; 因为body的高度默认100%,你用div方式的话,可以给父元素也设置100%,这样不用fixed也行;

**Comment by Hopingocean** [comment]
确实如此，设置父元素高度100%也不能全屏显示，这就很尴尬了，看来只有以body为滚动区域的时候才能使网页全屏，但是我的项目使用vue框架，不能将id='vue'放到body上，这可怎么办呢？

**Comment by mescroll** [comment]
body为滚动区域的话 就不用写<div id="mescroll" class="mescroll">  这个div的
所以你直接在body写你的原本的列表内容即可
