### ISSUE TITLE
IOS touchstart 时， mescroll-bounce 的min-height 会增加

### ISSUE THREAD

**Issue by VidaPu** [mescroll/mescroll#71]
只设置了down 和 up的callback， 成功后endSuccess，每次点击或移动 class mescroll-bounc 的min-height都会增加

**Comment by mescroll** [comment]
嗯嗯 我在touchstart对mescroll-bounce做了最新高度的设置 :
mescroll.bounceDom.style.minHeight = (mescroll.getClientHeight() + 5) + "px";
请问会对你的项目造成什么不好的影响不 ?
