### ISSUE TITLE
我在vue-cli中new实例化时报 “ReferenceError: MeScroll is not defined”

### ISSUE THREAD

**Issue by GaoKeiis** [mescroll/mescroll#74]
![1512546996](https://user-images.githubusercontent.com/26155978/33650745-47087970-da9e-11e7-9712-40c10906ab1c.png)
![1512547008 1](https://user-images.githubusercontent.com/26155978/33650747-47cd13fc-da9e-11e7-8dfb-425d9c693b7b.png)
我引入的完全是按照官网上做的

**Comment by mescroll** [comment]
https://github.com/mescroll/mescroll/issues/56

亲看看这里的解决方案~

**Comment by GaoKeiis** [comment]
恩恩  已修改 谢谢解答
