### ISSUE TITLE
回调不是长耗时方法时，按住拖动时会不停的发起回调，而不是在放开时发起一次

### ISSUE THREAD

**Issue by liuyuesakura** [mescroll/mescroll#79]
self.mescroll = new MeScroll("vue-div",{
                    up: { // 上拉加载
                        auto:true,
                        callback: self.upCallback,
                        toTop: { // 返回顶部按钮
                            src:"/Image/mescroll-totop.png"
                        },
                        empty: { //配置列表无任何数据的提示
                            warpId: "dataList",
                            icon: "/Image/untip.png",
                        },
                    }
                });
                upCallback: function (page) {
                    var self = this;
                    console.log("page.num=" + page.num + ", page.size=" + page.size + ",datetime=" + (Date.now()));
                    self.mescroll.endSuccess(10,true);
                    //setTimeout(function() {
                    //    console.log("page.num=" + page.num + ", page.size=" + page.size);
                    //    self.mescroll.endSuccess(10,true);
                    //},2000);
                }
![image](https://user-images.githubusercontent.com/6565855/34512638-ad197118-f09e-11e7-8cfe-f170975c62d5.png)

**Comment by mescroll** [comment]
恩 建议在实际场景使用
正常情况下 你肯定不会写死self.mescroll.endSuccess(10,true);    (这两参数请填写实际参数)
而且你请求成功之后是要把数据添加到界面渲染出来的
所以真实使用的时候 当你联网成功 列表数据渲染 此时肯定不会在底部 也就不会一直触发
