### ISSUE TITLE
求教如何重新初始化

### ISSUE THREAD

**Issue by allycs** [mescroll/mescroll#8]
var mescroll = new MeScroll(。。。）
之后如何重新init？

**Comment by mescroll** [comment]
暂时没有重现初始化的方法哦;请问你的使用场景是什么呢 ,为什么需要重新初始化

**Comment by mescroll** [comment]
1.2.1版本已提供销毁mescroll的方法:
mescroll.destroy();
销毁之后可以重新mescroll = new MeScroll(。。。）;

**Comment by laughAnd** [comment]
mescroll.resetUpScroll( isShowLoading );

**Comment by IT0315** [comment]
how to use it in vue.js

**Comment by mescroll** [comment]
http://www.mescroll.com/api.html?v=0929#mescrollvue
