### ISSUE TITLE
下拉刷新重置页面数据

### ISSUE THREAD

**Issue by lutao198** [mescroll/mescroll#81]
function ( mescroll ) { 
    mescroll.resetUpScroll(); 
}
“下拉刷新的回调; 默认重置上拉加载列表为第一页”
有没有参数控制这个重置数据的方法？做VUE的时候，下拉刷新了，data里面还有数据，可是页面没展示出来，我想要的是下拉刷新成功后，把原来的数据清空了，直接换成新数据。可现在如果这样的话，下拉刷新后，数据不显示出来了

**Comment by mescroll** [comment]
这个建议您参考vue的案例 http://www.mescroll.com/preview.html?name=list-products-vue
mescroll.resetUpScroll()会调upCallback, 您只需查看upCallback的代码即可 
您可以参考判断如果是第一页手动清空数据
if(page.num == 1) self.pdlist = [];
