### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by oimmc** [mescroll/mescroll#82]
建议添加国际化：
{
    i18n: {
        downTip: '下拉刷新',
        freedTip: '释放更新',
        loading: '正在玩命加载...',
        nodata: '我是有底线的'
    },
    up: {
        //...
    },
    down: {
        //...
    }
}

**Comment by mescroll** [comment]
好的 谢谢您的建议
您可以暂时可根据 http://www.mescroll.com/preview.html?name=mescroll-options 案例代码里面的配置去实现国际化;

**Comment by mescroll** [comment]
uni版本已经有国际化的示例
