### ISSUE TITLE
搜索demo有个问题

### ISSUE THREAD

**Issue by lxfwelldone** [mescroll/mescroll#86]
下拉刷新时，刷新提示的控件，有时出现在热门上方，有时出现在下方。代码我没看，不知道是不是故意写出这种效果，但就我来说，这种体验度不是很好。
具体操作如下：在热门搜索下方点滑，刷新就会出现在下方。

**Comment by mescroll** [comment]
列表下拉刷新是真正下拉刷新的提示,在上方;
点击搜索其实是调mescroll.resetUpScroll,显示的其实是上拉加载的进度条;

如果你希望出现在上方其实也不合理吧..

如果你要自定义进度条的位置 可配置warpClass
