### ISSUE TITLE
下拉刷新，li重复

### ISSUE THREAD

**Issue by lxfwelldone** [mescroll/mescroll#87]
你好，我在使用ajax post请求时，下拉刷新，li就会重复显示了。是需要我自己手动移除之前的li吗？还是需要在down中或up中做什么配置吗？我尝试了在up中配置ClearId：“”，但是第一次就不显示了。

**Comment by mescroll** [comment]
如果您配置了ClearId 内部会自动判断如果是第一页则置空ClearId里面的内容,你需先调用endSuccess再设置li的数据

如果您不理解配置的话 建议你手动判断如果第一页则先清空列表 再添加li数据
