### ISSUE TITLE
在Vue中，下拉时不出现“加载中..”，首次加载时出现？请问如何解决？

### ISSUE THREAD

**Issue by zhongku** [mescroll/mescroll#89]
以下是封装的组件代码
![default](https://user-images.githubusercontent.com/16175495/35494262-64cf13d0-04f4-11e8-8252-e6dae007a93c.png)
![default](https://user-images.githubusercontent.com/16175495/35494271-744a552c-04f4-11e8-8f84-e289bea3b70e.png)
![default](https://user-images.githubusercontent.com/16175495/35494275-7d47108e-04f4-11e8-8e99-013997a95690.png)

以下时调用时调用的代码
![default](https://user-images.githubusercontent.com/16175495/35494253-4e89d8bc-04f4-11e8-95a2-8eac5abf4841.png)

数据显示图片
![default](https://user-images.githubusercontent.com/16175495/35494195-d306a8d2-04f3-11e8-9b34-fb49492e82b0.png)

目前有两个 问题
**1. 下拉时，不显示“加载中..”，体验非常不好
2. 下拉时，数据比较多的情况下，会遮住头部导航（数据量大概有1亿多条）**

非常感谢

**Comment by mescroll** [comment]
http://www.mescroll.com/api.html?v=0929#mescrollvue
