### ISSUE TITLE
关于vue

### ISSUE THREAD

**Issue by fenghouqianyu** [mescroll/mescroll#9]
说是支持vue却没有任何在vue里面使用的案例
而且我这边使用webpack搭建的vue脚手架
根本没有引导怎么在.vue文件中怎么引入的说明
也没有说明要配置什么选项

**Comment by mescroll** [comment]
不好意思 在整理还没发 公司的事情太多了 抱歉~ 目前版本支持vue只停留在和vue不冲突的层面, 脚手架接入还没整理好,本来打算这星期整理发出去一个新版本的,公司又安排一大堆事情过来,我得忙完公司的事情先咯,得推迟一段时间了哈~ 感谢支持,如耽误您了,抱歉哈

**Comment by mescroll** [comment]
您暂时把mescroll.js和mescroll.css当普通的js和css引用就好; vue使用的案例等我忙完公司的事情补上哈~

**Comment by mescroll** [comment]
已新增vue的示例, http://www.mescroll.com/preview.html?name=list-products-vue
另外 mescroll更新至1.1.5
