### ISSUE TITLE
建议作者封装一个可以直接使用的vue组件

### ISSUE THREAD

**Issue by dylan921208** [mescroll/mescroll#90]
每次都得引入css、js有点繁琐

**Comment by mescroll** [comment]
恩恩 是的 年底赶公司的项目太忙了 年后会更新 感谢支持 Thanks♪(･ω･)ﾉ

**Comment by mvpleung** [comment]
https://github.com/mvpleung/mescroll/blob/master/README_vue.md

**Comment by ShawshankLin** [comment]
@mvpleung 你这个是vue的插件吗？

**Comment by mvpleung** [comment]
@ShawshankLin  是的

**Comment by mescroll** [comment]
https://github.com/mescroll/mescroll/tree/master/demo/vue-demo

**Comment by mescroll** [comment]
http://www.mescroll.com/api.html?v=0929#mescrollvue
