### ISSUE TITLE
在手机上显示的时候，数据量稍微大一点，然后滑动过快的时候，内容会一闪而过，过1s再显示出来

### ISSUE THREAD

**Issue by yuch321** [mescroll/mescroll#95]
有哪个属性可以控制嘛？也用过什么iscroll,jscroll这样类似的框架，但是同时同样的问题。在pc端显示没有问题

**Comment by mescroll** [comment]
您反馈的其实不是各种框架的问题了,您可以试试不用任何框架,单纯写死大量列表数据,同样会有这样的问题;

这属于手机性能的问题,因为html网页并没有像android或者ios原生的列表有item复用的机制.

建议:

**Comment by huoruji** [comment]
我也遇到同样的问题，在安卓手机上表现的尤为明显
