### ISSUE TITLE
请问作者，微信小程序，可以用这个js库吗

### ISSUE THREAD

**Issue by flyfox11** [mescroll/mescroll#97]
请问作者，微信小程序，可以用这个js库吗，谢谢了

**Comment by flyfox11** [comment]
已经试过了，不可以，因为作者封装插件的时候用了大量的window document 所以是不可能用在微信小程序的

**Comment by hooray** [comment]
@flyfox11 微信小程序自带支持上拉加载下拉刷新，无需使用第三方实现

**Comment by mescroll** [comment]
最近正在写, 再稍等一个星期 ~

**Comment by uddsoft** [comment]
现在支持了吗。

**Comment by Calvin1121** [comment]
我也在等呢~😂现在支持小程序了吗？

**Comment by NineSu** [comment]
现在支持小程序了吗  😂

**Comment by mescroll** [comment]
近期没有计划写专门小程序版本的mescroll, 精力有限 抱歉..
小程序暂时使用uni-app版本的mescroll; 
http://www.mescroll.com/uni.html

**Comment by NineSu** [comment]
> 近期没有计划写专门小程序版本的mescroll, 精力有限 抱歉..
> 小程序暂时使用uni-app版本的mescroll;
> http://www.mescroll.com/uni.html

笔芯
