### ISSUE TITLE
关于demo里面快速切换tab列表重新加载的问题

### ISSUE THREAD

**Issue by Truety** [mescroll/mescroll#98]
您好，demo里面快速切换tab的时候，列表显示loading之后，界面会先显示前一个tab的列表，然后才会展现当前tab的列表，请问如何解决呢？

**Comment by mescroll** [comment]
你用的是单mescroll这个案例 对吗  你可以在发送请求时先清空列表的数据

多mescroll的案例不会有你说的问题哦

**Comment by Truety** [comment]
是【雅布力 v2.4.0】这个案例，多次快速切换tab，会出现下拉列表不停切换的问题。

**Comment by amazg** [comment]
@Truety 在你每次发送请求之前将列表里数据清空应该就可以了
